In [1]:
import tensorflow as tf
import numpy as np 

# tensor cost

In [2]:
x_data = [1,2,3]
y_data = [1,2,3]
x = tf.constant( x_data ,dtype=float)
y = tf.constant( y_data ,dtype=float)

In [10]:
w = 3 
hx = w * x  # [3,6,9]
sq = tf.square( hx - y )   # [3,6,9] - [1,2,3] = [2,4,6]^2 = [4,16,36]
cost = tf.reduce_mean( sq )

In [11]:
w,hx,sq, cost

(3,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 6., 9.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4., 16., 36.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=18.666666>)

# tensorGradient  (기울기)

In [12]:
from tensorflow.keras.optimizers import SGD

In [13]:
x_data = np.array([1,2,3,4,5])
y_data = np.array([3,5,7,9,11])

In [17]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [22]:
x = tf.constant(x_data,tf.float32)
y = tf.constant(y_data,tf.float32)

w = tf.Variable(10.0)
b = tf.Variable(10.0)

In [25]:
x.numpy(),y.numpy(),w.numpy(),b.numpy()

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([ 3.,  5.,  7.,  9., 11.], dtype=float32),
 10.0,
 10.0)

In [26]:
# hx설정 및 cost 구하는 함수

def compute_cost():
    hx = w * x + b    # hx = wx + b
    cost = tf.reduce_mean( (hx - y)**2) #cost = (예측값 - 실제값)의 제곱
    return cost


경사 하강법 구현

In [27]:
optimizer = SGD(learning_rate=0.01)   # 미분과 알파 
for i in range(2000):
    optimizer.minimize(compute_cost,var_list=[w,b] )# 손실함수의 최소값 찾기
    '''
    w = w  - 0.01 * (w에 대한 미분값)  w.assign_sub(0.01* 미분값)
    b = b -  0.01 * (b에 대한 미분값)  b.assign_sub(0.01* 미분값)
    '''
    print(i,"코스트",compute_cost().numpy())

0 코스트 712.17365
1 코스트 417.96567
2 코스트 246.49605
3 코스트 146.55228
4 코스트 88.29037
5 코스트 54.318737
6 코스트 34.50238
7 코스트 22.935177
8 코스트 16.17528
9 코스트 12.216979
10 코스트 9.891439
11 코스트 8.517516
12 코스트 7.6982765
13 코스트 7.202403
14 코스트 6.8950987
15 코스트 6.6978025
16 코스트 6.56474
17 코스트 6.4692297
18 코스트 6.395726
19 코스트 6.3351665
20 코스트 6.2822695
21 코스트 6.2339563
22 코스트 6.188433
23 코스트 6.1446543
24 코스트 6.102006
25 코스트 6.0601325
26 코스트 6.0188284
27 코스트 5.9779673
28 코스트 5.9374766
29 코스트 5.8973184
30 코스트 5.8574634
31 코스트 5.817895
32 코스트 5.7786064
33 코스트 5.7395887
34 코스트 5.7008376
35 코스트 5.662351
36 코스트 5.624126
37 코스트 5.5861588
38 코스트 5.548449
39 코스트 5.510995
40 코스트 5.4737926
41 코스트 5.436841
42 코스트 5.40014
43 코스트 5.3636866
44 코스트 5.327478
45 코스트 5.291515
46 코스트 5.255794
47 코스트 5.2203155
48 코스트 5.185076
49 코스트 5.150073
50 코스트 5.115308
51 코스트 5.080778
52 코스트 5.0464797
53 코스트 5.012414
54 코스트 4.9785776
55 코스트 4.94497
56 코스트 4.911588
57 코스트 4.878433
58 코스트 4.845502
59 코스트 4.812792
60 코스트 4.780302
61 코스트 

543 코스트 0.18140194
544 코스트 0.18017721
545 코스트 0.17896095
546 코스트 0.177753
547 코스트 0.17655303
548 코스트 0.17536132
549 코스트 0.17417741
550 코스트 0.17300154
551 코스트 0.17183386
552 코스트 0.17067388
553 코스트 0.16952164
554 코스트 0.16837737
555 코스트 0.16724068
556 코스트 0.16611157
557 코스트 0.16499034
558 코스트 0.16387656
559 코스트 0.16277035
560 코스트 0.16167164
561 코스트 0.16058035
562 코스트 0.15949635
563 코스트 0.15841968
564 코스트 0.15735027
565 코스트 0.15628806
566 코스트 0.15523288
567 코스트 0.15418515
568 코스트 0.15314424
569 코스트 0.15211037
570 코스트 0.15108365
571 코스트 0.15006374
572 코스트 0.14905079
573 코스트 0.14804466
574 코스트 0.14704527
575 코스트 0.14605267
576 코스트 0.1450666
577 코스트 0.1440873
578 코스트 0.14311473
579 코스트 0.14214852
580 코스트 0.14118902
581 코스트 0.14023593
582 코스트 0.13928933
583 코스트 0.138349
584 코스트 0.13741513
585 코스트 0.13648745
586 코스트 0.13556613
587 코스트 0.1346509
588 코스트 0.13374206
589 코스트 0.13283923
590 코스트 0.13194248
591 코스트 0.13105181
592 코스트 0.13016732
593 코스트 0.12928852
594 코스트 0.12841567
595 코스트 0.12754883


986 코스트 0.009026027
987 코스트 0.0089651
988 코스트 0.00890458
989 코스트 0.008844484
990 코스트 0.008784733
991 코스트 0.008725435
992 코스트 0.008666546
993 코스트 0.008608026
994 코스트 0.00854994
995 코스트 0.008492224
996 코스트 0.008434886
997 코스트 0.008377952
998 코스트 0.008321409
999 코스트 0.008265236
1000 코스트 0.008209424
1001 코스트 0.008153984
1002 코스트 0.008098979
1003 코스트 0.00804432
1004 코스트 0.007989997
1005 코스트 0.007936081
1006 코스트 0.007882502
1007 코스트 0.007829288
1008 코스트 0.007776442
1009 코스트 0.007723955
1010 코스트 0.007671802
1011 코스트 0.007620009
1012 코스트 0.007568574
1013 코스트 0.0075174877
1014 코스트 0.00746672
1015 코스트 0.007416334
1016 코스트 0.0073662684
1017 코스트 0.00731649
1018 코스트 0.007267135
1019 코스트 0.0072181076
1020 코스트 0.0071693673
1021 코스트 0.0071209697
1022 코스트 0.007072887
1023 코스트 0.007025119
1024 코스트 0.006977734
1025 코스트 0.0069306297
1026 코스트 0.006883846
1027 코스트 0.006837383
1028 코스트 0.006791198
1029 코스트 0.0067453557
1030 코스트 0.0066998177
1031 코스트 0.006654626
1032 코스트 0.006609687
1033 코스트 0.006565063
1034 

1451 코스트 0.00038693153
1452 코스트 0.00038432254
1453 코스트 0.00038172497
1454 코스트 0.00037914544
1455 코스트 0.0003765871
1456 코스트 0.00037404458
1457 코스트 0.00037152547
1458 코스트 0.00036901596
1459 코스트 0.0003665221
1460 코스트 0.00036404427
1461 코스트 0.0003615946
1462 코스트 0.000359148
1463 코스트 0.00035672274
1464 코스트 0.00035431742
1465 코스트 0.00035192282
1466 코스트 0.0003495544
1467 코스트 0.00034719022
1468 코스트 0.00034483866
1469 코스트 0.0003425166
1470 코스트 0.000340203
1471 코스트 0.00033791014
1472 코스트 0.00033563114
1473 코스트 0.0003333601
1474 코스트 0.0003311155
1475 코스트 0.00032887585
1476 코스트 0.00032665586
1477 코스트 0.00032445192
1478 코스트 0.0003222631
1479 코스트 0.0003200869
1480 코스트 0.00031792035
1481 코스트 0.00031579056
1482 코스트 0.00031364648
1483 코스트 0.00031153313
1484 코스트 0.00030943548
1485 코스트 0.00030734128
1486 코스트 0.00030526973
1487 코스트 0.00030320723
1488 코스트 0.0003011595
1489 코스트 0.0002991262
1490 코스트 0.0002971076
1491 코스트 0.00029509765
1492 코스트 0.0002931082
1493 코스트 0.00029113152
1494 코스트 0.00028916838
1495 

1894 코스트 1.9251882e-05
1895 코스트 1.9121248e-05
1896 코스트 1.8992632e-05
1897 코스트 1.8863586e-05
1898 코스트 1.8736213e-05
1899 코스트 1.8609597e-05
1900 코스트 1.8483504e-05
1901 코스트 1.835922e-05
1902 코스트 1.8236049e-05
1903 코스트 1.8111212e-05
1904 코스트 1.799143e-05
1905 코스트 1.7869572e-05
1906 코스트 1.7747287e-05
1907 코스트 1.7627615e-05
1908 코스트 1.7508439e-05
1909 코스트 1.7391325e-05
1910 코스트 1.727358e-05
1911 코스트 1.7158085e-05
1912 코스트 1.7040777e-05
1913 코스트 1.6926217e-05
1914 코스트 1.681092e-05
1915 코스트 1.6698235e-05
1916 코스트 1.6586084e-05
1917 코스트 1.647311e-05
1918 코스트 1.6361939e-05
1919 코스트 1.6250622e-05
1920 코스트 1.6140897e-05
1921 코스트 1.6032966e-05
1922 코스트 1.592538e-05
1923 코스트 1.5818496e-05
1924 코스트 1.5710926e-05
1925 코스트 1.5604468e-05
1926 코스트 1.5500027e-05
1927 코스트 1.5395894e-05
1928 코스트 1.5290805e-05
1929 코스트 1.5187354e-05
1930 코스트 1.5085304e-05
1931 코스트 1.4983324e-05
1932 코스트 1.4882605e-05
1933 코스트 1.478291e-05
1934 코스트 1.4680477e-05
1935 코스트 1.45827125e-05
1936 코스트 1.44847245e-05
1937 코스트 1.43867

# Keras 선형회귀
- 장점 : 사용하기 쉬움
- 단점 : 내부 구조 이해 어려움

In [28]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import Adam,Adagrad
import matplotlib.pyplot  as plt

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

import pandas as pd
plt.style.use(['seaborn-white'])

In [30]:
df = pd.read_csv('../data/cars.csv',index_col='Unnamed: 0') 
df.head(3)

speed  dist
1      4     2
2      4    10
3      7     4

In [31]:
x_data = df['speed'].values
y_data = df['dist'].values

In [32]:
#Dense - units : 출력 뉴런의수 input_dim : 뉴런의 수, activation : 활성화 함수
dense = Dense( units=1, input_dim=1 )   # w b 초기값
model = Sequential([dense])
model.compile(loss='mse',optimizer =Adam( 0.1)) # 런닝레이트
h = model.fit(x_data ,y_data, epochs=500)

Epoch 1/500
2/2 [==============================] - 0s 2ms/step - loss: 2371.0330
Epoch 2/500
2/2 [==============================] - 0s 981us/step - loss: 2052.5986
Epoch 3/500
2/2 [==============================] - 0s 998us/step - loss: 1793.0739
Epoch 4/500
2/2 [==============================] - 0s 998us/step - loss: 1544.2605
Epoch 5/500
2/2 [==============================] - 0s 998us/step - loss: 1318.7340
Epoch 6/500
2/2 [==============================] - 0s 1ms/step - loss: 1117.3907
Epoch 7/500
2/2 [==============================] - 0s 2ms/step - loss: 945.0386
Epoch 8/500
2/2 [==============================] - 0s 997us/step - loss: 791.9067
Epoch 9/500
2/2 [==============================] - 0s 2ms/step - loss: 667.2291
Epoch 10/500
2/2 [==============================] - 0s 997us/step - loss: 563.3746
Epoch 11/500
2/2 [==============================] - 0s 997us/step - loss: 478.8644
Epoch 12/500
2/2 [==============================] - 0s 997us/step - loss: 404.6799
Epoch 13/500
2/

2/2 [==============================] - 0s 2ms/step - loss: 260.0041
Epoch 101/500
2/2 [==============================] - 0s 2ms/step - loss: 259.9635
Epoch 102/500
2/2 [==============================] - 0s 997us/step - loss: 259.8734
Epoch 103/500
2/2 [==============================] - 0s 998us/step - loss: 259.7771
Epoch 104/500
2/2 [==============================] - 0s 2ms/step - loss: 259.6832
Epoch 105/500
2/2 [==============================] - 0s 997us/step - loss: 259.3267
Epoch 106/500
2/2 [==============================] - 0s 2ms/step - loss: 259.3807
Epoch 107/500
2/2 [==============================] - 0s 998us/step - loss: 258.8253
Epoch 108/500
2/2 [==============================] - 0s 2ms/step - loss: 258.5833
Epoch 109/500
2/2 [==============================] - 0s 998us/step - loss: 258.4377
Epoch 110/500
2/2 [==============================] - 0s 997us/step - loss: 259.6796
Epoch 111/500
2/2 [==============================] - 0s 997us/step - loss: 258.5956
Epoch 112/500
2/

2/2 [==============================] - 0s 2ms/step - loss: 247.8562
Epoch 199/500
2/2 [==============================] - 0s 997us/step - loss: 247.8240
Epoch 200/500
2/2 [==============================] - 0s 997us/step - loss: 247.8375
Epoch 201/500
2/2 [==============================] - 0s 997us/step - loss: 247.5466
Epoch 202/500
2/2 [==============================] - 0s 997us/step - loss: 247.0770
Epoch 203/500
2/2 [==============================] - 0s 2ms/step - loss: 247.0664
Epoch 204/500
2/2 [==============================] - 0s 997us/step - loss: 246.1515
Epoch 205/500
2/2 [==============================] - 0s 998us/step - loss: 246.4455
Epoch 206/500
2/2 [==============================] - 0s 996us/step - loss: 245.9700
Epoch 207/500
2/2 [==============================] - 0s 998us/step - loss: 245.8393
Epoch 208/500
2/2 [==============================] - 0s 999us/step - loss: 245.7006
Epoch 209/500
2/2 [==============================] - 0s 998us/step - loss: 245.6244
Epoch 210/

2/2 [==============================] - 0s 996us/step - loss: 237.4907
Epoch 297/500
2/2 [==============================] - 0s 997us/step - loss: 237.5064
Epoch 298/500
2/2 [==============================] - 0s 998us/step - loss: 237.8628
Epoch 299/500
2/2 [==============================] - 0s 2ms/step - loss: 237.8020
Epoch 300/500
2/2 [==============================] - 0s 2ms/step - loss: 237.4402
Epoch 301/500
2/2 [==============================] - 0s 511us/step - loss: 237.6015
Epoch 302/500
2/2 [==============================] - 0s 998us/step - loss: 237.3186
Epoch 303/500
2/2 [==============================] - 0s 988us/step - loss: 237.0706
Epoch 304/500
2/2 [==============================] - 0s 997us/step - loss: 237.1383
Epoch 305/500
2/2 [==============================] - 0s 997us/step - loss: 236.8961
Epoch 306/500
2/2 [==============================] - 0s 980us/step - loss: 236.8268
Epoch 307/500
2/2 [==============================] - 0s 997us/step - loss: 236.7951
Epoch 308/

2/2 [==============================] - 0s 997us/step - loss: 232.1099
Epoch 395/500
2/2 [==============================] - 0s 997us/step - loss: 232.0302
Epoch 396/500
2/2 [==============================] - 0s 998us/step - loss: 232.0374
Epoch 397/500
2/2 [==============================] - 0s 2ms/step - loss: 232.2844
Epoch 398/500
2/2 [==============================] - 0s 2ms/step - loss: 231.8427
Epoch 399/500
2/2 [==============================] - 0s 998us/step - loss: 232.8096
Epoch 400/500
2/2 [==============================] - 0s 2ms/step - loss: 231.9046
Epoch 401/500
2/2 [==============================] - 0s 998us/step - loss: 231.6500
Epoch 402/500
2/2 [==============================] - 0s 998us/step - loss: 231.5006
Epoch 403/500
2/2 [==============================] - 0s 2ms/step - loss: 231.7214
Epoch 404/500
2/2 [==============================] - 0s 997us/step - loss: 231.4195
Epoch 405/500
2/2 [==============================] - 0s 1ms/step - loss: 232.7280
Epoch 406/500
2/

2/2 [==============================] - 0s 997us/step - loss: 229.7363
Epoch 493/500
2/2 [==============================] - 0s 997us/step - loss: 229.8285
Epoch 494/500
2/2 [==============================] - 0s 997us/step - loss: 229.0195
Epoch 495/500
2/2 [==============================] - 0s 998us/step - loss: 228.9616
Epoch 496/500
2/2 [==============================] - 0s 998us/step - loss: 228.9529
Epoch 497/500
2/2 [==============================] - 0s 998us/step - loss: 228.9223
Epoch 498/500
2/2 [==============================] - 0s 998us/step - loss: 229.2861
Epoch 499/500
2/2 [==============================] - 0s 2ms/step - loss: 229.2651
Epoch 500/500
2/2 [==============================] - 0s 999us/step - loss: 229.6243


In [33]:
dense.get_weights() # w 와 b 둘다 구함. 3.0161774     -1.773635

[array([[3.6318755]], dtype=float32), array([-13.472002], dtype=float32)]

In [34]:
w,b = dense.get_weights()

In [35]:
model.predict([10]) # 속도가 10일때 제동거리

array([[22.846754]], dtype=float32)

In [36]:
model.predict([10,14]) # 속도가 10, 14일 때 제동거리

array([[22.846754],
       [37.374252]], dtype=float32)

# PyTorch 선형회귀

In [37]:
import torch
from torch.optim import Adam

In [38]:
x_data = torch.FloatTensor([1,2,3,4,5])
y_data = torch.FloatTensor([2,4,6,8,10])
w = torch.tensor(10.0, requires_grad=True)
b = torch.tensor(10.0, requires_grad=True)

경사 하강법 구현

In [39]:
optimizer = Adam( [w,b],lr=0.1)   
for i in range(2000):
    hx = w * x_data + b 
    cost = torch.mean( (hx -y_data)**2 )
    optimizer.zero_grad() # 기울기 초기화
    cost.backward() # cost값 미분
    optimizer.step() # w =  w-0.1 x w미분값, b= b-0.1 x b미분값
    print(i,'cost: ',cost.item())  #손실 계산

0 cost:  1284.0
1 cost:  1253.780029296875
2 cost:  1223.9296875
3 cost:  1194.455322265625
4 cost:  1165.363037109375
5 cost:  1136.658203125
6 cost:  1108.3463134765625
7 cost:  1080.4326171875
8 cost:  1052.921875
9 cost:  1025.818603515625
10 cost:  999.126953125
11 cost:  972.8507690429688
12 cost:  946.9935302734375
13 cost:  921.5579833984375
14 cost:  896.5476684570312
15 cost:  871.9641723632812
16 cost:  847.8098754882812
17 cost:  824.0861206054688
18 cost:  800.7943115234375
19 cost:  777.9353637695312
20 cost:  755.509765625
21 cost:  733.5175170898438
22 cost:  711.95849609375
23 cost:  690.83203125
24 cost:  670.1370849609375
25 cost:  649.8726806640625
26 cost:  630.0369262695312
27 cost:  610.6280517578125
28 cost:  591.643798828125
29 cost:  573.0817260742188
30 cost:  554.93896484375
31 cost:  537.2125244140625
32 cost:  519.8990478515625
33 cost:  502.9949645996094
34 cost:  486.49639892578125
35 cost:  470.3995056152344
36 cost:  454.699951171875
37 cost:  439.3933

334 cost:  0.25556015968322754
335 cost:  0.2548072040081024
336 cost:  0.2540552020072937
337 cost:  0.2533039450645447
338 cost:  0.2525539994239807
339 cost:  0.25180453062057495
340 cost:  0.2510563135147095
341 cost:  0.250308632850647
342 cost:  0.24956199526786804
343 cost:  0.24881640076637268
344 cost:  0.24807186424732208
345 cost:  0.24732784926891327
346 cost:  0.24658527970314026
347 cost:  0.24584336578845978
348 cost:  0.24510245025157928
349 cost:  0.24436251819133759
350 cost:  0.24362356960773468
351 cost:  0.2428855150938034
352 cost:  0.24214854836463928
353 cost:  0.24141252040863037
354 cost:  0.2406773567199707
355 cost:  0.23994334042072296
356 cost:  0.23921021819114685
357 cost:  0.23847806453704834
358 cost:  0.23774714767932892
359 cost:  0.23701715469360352
360 cost:  0.2362879067659378
361 cost:  0.23556002974510193
362 cost:  0.23483309149742126
363 cost:  0.2341070920228958
364 cost:  0.23338215053081512
365 cost:  0.2326582968235016
366 cost:  0.2319354

698 cost:  0.06277015060186386
699 cost:  0.0624731108546257
700 cost:  0.06217705458402634
701 cost:  0.061882175505161285
702 cost:  0.06158827617764473
703 cost:  0.0612955279648304
704 cost:  0.06100394204258919
705 cost:  0.06071343272924423
706 cost:  0.060423921793699265
707 cost:  0.06013554334640503
708 cost:  0.05984833836555481
709 cost:  0.0595620796084404
710 cost:  0.05927697941660881
711 cost:  0.05899300426244736
712 cost:  0.0587100088596344
713 cost:  0.05842813104391098
714 cost:  0.05814731866121292
715 cost:  0.05786754563450813
716 cost:  0.05758892744779587
717 cost:  0.0573112890124321
718 cost:  0.05703473836183548
719 cost:  0.056759290397167206
720 cost:  0.05648490786552429
721 cost:  0.056211572140455246
722 cost:  0.05593917891383171
723 cost:  0.055667977780103683
724 cost:  0.055397748947143555
725 cost:  0.055128563195466995
726 cost:  0.05486036464571953
727 cost:  0.05459330230951309
728 cost:  0.05432724207639694
729 cost:  0.05406224727630615
730 co

1059 cost:  0.008230118080973625
1060 cost:  0.008176496252417564
1061 cost:  0.008123201318085194
1062 cost:  0.008070165291428566
1063 cost:  0.00801747478544712
1064 cost:  0.007965060882270336
1065 cost:  0.00791300181299448
1066 cost:  0.0078611820936203
1067 cost:  0.007809700910001993
1068 cost:  0.007758490741252899
1069 cost:  0.007707579992711544
1070 cost:  0.0076569728553295135
1071 cost:  0.007606693543493748
1072 cost:  0.007556651718914509
1073 cost:  0.007506920490413904
1074 cost:  0.007457452826201916
1075 cost:  0.007408312521874905
1076 cost:  0.007359418086707592
1077 cost:  0.007310828659683466
1078 cost:  0.007262502796947956
1079 cost:  0.007214493118226528
1080 cost:  0.0071667456068098545
1081 cost:  0.007119280286133289
1082 cost:  0.00707207340747118
1083 cost:  0.007025178521871567
1084 cost:  0.0069785392843186855
1085 cost:  0.00693216547369957
1086 cost:  0.006886056624352932
1087 cost:  0.006840258836746216
1088 cost:  0.00679469620808959
1089 cost:  0.

1420 cost:  0.0005483445711433887
1421 cost:  0.0005436929641291499
1422 cost:  0.0005390752921812236
1423 cost:  0.0005345023237168789
1424 cost:  0.0005299561307765543
1425 cost:  0.0005254541174508631
1426 cost:  0.0005209749797359109
1427 cost:  0.0005165438633412123
1428 cost:  0.0005121352733112872
1429 cost:  0.0005077706300653517
1430 cost:  0.0005034311325289309
1431 cost:  0.0004991400055587292
1432 cost:  0.0004948659334331751
1433 cost:  0.0004906397662125528
1434 cost:  0.0004864380171056837
1435 cost:  0.00048227878869511187
1436 cost:  0.0004781408642884344
1437 cost:  0.00047404092038050294
1438 cost:  0.00046997368917800486
1439 cost:  0.00046594388550147414
1440 cost:  0.00046194237074814737
1441 cost:  0.00045796571066603065
1442 cost:  0.0004540210939012468
1443 cost:  0.0004501123330555856
1444 cost:  0.0004462360520847142
1445 cost:  0.00044238846749067307
1446 cost:  0.0004385801439639181
1447 cost:  0.0004347949870862067
1448 cost:  0.0004310374497435987
1449 co

1770 cost:  1.9096838514087722e-05
1771 cost:  1.8892485968535766e-05
1772 cost:  1.868950857897289e-05
1773 cost:  1.849158070399426e-05
1774 cost:  1.8292677850695327e-05
1775 cost:  1.809673813113477e-05
1776 cost:  1.7903203115565702e-05
1777 cost:  1.7712576664052904e-05
1778 cost:  1.7521908375783823e-05
1779 cost:  1.7332800780422986e-05
1780 cost:  1.7147349353763275e-05
1781 cost:  1.696434264886193e-05
1782 cost:  1.6780622900114395e-05
1783 cost:  1.6602429241174832e-05
1784 cost:  1.642312781768851e-05
1785 cost:  1.624442302272655e-05
1786 cost:  1.607114973012358e-05
1787 cost:  1.5898296624072827e-05
1788 cost:  1.5725378034403548e-05
1789 cost:  1.5556406651739962e-05
1790 cost:  1.538835022074636e-05
1791 cost:  1.5221085050143301e-05
1792 cost:  1.505780983279692e-05
1793 cost:  1.4893828847561963e-05
1794 cost:  1.4734035175933968e-05
1795 cost:  1.4574620763596613e-05
1796 cost:  1.4414506040338892e-05
1797 cost:  1.4258036571845878e-05
1798 cost:  1.410384538758080

In [40]:
w.item()

1.99922776222229

# 다중 선형 회귀
```

  
  
  
```

- 내가 다중이랑 다항이랑 헷갈리는데
- 다항회귀는 독립변수의 차수를 높임. (x^2)
- 다중회귀는 다중의 독립변수가 있는 형태 (x1, x2)

In [41]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## x1 : 공부할시간 + x2 : 출석일수 y : 점수

In [55]:
x1_data = [1,0,3,4,5]  #공부한시간
x2_data = [0,1,2,3,4] #출석일수
y_data = [1,2,3,4,5] #점수

In [56]:
x1 = tf.constant( x1_data , tf.float32)
x2 = tf.constant( x2_data , tf.float32)
y = tf.constant( y_data , tf.float32)

In [57]:
w1 = tf.Variable(tf.random.uniform([1])) # x1 의 가중치
w2 = tf.Variable(tf.random.uniform([1])) # x2 의 가중치
b = tf.Variable(tf.random.uniform([1])) 

In [58]:
# cost 구하는 함수
def compute_loss():
    hx = w1*x1 + w2*x2 + b
    cost = tf.reduce_mean( (hx - y)**2 )
    return cost

In [60]:

optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize(compute_loss, var_list=[w1,w2,b] ) # 미분
    print(i,'cost: ',compute_loss().numpy())

TypeError: 'float' object is not iterable