In [1]:
import tensorflow as tf
import numpy as np

# Scalar data

- 단 하나의 값만을 저장할 수 있는 데이터 타입

In [ ]:
s1 = 10 
s2 = 'abc'
s3 = 3.14

# Vector data
- 스칼라 데이터 모음

In [ ]:
v = [10,20,30]

# matrix data

- 벡터 데이터 모음

In [ ]:
m = [  [10,20,30] , 
     [40,50,60]  ]   # 2 x 3  ==> 2행 3열

# 3d tensor

- 메트릭스 데이터 모음


In [2]:
# 2x2x3 ==> 2면 2행 3열   2메트릭스 2벡터 3스칼라
d3 = [ 
      [  [10,20,30] , 
         [40,50,60]  ], 
    
      [  [10,20,30] , 
         [40,50,60]  ] 
     ] 

# 4d tensor


In [5]:
# 2 x 2 x 2 x3      2 3dtensor 2매트릭스 2벡터 3스칼라
d4 =[ [  [  [10,20,30] , [40,50,60]  ], 
       [  [10,20,30] , [40,50,60]  ] ] 
     ,[  [  [10,20,30] , [40,50,60]  ], 
       [  [10,20,30] , [40,50,60]  ] ] ]

# tensor data node 정의
```
1. constant   - > 읽기 전용 ( 값 고정)
2. Variable   - > 읽기 쓰기 
```

## Constant

In [8]:
# scalar      shape=()     numpy = value
s1 = 10
c1  = tf.constant( s1 )
c1,c1.numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=10>, 10)

In [10]:
# vector   shape=(3,)   numpy=array([])
v1 = [10,20,30]
t1  = tf.constant(v1)
t1, t1.numpy() , type(t1)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>,
 array([10, 20, 30]),
 tensorflow.python.framework.ops.EagerTensor)

In [12]:
# matrix    shape=(2, 3)    numpy=array([ [ ] ])
m1 = [[10,20,30], [40,50,60] ]
t2 = tf.constant( m1 )
t2, t2.numpy()

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [40, 50, 60]])>,
 array([[10, 20, 30],
        [40, 50, 60]]))

## 연산  element wise
- 요소별 연산 

In [14]:
a = tf.constant( 3 )  # scalar data         shape=()
b = tf.constant( [1,2,3] ) # vector data   shape=(3,)

In [18]:
c = tf.multiply(a , b)  # * 연산      shape=(3,)   
c, c.numpy()

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>,
 array([3, 6, 9]))

In [19]:
d = tf.add(a,b) #  + 연산        shape=(3,)
d, d.numpy()

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>,
 array([4, 5, 6]))

In [21]:
e = tf.add(c, b)   #               shape=(3,)      c+b
e, e.numpy()

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12])>,
 array([ 4,  8, 12]))

## broad casting
- 두 행렬 A, B 중 크기가 작은 행렬을 크기가 큰 행렬과 모양(shape)이 맞게끔 늘려주는 것을 의미


In [22]:
f = tf.constant([1,2,3])
g = tf.constant([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]  ])
h = f+g  # tf.add( f , g )

In [25]:
h.numpy()

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [27]:
# i = tf.constant([1,2,3])
i = tf.constant( [  [1],       # 3행 1열 매트릭스
                    [2],
                    [3]] )
j = tf.constant([ [1,2,3],
                  [4,5,6],
                  [7,8,9] ] )

k = i * j   # tf.constant( f, g )

In [28]:
k.numpy()

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [30]:
# # shape error
# l = tf.constant( [1,2 ])     
# m = tf.constant(  [ [1,2,3],
#                     [4,5,6],
#                     [7,8,9]] )
# n = l - j    # tf.subtrack(l , m )    

## 행렬의 곱
- tf.matmul( A , B )

In [32]:
#   2x2     2x2
o = tf.constant([  [1,2],
                   [3,4]] )
p = tf.constant( [ [5,6],
                    [7,8] ] )

q = tf.multiply( o ,p )    # o * p 

r = tf.matmul( o, p )     # 행렬의 곱    
# ((1*5)  + (2*6) , (1*6) + (2*8) ) 
# ((3*5)  + (4*6) , (3*6) + (5*8) ) 

In [33]:
q,r

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 12],
        [21, 32]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[19, 22],
        [43, 50]])>)

## 많이 사용하는 operation
```
- tf.square()       제곱    s**2
- tf.reduce_mean()  평균
```

In [34]:
s = [1,2,3,]
t = tf.square( s )

In [37]:
t.numpy()

array([1, 4, 9])

In [39]:
u = tf.reduce_mean( s )
u.numpy()

2

## Variable

```
변수명 =  tf.Variable(10)

변수명.assign( 20 )    기존의 값을 10에서 20으로 변경
변수명.assign_add( 3 ) 기존의 값에 3을 더함
변수명.assign_sub( 3 ) 기존의 값에 3을 뺌

```

In [41]:
v = tf.Variable( 10 )
v                       # 10

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [46]:
# v = 20   X
v.assign(3)
v                     #  3 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [47]:
v.assign_add( 3 )
v                   #  3 + 3  = 6

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

In [48]:
v.assign_sub( 3 )  #   6  -  3 =  3
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>