In [4]:
import tensorflow as tf
import numpy as np
import math
import matplotlib.pyplot as plt 
from  tensorflow.keras.optimizers import Adam
plt.style.use('ggplot')

In [2]:
#공부한시간, 출석일수
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y_data = np.array( [[0],[0],[0],[1],[1],[1]])

In [3]:
x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

In [12]:
# xavier,  he ( 최적의 초기화 알고리즘 )
initX = tf.initializers.GlorotUniform()
w = tf.Variable(initX(shape=[2,1]))
b = tf.Variable(initX(shape=[1]))

############ 기존 함수들 ############ 

```
def cost( x,y,w):
#     hx = w*x
    z = w*x
    hx = tf.nn.sigmoid( z ) # 0~1사이값
    cost = -tf.reduce_mean( y * tf.math.log(hx) + (1 - y) * (tf.math.log(1 - hx)) )
# #     cost = tf.reduce_mean( (hx-y)**2)
# #     cost = -tf.reduce_mean( y * tf.math.log(hx) + (1 - y) * (tf.math.log(1 - hx)) )
#     cost_i = -( y * tf.math.log(hx) + (1 - y) * (tf.math.log(1 - hx)) )
# #     cost_i = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=z)
#     cost = tf.reduce_mean( cost_i )
    return cost.numpy()
```


```
def compute_loss():
    z = tf.matmul( x, w) + b
#     hx = tf.nn.sigmoid( z ) # 0~1 사이값
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits( labels=y , logits= z)
    cost = tf.reduce_mean( cost_i )
#     hx = tf.matmul( x, w) + b
#     cost = tf.reduce_mean( (hx-y)**2)
    return cost
```

In [13]:
def compute_loss():
#     hx = tf.matmul(x,w) + b
    z = tf.matmul(x,w) + b
    hx = tf.nn.sigmoid(z)  # (뉴럴 네트워크)
    

#     cost = tf.reduce_mean((hx-y)**2)

    # 라벨 = 정답(y)   logits= 시그모이드 (z)
    # 미분이 안되기 때문에 로그 씌워서 
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=z)
    cost = tf.reduce_mean(cost_i)
    return cost
    

In [24]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b] )
    print(i, 'cost:', compute_loss().numpy() )

0 cost: 0.0060990346
1 cost: 0.0053072907
2 cost: 0.0055624917
3 cost: 0.005298048
4 cost: 0.0048561655
5 cost: 0.0046589263
6 cost: 0.004608978
7 cost: 0.004507402
8 cost: 0.00430422
9 cost: 0.0040700426
10 cost: 0.003889647
11 cost: 0.0037882908
12 cost: 0.003714664
13 cost: 0.0036032656
14 cost: 0.003449357
15 cost: 0.0032953636
16 cost: 0.0031735164
17 cost: 0.0030828046
18 cost: 0.003002855
19 cost: 0.0029155686
20 cost: 0.0028162648
21 cost: 0.002712373
22 cost: 0.0026154441
23 cost: 0.0025328097
24 cost: 0.0024633117
25 cost: 0.0023992264
26 cost: 0.002332775
27 cost: 0.0022618321
28 cost: 0.0021900886
29 cost: 0.002122773
30 cost: 0.00206257
31 cost: 0.002008621
32 cost: 0.0019580785
33 cost: 0.0019082781
34 cost: 0.0018580874
35 cost: 0.0018080459
36 cost: 0.0017596175
37 cost: 0.0017141491
38 cost: 0.0016721274
39 cost: 0.0016330132
40 cost: 0.0015956857
41 cost: 0.0015591355
42 cost: 0.0015229695
43 cost: 0.0014874609
44 cost: 0.0014531948
45 cost: 0.0014206407
46 cost: 0.00

373 cost: 0.000106783176
374 cost: 0.00010637322
375 cost: 0.000105965795
376 cost: 0.00010556084
377 cost: 0.00010515845
378 cost: 0.00010475848
379 cost: 0.000104360945
380 cost: 0.000103965904
381 cost: 0.000103573264
382 cost: 0.000103182996
383 cost: 0.00010279506
384 cost: 0.00010240943
385 cost: 0.00010202618
386 cost: 0.00010164519
387 cost: 0.00010126652
388 cost: 0.000100890145
389 cost: 0.000100515936
390 cost: 0.00010014405
391 cost: 9.977431e-05
392 cost: 9.940678e-05
393 cost: 9.904142e-05
394 cost: 9.867816e-05
395 cost: 9.83171e-05
396 cost: 9.795814e-05
397 cost: 9.760124e-05
398 cost: 9.7246484e-05
399 cost: 9.689379e-05
400 cost: 9.654317e-05
401 cost: 9.619462e-05
402 cost: 9.584805e-05
403 cost: 9.550346e-05
404 cost: 9.5160874e-05
405 cost: 9.482028e-05
406 cost: 9.448166e-05
407 cost: 9.4144925e-05
408 cost: 9.381015e-05
409 cost: 9.347723e-05
410 cost: 9.3146205e-05
411 cost: 9.281713e-05
412 cost: 9.24899e-05
413 cost: 9.216449e-05
414 cost: 9.1840884e-05
415 c

738 cost: 3.8466736e-05
739 cost: 3.8385635e-05
740 cost: 3.8304788e-05
741 cost: 3.8224214e-05
742 cost: 3.814391e-05
743 cost: 3.806386e-05
744 cost: 3.798407e-05
745 cost: 3.790454e-05
746 cost: 3.7825277e-05
747 cost: 3.7746275e-05
748 cost: 3.7667523e-05
749 cost: 3.7589023e-05
750 cost: 3.7510792e-05
751 cost: 3.7432797e-05
752 cost: 3.735507e-05
753 cost: 3.7277558e-05
754 cost: 3.7200298e-05
755 cost: 3.7123293e-05
756 cost: 3.704656e-05
757 cost: 3.697005e-05
758 cost: 3.68938e-05
759 cost: 3.681777e-05
760 cost: 3.674201e-05
761 cost: 3.6666508e-05
762 cost: 3.659124e-05
763 cost: 3.65162e-05
764 cost: 3.6441397e-05
765 cost: 3.6366826e-05
766 cost: 3.6292487e-05
767 cost: 3.6218396e-05
768 cost: 3.6144545e-05
769 cost: 3.6070942e-05
770 cost: 3.5997542e-05
771 cost: 3.5924375e-05
772 cost: 3.5851455e-05
773 cost: 3.5778754e-05
774 cost: 3.5706293e-05
775 cost: 3.5634035e-05
776 cost: 3.5562025e-05
777 cost: 3.5490226e-05
778 cost: 3.541869e-05
779 cost: 3.5347362e-05
780 cos

In [19]:
def hxfn(xdata):
    xd = tf.constant(xdata,tf.float32)
    z = tf.matmul(xd,w ) + b
    hx = tf.nn.sigmoid(z)
#     return z.numpy(),hx.numpy()
    return (hx.numpy() > 0.5) + 0    # 1 일경우 합, 0일경우 불합.

In [25]:
hxfn([[4,5]])

array([[1]])

In [28]:
hxfn([[2,3], [5,6] ]  )   # 2x2 matmul 2x1 =  2x1

array([[0],
       [1]])

In [30]:
# 전체 데이터
x_data ,x_data.shape

(array([[1, 3],
        [2, 2],
        [3, 1],
        [4, 6],
        [5, 5],
        [6, 4]]),
 (6, 2))

In [31]:
hxfn(x_data)

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [33]:
# 실제값 
y_data,y_data.shape

(array([[0],
        [0],
        [0],
        [1],
        [1],
        [1]]),
 (6, 1))

In [34]:
# 정확도 예측
pred = hxfn(x_data)

pred == y_data

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [36]:
(pred == y_data).mean()

1.0

In [38]:
def accFn(xdata):
    pred = hxfn(xdata)
    return (pred==y_data).mean()
accFn(x_data)

1.0