In [2]:
import tensorflow as tf
import numpy as np
import math
import matplotlib.pyplot as plt 
from  tensorflow.keras.optimizers import Adam
plt.style.use('ggplot')
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [5]:
#공부한시간, 출석일수
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y_data = np.array( [[0],[0],[0],[1],[1],[1]])

In [7]:
dense = Dense(units= 1, input_dim = 2 ,activation='sigmoid') # w : 2x1  b :1 
model = Sequential([dense])

# 로지스틱에서는 cost가 mse가 아님 
# model.compile(loss = 'mse')

model.compile(loss = 'binary_crossentropy',optimizer=Adam(0.1),metrics=['acc']  )
h = model.fit(x_data,y_data,epochs=1000)



Epoch 1/1000
1/1 [==============================] - 0s 233ms/step - loss: 1.8927 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.4332 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 1.0492 - acc: 0.3333
Epoch 4/1000
1/1 [==============================] - 0s 998us/step - loss: 0.7954 - acc: 0.3333
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7016 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 997us/step - loss: 0.7207 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7778 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 997us/step - loss: 0.8303 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 998us/step - loss: 0.8630 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.8733 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 2

1/1 [==============================] - 0s 998us/step - loss: 0.1574 - acc: 1.0000
Epoch 88/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1550 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1527 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1505 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1483 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1461 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1440 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1419 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1399 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1379 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 997us/st

1/1 [==============================] - 0s 2ms/step - loss: 0.0600 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0595 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0590 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0585 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0580 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 984us/step - loss: 0.0575 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0570 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0565 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0561 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0556 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] -

1/1 [==============================] - 0s 998us/step - loss: 0.0329 - acc: 1.0000
Epoch 258/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0328 - acc: 1.0000
Epoch 259/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0326 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0324 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0322 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0320 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0318 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0316 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0315 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0313 - acc: 1.0000
Epoch 267/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.0213 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0213 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0212 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0211 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0210 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0209 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0208 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0207 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0206 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0205 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 998us/step - loss: 0.0152 - acc: 1.0000
Epoch 428/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0151 - acc: 1.0000
Epoch 429/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0151 - acc: 1.0000
Epoch 430/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0150 - acc: 1.0000
Epoch 431/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0150 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0149 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0148 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0148 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0147 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0147 - acc: 1.0000
Epoch 437/1000
1/1 [=============================

1/1 [==============================] - 0s 998us/step - loss: 0.0114 - acc: 1.0000
Epoch 513/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0114 - acc: 1.0000
Epoch 514/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0114 - acc: 1.0000
Epoch 515/1000
1/1 [==============================] - 0s 978us/step - loss: 0.0113 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0113 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0113 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0112 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0112 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0112 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0111 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] -

1/1 [==============================] - 0s 998us/step - loss: 0.0090 - acc: 1.0000
Epoch 598/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0090 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0089 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0089 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0089 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0089 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0088 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0088 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0088 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0088 - acc: 1.0000
Epoch 607/1000
1/1 [==============================] -

1/1 [==============================] - 0s 998us/step - loss: 0.0073 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0073 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0072 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0072 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0072 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0072 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0072 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0072 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0071 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0071 - acc: 1.0000
Epoch 692/1000
1/1 [=============================

1/1 [==============================] - 0s 998us/step - loss: 0.0060 - acc: 1.0000
Epoch 768/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0060 - acc: 1.0000
Epoch 769/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0060 - acc: 1.0000
Epoch 770/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0060 - acc: 1.0000
Epoch 771/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0060 - acc: 1.0000
Epoch 772/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0060 - acc: 1.0000
Epoch 773/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0059 - acc: 1.0000
Epoch 774/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0059 - acc: 1.0000
Epoch 775/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0059 - acc: 1.0000
Epoch 776/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0059 - acc: 1.0000
Epoch 777/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.0051 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0051 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0051 - acc: 1.0000
Epoch 855/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0050 - acc: 1.0000
Epoch 856/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 857/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 858/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 859/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0050 - acc: 1.0000
Epoch 860/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 861/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0050 - acc: 1.0000
Epoch 862/1000
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 998us/step - loss: 0.0043 - acc: 1.0000
Epoch 938/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0043 - acc: 1.0000
Epoch 939/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0043 - acc: 1.0000
Epoch 940/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0043 - acc: 1.0000
Epoch 941/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0043 - acc: 1.0000
Epoch 942/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0043 - acc: 1.0000
Epoch 943/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0043 - acc: 1.0000
Epoch 944/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0043 - acc: 1.0000
Epoch 945/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0043 - acc: 1.0000
Epoch 946/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0043 - acc: 1.0000
Epoch 947/1000
1/1 [==============================] - 0

In [8]:
w,b = dense.get_weights()
w,b

(array([[1.8738748],
        [1.8773813]], dtype=float32),
 array([-12.720841], dtype=float32))

In [9]:
# 5시간 6일 공부했을때
model.predict([[5,6]])

array([[0.99963415]], dtype=float32)

In [10]:
(model.predict([[5,6]])>0.5) +0

array([[1]])

In [11]:
model.predict(x_data)

array([[0.00540605],
       [0.00538722],
       [0.00536832],
       [0.99762154],
       [0.9976133 ],
       [0.99760497]], dtype=float32)

In [16]:
p = (model.predict(x_data)>0.5) + 0
# 정확도
p == y_data

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [12]:
model.evaluate(x_data,y_data)

1/1 [==============================] - 0s 85ms/step - loss: 0.0039 - acc: 1.0000


[0.003895687637850642, 1.0]

# pima indian 케라스 첫번째 행 예측

In [65]:
import pandas as pd
df = pd.read_csv('ddata/pima-indians-diabetes.data.csv',encoding='euc-kr')
df.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1

In [66]:
for c in ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']:
    idx = np.where(df[c]==0)[0]
    df.loc[idx,c] = df[c].mean()

In [67]:
df.describe()

Pregnancies     Glucose  BloodPressure  ...  DiabetesPedigreeFunction         Age     Outcome
count   768.000000  768.000000     768.000000  ...                768.000000  768.000000  768.000000
mean      3.845052  121.681605      72.254807  ...                  0.471876   33.240885    0.348958
std       3.369578   30.436016      12.115932  ...                  0.331329   11.760232    0.476951
min       0.000000   44.000000      24.000000  ...                  0.078000   21.000000    0.000000
25%       1.000000   99.750000      64.000000  ...                  0.243750   24.000000    0.000000
50%       3.000000  117.000000      72.000000  ...                  0.372500   29.000000    0.000000
75%       6.000000  140.250000      80.000000  ...                  0.626250   41.000000    1.000000
max      17.000000  199.000000     122.000000  ...                  2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [68]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,[-1]].values

In [69]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_data)

x = tf.constant(x_scaled, tf.float32)
y = tf.constant(y_data, tf.float32)

In [26]:
x_data.shape , y_data.shape

((768, 8), (768, 1))

In [28]:
x.shape, y.shape

(TensorShape([768, 8]), TensorShape([768, 1]))

In [70]:
dense = Dense( units=1, input_dim=8 ,activation="sigmoid") # w:2x1, b:1
model = Sequential( [dense])
model.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_scaled,y, epochs=1000)

Epoch 1/1000
24/24 [==============================] - 0s 607us/step - loss: 0.5741 - acc: 0.6966
Epoch 2/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4764 - acc: 0.7826
Epoch 3/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4804 - acc: 0.7734
Epoch 4/1000
24/24 [==============================] - 0s 521us/step - loss: 0.4780 - acc: 0.7708
Epoch 5/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4763 - acc: 0.7695
Epoch 6/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4784 - acc: 0.7695
Epoch 7/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4805 - acc: 0.7643
Epoch 8/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4768 - acc: 0.7734
Epoch 9/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4866 - acc: 0.7656
Epoch 10/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4846 - acc: 0.7747
Epoch 11/1000
24/24 [========

24/24 [==============================] - 0s 477us/step - loss: 0.4835 - acc: 0.7617
Epoch 85/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4835 - acc: 0.7773
Epoch 86/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4900 - acc: 0.7760
Epoch 87/1000
24/24 [==============================] - 0s 480us/step - loss: 0.4847 - acc: 0.7539
Epoch 88/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4773 - acc: 0.7682
Epoch 89/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4754 - acc: 0.7552
Epoch 90/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4814 - acc: 0.7617
Epoch 91/1000
24/24 [==============================] - 0s 437us/step - loss: 0.4804 - acc: 0.7643
Epoch 92/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4797 - acc: 0.7695
Epoch 93/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4831 - acc: 0.7760
Epoch 94/1000
24/24 [=============

24/24 [==============================] - 0s 520us/step - loss: 0.4784 - acc: 0.7669
Epoch 168/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4832 - acc: 0.7721
Epoch 169/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4785 - acc: 0.7695
Epoch 170/1000
24/24 [==============================] - 0s 476us/step - loss: 0.4763 - acc: 0.7669
Epoch 171/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4861 - acc: 0.7656
Epoch 172/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4800 - acc: 0.7682
Epoch 173/1000
24/24 [==============================] - 0s 564us/step - loss: 0.4834 - acc: 0.7734
Epoch 174/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4944 - acc: 0.7565
Epoch 175/1000
24/24 [==============================] - 0s 483us/step - loss: 0.4768 - acc: 0.7708
Epoch 176/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4860 - acc: 0.7682
Epoch 177/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4818 - acc: 0.7708
Epoch 250/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4800 - acc: 0.7747
Epoch 251/1000
24/24 [==============================] - 0s 528us/step - loss: 0.4860 - acc: 0.7656
Epoch 252/1000
24/24 [==============================] - 0s 519us/step - loss: 0.4795 - acc: 0.7552
Epoch 253/1000
24/24 [==============================] - 0s 564us/step - loss: 0.4771 - acc: 0.7695
Epoch 254/1000
24/24 [==============================] - 0s 438us/step - loss: 0.4832 - acc: 0.7682
Epoch 255/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4847 - acc: 0.7617
Epoch 256/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4865 - acc: 0.7656
Epoch 257/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4829 - acc: 0.7565
Epoch 258/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4838 - acc: 0.7669
Epoch 259/1000
24/24 [===

24/24 [==============================] - 0s 478us/step - loss: 0.4795 - acc: 0.7682
Epoch 332/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4808 - acc: 0.7734
Epoch 333/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4874 - acc: 0.7578
Epoch 334/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4895 - acc: 0.7643
Epoch 335/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4839 - acc: 0.7656
Epoch 336/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4780 - acc: 0.7682
Epoch 337/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4777 - acc: 0.7747
Epoch 338/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4794 - acc: 0.7682
Epoch 339/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4769 - acc: 0.7682
Epoch 340/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4784 - acc: 0.7695
Epoch 341/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4845 - acc: 0.7695
Epoch 414/1000
24/24 [==============================] - 0s 485us/step - loss: 0.4730 - acc: 0.7760
Epoch 415/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4803 - acc: 0.7656
Epoch 416/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4749 - acc: 0.7799
Epoch 417/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4762 - acc: 0.7656
Epoch 418/1000
24/24 [==============================] - 0s 523us/step - loss: 0.4815 - acc: 0.7721
Epoch 419/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4797 - acc: 0.7747
Epoch 420/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4776 - acc: 0.7708
Epoch 421/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4845 - acc: 0.7708
Epoch 422/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4854 - acc: 0.7617
Epoch 423/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4794 - acc: 0.7682
Epoch 496/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4783 - acc: 0.7721
Epoch 497/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4862 - acc: 0.7604
Epoch 498/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4791 - acc: 0.7695
Epoch 499/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4994 - acc: 0.7500
Epoch 500/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4919 - acc: 0.7565
Epoch 501/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4909 - acc: 0.7630
Epoch 502/1000
24/24 [==============================] - 0s 480us/step - loss: 0.4837 - acc: 0.7617
Epoch 503/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4775 - acc: 0.7760
Epoch 504/1000
24/24 [==============================] - 0s 522us/step - loss: 0.4782 - acc: 0.7760
Epoch 505/1000
24/24 [===

24/24 [==============================] - 0s 481us/step - loss: 0.4817 - acc: 0.7669
Epoch 578/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4856 - acc: 0.7669
Epoch 579/1000
24/24 [==============================] - 0s 478us/step - loss: 0.4816 - acc: 0.7747
Epoch 580/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4902 - acc: 0.7526
Epoch 581/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4874 - acc: 0.7747
Epoch 582/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4757 - acc: 0.7760
Epoch 583/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4803 - acc: 0.7656
Epoch 584/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4776 - acc: 0.7721
Epoch 585/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4787 - acc: 0.7682
Epoch 586/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4770 - acc: 0.7708
Epoch 587/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4807 - acc: 0.7643
Epoch 660/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4757 - acc: 0.7721
Epoch 661/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4858 - acc: 0.7734
Epoch 662/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4741 - acc: 0.7682
Epoch 663/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4763 - acc: 0.7708
Epoch 664/1000
24/24 [==============================] - 0s 480us/step - loss: 0.4753 - acc: 0.7812
Epoch 665/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4805 - acc: 0.7656
Epoch 666/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4729 - acc: 0.7682
Epoch 667/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4766 - acc: 0.7656
Epoch 668/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4872 - acc: 0.7708
Epoch 669/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4775 - acc: 0.7721
Epoch 742/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4784 - acc: 0.7721
Epoch 743/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4847 - acc: 0.7695
Epoch 744/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4730 - acc: 0.7786
Epoch 745/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4726 - acc: 0.7812
Epoch 746/1000
24/24 [==============================] - 0s 480us/step - loss: 0.4808 - acc: 0.7812
Epoch 747/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4780 - acc: 0.7721
Epoch 748/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4770 - acc: 0.7760
Epoch 749/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4823 - acc: 0.7656
Epoch 750/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4782 - acc: 0.7708
Epoch 751/1000
24/24 [===

24/24 [==============================] - 0s 564us/step - loss: 0.4855 - acc: 0.7669
Epoch 824/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4823 - acc: 0.7669
Epoch 825/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4783 - acc: 0.7747
Epoch 826/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4836 - acc: 0.7773
Epoch 827/1000
24/24 [==============================] - 0s 478us/step - loss: 0.4833 - acc: 0.7669
Epoch 828/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4954 - acc: 0.7617
Epoch 829/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4818 - acc: 0.7786
Epoch 830/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4771 - acc: 0.7786
Epoch 831/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4735 - acc: 0.7669
Epoch 832/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4820 - acc: 0.7656
Epoch 833/1000
24/24 [===

24/24 [==============================] - 0s 434us/step - loss: 0.4780 - acc: 0.7643
Epoch 906/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4740 - acc: 0.7734
Epoch 907/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4814 - acc: 0.7708
Epoch 908/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4877 - acc: 0.7552
Epoch 909/1000
24/24 [==============================] - 0s 482us/step - loss: 0.4785 - acc: 0.7617
Epoch 910/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4917 - acc: 0.7604
Epoch 911/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4823 - acc: 0.7708
Epoch 912/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4804 - acc: 0.7669
Epoch 913/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4869 - acc: 0.7643
Epoch 914/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4897 - acc: 0.7734
Epoch 915/1000
24/24 [===

24/24 [==============================] - 0s 434us/step - loss: 0.4823 - acc: 0.7708
Epoch 988/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4804 - acc: 0.7669
Epoch 989/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4806 - acc: 0.7747
Epoch 990/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4798 - acc: 0.7669
Epoch 991/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4791 - acc: 0.7565
Epoch 992/1000
24/24 [==============================] - 0s 476us/step - loss: 0.4738 - acc: 0.7773
Epoch 993/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4915 - acc: 0.7578
Epoch 994/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4776 - acc: 0.7708
Epoch 995/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4771 - acc: 0.7578
Epoch 996/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4827 - acc: 0.7474
Epoch 997/1000
24/24 [===

In [71]:
w, b = dense.get_weights()
w

array([[ 0.33028746],
       [ 1.2396499 ],
       [-0.19251691],
       [ 0.11773425],
       [-0.08524528],
       [ 0.90621066],
       [ 0.42080632],
       [ 0.07264315]], dtype=float32)

In [80]:
model.predict(x_data[0].reshape(1,-1))

array([[1.]], dtype=float32)

In [73]:
model.predict([[  6.        , 148.        ,  72.        ,  35.        ,
        79.79947917,  33.6       ,   0.627     ,  50.        ]])

array([[1.]], dtype=float32)

# 파이프라인

In [48]:
import pandas as pd
df = pd.read_csv('ddata/pima-indians-diabetes.data.csv',encoding='euc-kr')
for c in ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']:
    idx = np.where(df[c]==0)[0]
    df.loc[idx,c] = df[c].mean()
df.head(3)

Pregnancies  Glucose  BloodPressure  SkinThickness    Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6    148.0           72.0      35.000000  79.799479  33.6                     0.627   50        1
1            1     85.0           66.0      29.000000  79.799479  26.6                     0.351   31        0
2            8    183.0           64.0      20.536458  79.799479  23.3                     0.672   32        1

In [51]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.pipeline import make_pipeline

In [50]:
x_data = df.iloc[:,:-1].values
y_data = df.iloc[:,[-1]].values

In [52]:
def createModel():
    dense = Dense( units=1, input_dim=8 ,activation="sigmoid") # w:2x1, b:1
    model = Sequential( [dense])
    model.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )

    return model
#h = model.fit( x_data, y_data, epochs=1000)

In [54]:
kcf = KerasClassifier(build_fn=createModel, epochs=1000 ,verbose=1)
pmodel = make_pipeline(MinMaxScaler(),kcf)
pmodel.fit(x_data,y_data)

Epoch 1/1000
 1/24 [>.............................] - ETA: 3s - loss: 0.6622 - acc: 0.6875

<ipython-input-54-25b74214e89e>:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  kcf = KerasClassifier(build_fn=createModel, epochs=1000 ,verbose=1)


24/24 [==============================] - 0s 520us/step - loss: 0.6496 - acc: 0.6602
Epoch 2/1000
24/24 [==============================] - 0s 477us/step - loss: 0.5762 - acc: 0.6992
Epoch 3/1000
24/24 [==============================] - 0s 477us/step - loss: 0.5487 - acc: 0.7201
Epoch 4/1000
24/24 [==============================] - 0s 520us/step - loss: 0.5214 - acc: 0.7539
Epoch 5/1000
24/24 [==============================] - 0s 520us/step - loss: 0.5070 - acc: 0.7396
Epoch 6/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4960 - acc: 0.7565
Epoch 7/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4952 - acc: 0.7643
Epoch 8/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4818 - acc: 0.7682
Epoch 9/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4846 - acc: 0.7643
Epoch 10/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4885 - acc: 0.7552
Epoch 11/1000
24/24 [=====================

24/24 [==============================] - 0s 520us/step - loss: 0.4714 - acc: 0.7643
Epoch 85/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4668 - acc: 0.7812
Epoch 86/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4663 - acc: 0.7773
Epoch 87/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4661 - acc: 0.7786
Epoch 88/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4647 - acc: 0.7721
Epoch 89/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4696 - acc: 0.7812
Epoch 90/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4650 - acc: 0.7773
Epoch 91/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4666 - acc: 0.7721
Epoch 92/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4663 - acc: 0.7786
Epoch 93/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4693 - acc: 0.7773
Epoch 94/1000
24/24 [=============

24/24 [==============================] - 0s 477us/step - loss: 0.4713 - acc: 0.7708
Epoch 168/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4684 - acc: 0.7747
Epoch 169/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4760 - acc: 0.7695
Epoch 170/1000
24/24 [==============================] - 0s 476us/step - loss: 0.4740 - acc: 0.7721
Epoch 171/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4775 - acc: 0.7708
Epoch 172/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4705 - acc: 0.7695
Epoch 173/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4658 - acc: 0.7747
Epoch 174/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4676 - acc: 0.7773
Epoch 175/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4696 - acc: 0.7760
Epoch 176/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4782 - acc: 0.7682
Epoch 177/1000
24/24 [===

24/24 [==============================] - 0s 520us/step - loss: 0.4674 - acc: 0.7695
Epoch 250/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4694 - acc: 0.7721
Epoch 251/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4695 - acc: 0.7773
Epoch 252/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4775 - acc: 0.7773
Epoch 253/1000
24/24 [==============================] - 0s 478us/step - loss: 0.4673 - acc: 0.7773
Epoch 254/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4722 - acc: 0.7682
Epoch 255/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4657 - acc: 0.7695
Epoch 256/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4688 - acc: 0.7682
Epoch 257/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4729 - acc: 0.7708
Epoch 258/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4658 - acc: 0.7812
Epoch 259/1000
24/24 [===

24/24 [==============================] - 0s 520us/step - loss: 0.4650 - acc: 0.7760
Epoch 332/1000
24/24 [==============================] - 0s 564us/step - loss: 0.4764 - acc: 0.7630
Epoch 333/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4682 - acc: 0.7773
Epoch 334/1000
24/24 [==============================] - 0s 521us/step - loss: 0.4669 - acc: 0.7734
Epoch 335/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4660 - acc: 0.7773
Epoch 336/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4663 - acc: 0.7760
Epoch 337/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4762 - acc: 0.7630
Epoch 338/1000
24/24 [==============================] - 0s 591us/step - loss: 0.4731 - acc: 0.7708
Epoch 339/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4655 - acc: 0.7773
Epoch 340/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4663 - acc: 0.7708
Epoch 341/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4671 - acc: 0.7760
Epoch 414/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4670 - acc: 0.7786
Epoch 415/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4659 - acc: 0.7773
Epoch 416/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4669 - acc: 0.7734
Epoch 417/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4684 - acc: 0.7760
Epoch 418/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4681 - acc: 0.7760
Epoch 419/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4671 - acc: 0.7826
Epoch 420/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4698 - acc: 0.7734
Epoch 421/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4658 - acc: 0.7721
Epoch 422/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4660 - acc: 0.7760
Epoch 423/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4753 - acc: 0.7708
Epoch 496/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4686 - acc: 0.7812
Epoch 497/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4690 - acc: 0.7682
Epoch 498/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4678 - acc: 0.7826
Epoch 499/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4741 - acc: 0.7721
Epoch 500/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4809 - acc: 0.7721
Epoch 501/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4785 - acc: 0.7682
Epoch 502/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4688 - acc: 0.7812
Epoch 503/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4764 - acc: 0.7656
Epoch 504/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4691 - acc: 0.7708
Epoch 505/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4710 - acc: 0.7721
Epoch 578/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4663 - acc: 0.7747
Epoch 579/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4705 - acc: 0.7630
Epoch 580/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4726 - acc: 0.7643
Epoch 581/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4647 - acc: 0.7826
Epoch 582/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4811 - acc: 0.7604
Epoch 583/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4791 - acc: 0.7747
Epoch 584/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4704 - acc: 0.7734
Epoch 585/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4632 - acc: 0.7786
Epoch 586/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4690 - acc: 0.7786
Epoch 587/1000
24/24 [===

24/24 [==============================] - 0s 477us/step - loss: 0.4819 - acc: 0.7734
Epoch 660/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4709 - acc: 0.7578
Epoch 661/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4712 - acc: 0.7695
Epoch 662/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4657 - acc: 0.7799
Epoch 663/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4692 - acc: 0.7799
Epoch 664/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4671 - acc: 0.7695
Epoch 665/1000
24/24 [==============================] - 0s 520us/step - loss: 0.4703 - acc: 0.7734
Epoch 666/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4699 - acc: 0.7760
Epoch 667/1000
24/24 [==============================] - 0s 476us/step - loss: 0.4728 - acc: 0.7682
Epoch 668/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4655 - acc: 0.7839
Epoch 669/1000
24/24 [===

24/24 [==============================] - 0s 434us/step - loss: 0.4663 - acc: 0.7799
Epoch 742/1000
24/24 [==============================] - 0s 476us/step - loss: 0.4655 - acc: 0.7734
Epoch 743/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4689 - acc: 0.7617
Epoch 744/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4666 - acc: 0.7747
Epoch 745/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4689 - acc: 0.7865
Epoch 746/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4693 - acc: 0.7747
Epoch 747/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4695 - acc: 0.7721
Epoch 748/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4690 - acc: 0.7734
Epoch 749/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4738 - acc: 0.7721
Epoch 750/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4721 - acc: 0.7682
Epoch 751/1000
24/24 [===

24/24 [==============================] - 0s 434us/step - loss: 0.4755 - acc: 0.7760
Epoch 824/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4739 - acc: 0.7721
Epoch 825/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4710 - acc: 0.7682
Epoch 826/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4691 - acc: 0.7773
Epoch 827/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4668 - acc: 0.7812
Epoch 828/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4668 - acc: 0.7734
Epoch 829/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4665 - acc: 0.7786
Epoch 830/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4664 - acc: 0.7760
Epoch 831/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4649 - acc: 0.7747
Epoch 832/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4694 - acc: 0.7734
Epoch 833/1000
24/24 [===

24/24 [==============================] - 0s 520us/step - loss: 0.4671 - acc: 0.7786
Epoch 906/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4677 - acc: 0.7760
Epoch 907/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4698 - acc: 0.7760
Epoch 908/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4717 - acc: 0.7786
Epoch 909/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4705 - acc: 0.7786
Epoch 910/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4663 - acc: 0.7734
Epoch 911/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4685 - acc: 0.7812
Epoch 912/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4733 - acc: 0.7682
Epoch 913/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4737 - acc: 0.7721
Epoch 914/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4652 - acc: 0.7786
Epoch 915/1000
24/24 [===

24/24 [==============================] - 0s 520us/step - loss: 0.4713 - acc: 0.7695
Epoch 988/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4665 - acc: 0.7721
Epoch 989/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4671 - acc: 0.7695
Epoch 990/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4722 - acc: 0.7773
Epoch 991/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4654 - acc: 0.7799
Epoch 992/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4733 - acc: 0.7695
Epoch 993/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4661 - acc: 0.7695
Epoch 994/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4771 - acc: 0.7826
Epoch 995/1000
24/24 [==============================] - 0s 434us/step - loss: 0.4687 - acc: 0.7786
Epoch 996/1000
24/24 [==============================] - 0s 477us/step - loss: 0.4690 - acc: 0.7799
Epoch 997/1000
24/24 [===

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('kerasclassifier',
                 <keras.wrappers.scikit_learn.KerasClassifier object at 0x000001BB685D3C10>)])

In [55]:
pmodel.predict(x_data)

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [57]:
x_data[0]

array([  6.        , 148.        ,  72.        ,  35.        ,
        79.79947917,  33.6       ,   0.627     ,  50.        ])

In [59]:
pmodel.predict([[  6.        , 148.        ,  72.        ,  35.        ,
        79.79947917,  33.6       ,   0.627     ,  50.        ]])

array([[1]], dtype=int64)

In [64]:
pmodel.predict_proba([[  6.        , 148.        ,  72.        ,  35.        ,
        79.79947917,  33.6       ,   0.627     ,  50.        ]])

array([[0.20402408, 0.7959759 ]], dtype=float32)