In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

import math
import matplotlib.pyplot as plt 

plt.style.use('ggplot')

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('tdata/softmax.txt', sep =' ' , header = None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [45]:
x_data = df.iloc[:,0:2]
y_data = df.iloc[:,2:]

In [19]:
x_data.shape , y_data.shape

((8, 2), (8, 3))

In [46]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [47]:
initX =tf.initializers.GlorotUniform()
w = tf.Variable( initX( shape=[2,3] ) ) #[특성데이터의 갯수, 라벳의갯수]
b = tf.Variable( initX( shape=[3] ) ) #라벨의 갯수

In [48]:
def compute_loss():
    z = tf.matmul( x, w) + b
#     hx = tf.nn.softmax( z )
    cost_i = tf.nn.softmax_cross_entropy_with_logits( labels=y, logits=z )
    cost = tf.reduce_mean( cost_i)
    return cost

In [49]:
optimizer = Adam( 0.1 )
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b] )
    print( i, 'cost:', compute_loss().numpy() )

0 cost: 1.2453353
1 cost: 1.2967131
2 cost: 1.4539394
3 cost: 1.43964
4 cost: 1.3094814
5 cost: 1.1463856
6 cost: 1.0515492
7 cost: 1.0764238
8 cost: 1.1284382
9 cost: 1.1118093
10 cost: 1.030742
11 cost: 0.94631195
12 cost: 0.9100919
13 cost: 0.91409075
14 cost: 0.91896886
15 cost: 0.9047181
16 cost: 0.8718606
17 cost: 0.8305091
18 cost: 0.79726255
19 cost: 0.78289515
20 cost: 0.7795081
21 cost: 0.7714975
22 cost: 0.75471526
23 cost: 0.73722947
24 cost: 0.7249297
25 cost: 0.7138978
26 cost: 0.6998236
27 cost: 0.6867269
28 cost: 0.6806625
29 cost: 0.6791959
30 cost: 0.67425466
31 cost: 0.66326886
32 cost: 0.6511919
33 cost: 0.64384335
34 cost: 0.6420208
35 cost: 0.64137626
36 cost: 0.6374899
37 cost: 0.63028777
38 cost: 0.62303853
39 cost: 0.6181632
40 cost: 0.6152079
41 cost: 0.6123911
42 cost: 0.6088253
43 cost: 0.60494006
44 cost: 0.6012438
45 cost: 0.5974336
46 cost: 0.59322196
47 cost: 0.58929324
48 cost: 0.58643514
49 cost: 0.5841567
50 cost: 0.5812017
51 cost: 0.5772639
52 cost:

441 cost: 0.1937117
442 cost: 0.19333006
443 cost: 0.19294941
444 cost: 0.19256987
445 cost: 0.19219139
446 cost: 0.1918138
447 cost: 0.19143736
448 cost: 0.19106205
449 cost: 0.19068766
450 cost: 0.19031426
451 cost: 0.18994194
452 cost: 0.18957072
453 cost: 0.18920037
454 cost: 0.18883105
455 cost: 0.1884628
456 cost: 0.18809551
457 cost: 0.18772918
458 cost: 0.1873639
459 cost: 0.1869996
460 cost: 0.18663633
461 cost: 0.18627392
462 cost: 0.18591255
463 cost: 0.18555216
464 cost: 0.18519278
465 cost: 0.1848343
466 cost: 0.18447685
467 cost: 0.18412031
468 cost: 0.18376467
469 cost: 0.18341002
470 cost: 0.18305627
471 cost: 0.18270363
472 cost: 0.18235171
473 cost: 0.18200086
474 cost: 0.18165097
475 cost: 0.1813019
476 cost: 0.18095385
477 cost: 0.1806067
478 cost: 0.18026042
479 cost: 0.1799151
480 cost: 0.1795706
481 cost: 0.17922708
482 cost: 0.17888445
483 cost: 0.1785427
484 cost: 0.17820193
485 cost: 0.17786196
486 cost: 0.17752285
487 cost: 0.17718469
488 cost: 0.1768475
489 

857 cost: 0.09434809
858 cost: 0.09420404
859 cost: 0.09406026
860 cost: 0.09391697
861 cost: 0.09377383
862 cost: 0.093630955
863 cost: 0.09348843
864 cost: 0.09334618
865 cost: 0.09320426
866 cost: 0.093062535
867 cost: 0.09292126
868 cost: 0.09278019
869 cost: 0.09263942
870 cost: 0.09249891
871 cost: 0.09235874
872 cost: 0.09221885
873 cost: 0.092079185
874 cost: 0.09193985
875 cost: 0.09180088
876 cost: 0.091662094
877 cost: 0.09152363
878 cost: 0.09138541
879 cost: 0.09124756
880 cost: 0.09110992
881 cost: 0.09097251
882 cost: 0.09083551
883 cost: 0.09069871
884 cost: 0.09056227
885 cost: 0.09042605
886 cost: 0.09029014
887 cost: 0.09015447
888 cost: 0.09001907
889 cost: 0.08988393
890 cost: 0.08974913
891 cost: 0.0896146
892 cost: 0.089480355
893 cost: 0.089346364
894 cost: 0.089212656
895 cost: 0.089079134
896 cost: 0.088945955
897 cost: 0.0888131
898 cost: 0.088680424
899 cost: 0.08854803
900 cost: 0.08841596
901 cost: 0.08828412
902 cost: 0.08815254
903 cost: 0.08802125
904 c

In [50]:
w.numpy()

array([[ 0.3185976 ,  0.21334033, -0.03309755],
       [ 3.3485675 , -1.0044868 , -5.7673373 ]], dtype=float32)

# 넘파이 가장 큰값의 인덱스 -> argmax()

In [29]:
arr = np.array([ [1,2,3],
                 [4,5,6] ] )

## axis = 0 인경우   ( 행 기준)

In [32]:
arr.argmax()  #   =행 기준

5

## axis = 1 인경우   ( 열 기준)

In [34]:
arr.argmax(axis=1)  #   =열 기준

array([2, 2], dtype=int64)

In [57]:
arr = np.array( [[1,2,3],[4,5,6]] )
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

# softmax 가장 큰값

In [43]:
# 예측값
def hxfn(xdata):
    xd = tf.constant(x_data, tf.float32)
    z = tf.matmul(xd, w ) + b
    hx = tf.nn.softmax(z)
#     return z.numpy(), hx.numpy()
    return hx.numpy()

In [44]:
hxfn( [[5,6]]  )

array([[9.0934037e-16, 1.9972887e-07, 9.9999976e-01],
       [6.7842641e-12, 2.2721661e-05, 9.9997723e-01],
       [1.5947856e-04, 1.5267771e-01, 8.4716284e-01],
       [6.8172932e-02, 8.9755720e-01, 3.4269955e-02],
       [8.3613120e-02, 8.9543480e-01, 2.0952037e-02],
       [4.9079463e-02, 8.8081908e-01, 7.0101559e-02],
       [8.3276039e-01, 1.6718346e-01, 5.6109508e-05],
       [9.9694818e-01, 3.0518919e-03, 9.0033083e-09]], dtype=float32)

In [54]:
hxfn( [[1,1],[5,6]]  )

array([[1.00907346e-16, 7.61979848e-08, 9.99999881e-01],
       [1.30509893e-12, 1.14141885e-05, 9.99988556e-01],
       [9.34224154e-05, 1.35281235e-01, 8.64625335e-01],
       [6.02442920e-02, 9.09428954e-01, 3.03267818e-02],
       [7.41884634e-02, 9.07328725e-01, 1.84828248e-02],
       [4.32024188e-02, 8.94332707e-01, 6.24649785e-02],
       [8.51153493e-01, 1.48813456e-01, 3.31278789e-05],
       [9.97979105e-01, 2.02085660e-03, 3.00317593e-09]], dtype=float32)

In [61]:
pred  = hxfn(x_data).argmax(axis=1)
pred

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [64]:
r = y_data.values.argmax(axis=1)
r

array([2, 2, 2, 1, 1, 1, 0, 0], dtype=int64)

In [65]:
(pred == r ).mean()

1.0

# 케라스 버전

In [66]:
df = pd.read_csv('tdata/softmax.txt', sep =' ' , header = None)
df

0  1  2  3  4
0  2  1  0  0  1
1  3  2  0  0  1
2  3  4  0  0  1
3  5  5  0  1  0
4  7  5  0  1  0
5  2  5  0  1  0
6  6  6  1  0  0
7  7  7  1  0  0

In [68]:
# x값 2  , y깂 3
x_data = df.iloc[:,0:2].values
y_data = df.iloc[:,2:].values

In [71]:
x_data.shape, y_data.shape

((8, 2), (8, 3))

In [72]:
dense = Dense( units=3, input_dim=2 ,activation="softmax")
model = Sequential( [dense])
model.compile( loss="categorical_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_data,y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 191ms/step - loss: 2.3689 - acc: 0.2500
Epoch 2/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.9261 - acc: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 1.6675 - acc: 0.3750
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.3535 - acc: 0.3750
Epoch 5/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.1429 - acc: 0.3750
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2709 - acc: 0.3750
Epoch 7/1000
1/1 [==============================] - 0s 0s/step - loss: 1.4139 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.3465 - acc: 0.3750
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2022 - acc: 0.3750
Epoch 10/1000
1/1 [==============================] - 0s 997us/step - loss: 1.1014 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 2ms/step

1/1 [==============================] - 0s 2ms/step - loss: 0.5243 - acc: 0.8750
Epoch 88/1000
1/1 [==============================] - 0s 997us/step - loss: 0.5221 - acc: 0.8750
Epoch 89/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5199 - acc: 0.8750
Epoch 90/1000
1/1 [==============================] - 0s 998us/step - loss: 0.5177 - acc: 0.8750
Epoch 91/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5156 - acc: 0.8750
Epoch 92/1000
1/1 [==============================] - 0s 998us/step - loss: 0.5135 - acc: 0.8750
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5114 - acc: 0.8750
Epoch 94/1000
1/1 [==============================] - 0s 999us/step - loss: 0.5093 - acc: 0.8750
Epoch 95/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.5073 - acc: 0.8750
Epoch 96/1000
1/1 [==============================] - 0s 998us/step - loss: 0.5052 - acc: 0.8750
Epoch 97/1000
1/1 [==============================] - 0s 998us/st

1/1 [==============================] - 0s 2ms/step - loss: 0.3889 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3877 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3866 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3854 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3843 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3831 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3820 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3808 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3797 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3786 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] -

1/1 [==============================] - 0s 1ms/step - loss: 0.3095 - acc: 1.0000
Epoch 258/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3088 - acc: 1.0000
Epoch 259/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3080 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3073 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3066 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3058 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3051 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3044 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3037 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3029 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 979us/step - loss: 0.2563 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2558 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2553 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2548 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2542 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2537 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 996us/step - loss: 0.2532 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2527 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2522 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 996us/step - loss: 0.2517 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] -

1/1 [==============================] - 0s 999us/step - loss: 0.2171 - acc: 1.0000
Epoch 428/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2167 - acc: 1.0000
Epoch 429/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2163 - acc: 1.0000
Epoch 430/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2159 - acc: 1.0000
Epoch 431/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2155 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2151 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2147 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2143 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2139 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2135 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 998us/step - loss: 0.1862 - acc: 1.0000
Epoch 513/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1859 - acc: 1.0000
Epoch 514/1000
1/1 [==============================] - 0s 996us/step - loss: 0.1856 - acc: 1.0000
Epoch 515/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1853 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1849 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1846 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1843 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1840 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1836 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1833 - acc: 1.0000
Epoch 522/1000
1/1 [=============================

1/1 [==============================] - 0s 998us/step - loss: 0.1611 - acc: 1.0000
Epoch 598/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1608 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 988us/step - loss: 0.1606 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1603 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1600 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1598 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1595 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1592 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1590 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1587 - acc: 1.0000
Epoch 607/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.1403 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1400 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1398 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1396 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1394 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1391 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1389 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1387 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 995us/step - loss: 0.1385 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1383 - acc: 1.0000
Epoch 692/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.1228 - acc: 1.0000
Epoch 768/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1226 - acc: 1.0000
Epoch 769/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1224 - acc: 1.0000
Epoch 770/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1223 - acc: 1.0000
Epoch 771/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1221 - acc: 1.0000
Epoch 772/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1219 - acc: 1.0000
Epoch 773/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1217 - acc: 1.0000
Epoch 774/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1215 - acc: 1.0000
Epoch 775/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1213 - acc: 1.0000
Epoch 776/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1211 - acc: 1.0000
Epoch 777/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.1081 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1080 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1078 - acc: 1.0000
Epoch 855/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1076 - acc: 1.0000
Epoch 856/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1075 - acc: 1.0000
Epoch 857/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1073 - acc: 1.0000
Epoch 858/1000
1/1 [==============================] - 0s 998us/step - loss: 0.1072 - acc: 1.0000
Epoch 859/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1070 - acc: 1.0000
Epoch 860/1000
1/1 [==============================] - 0s 997us/step - loss: 0.1069 - acc: 1.0000
Epoch 861/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1067 - acc: 1.0000
Epoch 862/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 998us/step - loss: 0.0957 - acc: 1.0000
Epoch 938/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0955 - acc: 1.0000
Epoch 939/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0954 - acc: 1.0000
Epoch 940/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0953 - acc: 1.0000
Epoch 941/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0951 - acc: 1.0000
Epoch 942/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0950 - acc: 1.0000
Epoch 943/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0949 - acc: 1.0000
Epoch 944/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0947 - acc: 1.0000
Epoch 945/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0946 - acc: 1.0000
Epoch 946/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0945 - acc: 1.0000
Epoch 947/1000
1/1 [==============================] -

In [73]:
w, b = dense.get_weights()
w

array([[ 0.45296746,  0.3505242 ,  0.09935073],
       [ 4.390314  ,  0.18342873, -4.124764  ]], dtype=float32)

In [74]:
b

array([-23.786135  ,   0.39771515,  20.004827  ], dtype=float32)

In [75]:
model.predict( x_data )

array([[9.7056857e-16, 3.7491216e-07, 9.9999964e-01],
       [6.8965996e-12, 3.5811441e-05, 9.9996424e-01],
       [1.4332776e-04, 1.6506805e-01, 8.3478862e-01],
       [6.4310268e-02, 8.9867902e-01, 3.7010740e-02],
       [7.8932911e-02, 8.9867181e-01, 2.2395356e-02],
       [4.6158724e-02, 8.7710106e-01, 7.6740138e-02],
       [8.4180105e-01, 1.5813078e-01, 6.8175934e-05],
       [9.9748117e-01, 2.5188038e-03, 1.1368472e-08]], dtype=float32)

In [78]:
grade=['A','B','C']

In [76]:
# 5시간 공부 6일 출석의 0 , 1  ,2  확률 
model.predict([[5,6]])

array([[8.2765877e-01, 1.7224574e-01, 9.5465562e-05]], dtype=float32)

In [77]:
model.predict([[5,6]]).argmax(axis=1)

array([0], dtype=int64)

In [79]:
grade[int(model.predict([[5,6]]).argmax(axis=1)) ]

'A'

In [80]:
def resultFn(dt) :
    n = int(model.predict([[5,6]]).argmax(axis=1))
    grade=['A','B','C']
    return grade[n]

In [81]:
resultFn([[5,6]])

'A'