In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import Adam,Adagrad
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot  as plt
import pandas as pd 
plt.style.use(['seaborn-white'])

In [3]:
x_data = np.array( [[0,0],
                    [0,1],
                    [1,0],
                    [1,1]] )

y_data = np.array( [[0],
                    [1],
                    [1],
                    [0] ] )

In [10]:
dense1 = Dense( units=100, input_dim=2 ,activation="sigmoid") # 2x100, b:100
dense2 = Dense( units=1, input_dim=100 ,activation="sigmoid") # 100x1 b: 1
model = Sequential( [dense1, dense2])
model.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 232ms/step - loss: 0.7011 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 998us/step - loss: 2.7109 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0423 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2794 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 997us/step - loss: 1.7035 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.3668 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.8267 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 998us/step - loss: 0.7484 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0292 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 995us/step - loss: 1.1376 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 2ms

1/1 [==============================] - 0s 998us/step - loss: 0.0260 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0256 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0251 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0247 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0243 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0240 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0236 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0232 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0229 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0225 - acc: 1.0000
Epoch 182/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.0056 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0056 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0056 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0055 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0055 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0055 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0054 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0054 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0054 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0053 - acc: 1.0000
Epoch 352/1000
1/1 [=============================

1/1 [==============================] - 0s 997us/step - loss: 0.0037 - acc: 1.0000
Epoch 428/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0037 - acc: 1.0000
Epoch 429/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0037 - acc: 1.0000
Epoch 430/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0037 - acc: 1.0000
Epoch 431/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0037 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0037 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0036 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0036 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0036 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0036 - acc: 1.0000
Epoch 437/1000
1/1 [==============================]

1/1 [==============================] - 0s 998us/step - loss: 0.0021 - acc: 1.0000
Epoch 598/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0021 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0020 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0020 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0020 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0020 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0020 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0020 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0020 - acc: 1.0000
Epoch 607/1000
1/1 [==============================]

1/1 [==============================] - 0s 2ms/step - loss: 0.0016 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0016 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0016 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0016 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0016 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0016 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0016 - acc: 1.0000
Epoch 692/1000
1/1 [==============================]

1/1 [==============================] - 0s 999us/step - loss: 0.0011 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0011 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 855/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 856/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011 - acc: 1.0000
Epoch 857/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011 - acc: 1.0000
Epoch 858/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 859/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011 - acc: 1.0000
Epoch 860/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0011 - acc: 1.0000
Epoch 861/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 862/1000
1/1 [==============================] -

Epoch 936/1000
1/1 [==============================] - 0s 997us/step - loss: 9.4577e-04 - acc: 1.0000
Epoch 937/1000
1/1 [==============================] - 0s 997us/step - loss: 9.4401e-04 - acc: 1.0000
Epoch 938/1000
1/1 [==============================] - 0s 997us/step - loss: 9.4226e-04 - acc: 1.0000
Epoch 939/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.4051e-04 - acc: 1.0000
Epoch 940/1000
1/1 [==============================] - 0s 997us/step - loss: 9.3877e-04 - acc: 1.0000
Epoch 941/1000
1/1 [==============================] - 0s 998us/step - loss: 9.3703e-04 - acc: 1.0000
Epoch 942/1000
1/1 [==============================] - 0s 997us/step - loss: 9.3529e-04 - acc: 1.0000
Epoch 943/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.3357e-04 - acc: 1.0000
Epoch 944/1000
1/1 [==============================] - 0s 997us/step - loss: 9.3184e-04 - acc: 1.0000
Epoch 945/1000
1/1 [==============================] - 0s 998us/step - loss: 9.3013e-04 - acc: 1

In [11]:
(model.predict(x_data)>0.5)+0

array([[0],
       [1],
       [1],
       [0]])

In [12]:
w,b = dense1.get_weights()  # 2행 100열
w,b

(array([[-1.7973720e+00, -1.8293883e+00, -1.9450517e+00, -2.5982955e+00,
         -7.4164371e+00,  1.3939713e+00, -8.4312391e+00, -9.3502550e+00,
         -3.3906541e+00, -1.5397311e+00, -5.3899531e+00, -2.3513975e+00,
         -1.6010090e+00, -2.1897793e+00, -7.8431792e+00, -1.9777843e+00,
          1.2686112e+00, -3.3237207e+00, -1.6615591e+00, -4.0442920e+00,
         -5.6379390e+00, -6.2035861e+00, -7.4272861e+00, -7.7856455e+00,
         -2.6233141e+00,  1.0736920e+00, -2.6083598e+00, -2.2457705e+00,
         -1.5035222e+00, -5.5051398e+00, -5.7201405e+00, -1.9037479e+00,
         -6.6888113e+00, -1.7557738e+00, -1.7815921e+00, -1.6217360e+00,
         -4.9789805e+00, -1.6550829e+00, -1.2221503e+00, -1.3675798e+00,
         -1.6067038e+00, -1.7591040e+00,  1.1954292e+00, -6.7472668e+00,
         -3.4137464e+00, -3.7056966e+00, -2.0020647e+00, -1.3140647e+00,
         -1.3739042e+00, -1.6559902e+00, -3.2504859e+00, -8.1887197e+00,
         -1.4365693e+00, -1.7346789e+00,  1.4935360

In [13]:
w,b = dense2.get_weights()  # 2행 100열
w,b

(array([[ 7.1061492e-02],
        [ 9.9680901e-02],
        [-1.0309569e-01],
        [-2.1771583e-01],
        [ 1.8015255e+00],
        [ 9.0283930e-01],
        [-2.3750968e+00],
        [ 2.8015490e+00],
        [ 5.4890871e-01],
        [-2.8665806e-03],
        [-9.5077831e-01],
        [-1.9057244e-01],
        [-3.6081742e-02],
        [ 1.6227412e-01],
        [-1.8945473e+00],
        [-9.2611909e-02],
        [ 1.1110458e+00],
        [ 2.9525858e-01],
        [ 5.9870526e-02],
        [-5.7723898e-01],
        [ 8.1627512e-01],
        [-1.0917155e+00],
        [-1.6401545e+00],
        [-1.8749068e+00],
        [ 1.9431925e-01],
        [ 1.0407333e+00],
        [-2.4635831e-01],
        [-1.6186434e-01],
        [ 5.2958481e-02],
        [-9.9734855e-01],
        [-1.0777422e+00],
        [-7.9460040e-02],
        [ 1.3644950e+00],
        [ 4.9255434e-02],
        [ 7.5984269e-02],
        [ 5.2199230e-02],
        [-7.1692294e-01],
        [ 7.8899115e-02],
        [-7.

In [18]:
modelNN = Sequential()
modelNN.add( Dense( units=64, input_dim=2 ,activation="sigmoid") )
modelNN.add( Dense( units=32, activation="sigmoid") )
modelNN.add( Dense( units=1,  activation="sigmoid") )
modelNN.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = modelNN.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 368ms/step - loss: 0.7541 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.3588 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 997us/step - loss: 1.0834 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7950 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 996us/step - loss: 0.6965 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 998us/step - loss: 0.7082 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7335 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7376 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7398 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7397 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 996us

1/1 [==============================] - 0s 2ms/step - loss: 0.0315 - acc: 1.0000
Epoch 173/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0311 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0308 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0305 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0301 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0298 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0295 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0292 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0289 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0286 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] - 0

1/1 [==============================] - 0s 997us/step - loss: 0.0098 - acc: 1.0000
Epoch 343/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0097 - acc: 1.0000
Epoch 344/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0097 - acc: 1.0000
Epoch 345/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0096 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0096 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0095 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0095 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0094 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0094 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0094 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] -

1/1 [==============================] - 0s 3ms/step - loss: 0.0051 - acc: 1.0000
Epoch 513/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0051 - acc: 1.0000
Epoch 514/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0051 - acc: 1.0000
Epoch 515/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0051 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0050 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0050 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0050 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] - 0s 2ms/st

1/1 [==============================] - 0s 2ms/step - loss: 0.0032 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0032 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0032 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0032 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0032 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0032 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0032 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0032 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0032 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0031 - acc: 1.0000
Epoch 692/1000
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 997us/step - loss: 0.0022 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 855/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0022 - acc: 1.0000
Epoch 856/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0022 - acc: 1.0000
Epoch 857/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 858/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 859/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 860/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 861/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0022 - acc: 1.0000
Epoch 862/1000
1/1 [==============================] - 0s 

In [19]:
modelNN.layers

In [25]:
w,b = modelNN.layers[0].get_weights()
w,b

(array([[-2.3363523 , -2.0908732 , -1.0364397 , -2.0763392 , -1.13408   ,
         -1.9190024 , -1.2595366 , -1.6646781 , -2.1926572 , -2.1259413 ,
          3.0462785 , -2.155261  , -0.2725096 , -2.2300117 , -1.6970253 ,
         -2.5943148 , -2.4629216 ,  0.5819875 , -1.9949954 ,  2.0523257 ,
          1.7826446 , -2.390421  , -1.2972074 , -1.8764966 , -2.3368583 ,
         -1.741642  , -2.1953778 , -2.2984533 , -2.0043771 , -2.992892  ,
         -2.3769379 , -1.143847  , -1.8375582 , -1.4355863 , -1.3984576 ,
         -1.6771133 , -2.0207703 , -1.0011151 , -1.6372174 , -1.7240108 ,
          2.6142828 , -2.6452718 , -2.1562102 ,  2.5683892 , -1.3623253 ,
         -1.9079412 , -2.264648  ,  3.0141084 ,  3.0626738 , -0.98358285,
          3.7380095 , -2.2454622 ,  3.2743697 , -2.2450323 , -2.701793  ,
         -1.3639942 , -0.6010279 , -2.9304833 , -2.6676722 ,  2.1698396 ,
         -2.1115398 , -2.216217  , -1.7791576 , -1.8457714 ],
        [-1.7035199 , -1.6793439 , -2.3938866 , -1

In [1]:

(modelNN.predict(x_data)>0.5)

NameError: name 'modelNN' is not defined