In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier



import numpy as np
import tensorflow as tf
from tensorflow.keras.optimizers import Adam,Adagrad
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot  as plt
import pandas as pd 
plt.style.use(['seaborn-white'])

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 80 from C header, got 88 from PyObject


In [4]:
x_data = np.array( [[0,0],
                    [0,1],
                    [1,0],
                    [1,1]] )

y_data = np.array( [[0],
                    [1],
                    [1],
                    [0] ] )

In [5]:
model_logi = LogisticRegression(max_iter=1000, verbose=1)
model_logi.fit(x_data,y_data)

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [6]:
model_logi.coef_     # 기울기

array([[0., 0.]])

In [ ]:
model_logi.intercept_ # 절편

In [7]:
model_logi.predict(x_data) # x데이터 예측 값

array([0, 0, 0, 0])

In [8]:
model_logi.score(x_data, y_data) # 로지스틱모델 정확도

0.5

# 사이킷런에서 지원하는딥러닝  

----

 - from sklearn.linear_model import LogisticRegression
 - from sklearn.neural_network import MLPClassifier


In [9]:
model_mlp = MLPClassifier(hidden_layer_sizes=(100,) ,max_iter=1000,verbose=True  )
model_mlp.fit(x_data,y_data)

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Iteration 1, loss = 0.69559282
Iteration 2, loss = 0.69422161
Iteration 3, loss = 0.69289527
Iteration 4, loss = 0.69158429
Iteration 5, loss = 0.69028808
Iteration 6, loss = 0.68900012
Iteration 7, loss = 0.68771659
Iteration 8, loss = 0.68643855
Iteration 9, loss = 0.68517492
Iteration 10, loss = 0.68390155
Iteration 11, loss = 0.68263374
Iteration 12, loss = 0.68138410
Iteration 13, loss = 0.68013944
Iteration 14, loss = 0.67889714
Iteration 15, loss = 0.67766569
Iteration 16, loss = 0.67642398
Iteration 17, loss = 0.67518358
Iteration 18, loss = 0.67394978
Iteration 19, loss = 0.67271912
Iteration 20, loss = 0.67148969
Iteration 21, loss = 0.67025669
Iteration 22, loss = 0.66904861
Iteration 23, loss = 0.66788567
Iteration 24, loss = 0.66680481
Iteration 25, loss = 0.66573496
Iteration 26, loss = 0.66465916
Iteration 27, loss = 0.66358692
Iteration 28, loss = 0.66259023
Iteration 29, loss = 0.66159300
Iteration 30, loss = 0.66060523
Iteration 31, loss = 0.65962842
Iteration 32, los

Iteration 548, loss = 0.07598631
Iteration 549, loss = 0.07562538
Iteration 550, loss = 0.07528511
Iteration 551, loss = 0.07493193
Iteration 552, loss = 0.07456734
Iteration 553, loss = 0.07421926
Iteration 554, loss = 0.07387779
Iteration 555, loss = 0.07352464
Iteration 556, loss = 0.07318665
Iteration 557, loss = 0.07284831
Iteration 558, loss = 0.07251230
Iteration 559, loss = 0.07217612
Iteration 560, loss = 0.07184102
Iteration 561, loss = 0.07150670
Iteration 562, loss = 0.07118195
Iteration 563, loss = 0.07085063
Iteration 564, loss = 0.07052187
Iteration 565, loss = 0.07019741
Iteration 566, loss = 0.06987974
Iteration 567, loss = 0.06956227
Iteration 568, loss = 0.06923819
Iteration 569, loss = 0.06892139
Iteration 570, loss = 0.06861456
Iteration 571, loss = 0.06830581
Iteration 572, loss = 0.06798507
Iteration 573, loss = 0.06767803
Iteration 574, loss = 0.06737670
Iteration 575, loss = 0.06706909
Iteration 576, loss = 0.06676549
Iteration 577, loss = 0.06646926
Iteration 

MLPClassifier(max_iter=1000, verbose=True)

In [10]:
model_mlp.predict(x_data)

array([0, 1, 1, 0])

In [11]:
model_mlp.coefs_  


# 4 x 2  matmul  2 x 100 => 4 x 100 
# 4 x 100 matmul 100 x 1 => 4 x 1    


[array([[ 8.33865842e-19,  6.34528048e-01,  1.88961217e-01,
          1.37930215e-01, -1.04943359e-09, -4.81257071e-02,
          3.68157966e-16, -7.96864417e-04,  8.93233416e-02,
          5.11828818e-21,  5.03389881e-01, -3.50776548e-01,
          6.26563336e-01, -3.17761235e-21,  1.75626498e-19,
          2.17674753e-20,  5.69680034e-01,  5.08827303e-20,
         -6.47081590e-01, -1.17314769e-07,  3.01558430e-21,
          5.16768229e-01,  5.74259754e-01, -8.68709962e-21,
         -5.48796701e-01, -7.04408013e-05, -4.07032899e-01,
         -5.13161978e-05,  3.44021160e-20, -1.02799859e-17,
          1.55398980e-20,  1.30394852e-02,  1.89303579e-14,
         -6.89354928e-01,  2.75973372e-01, -5.55810611e-01,
         -3.05755205e-20, -5.89091471e-01, -2.29160400e-08,
          3.94917222e-01, -5.57114655e-05, -4.72172509e-01,
          5.20752030e-01,  6.89005795e-01, -1.30335408e-16,
          3.69711975e-02,  5.01180973e-02,  4.89330961e-20,
         -1.42579345e-08, -7.20286582e-0

In [12]:
model_mlp.coefs_[0].shape , model_mlp.coefs_[1].shape #  기울기

((2, 100), (100, 1))

In [15]:
model_mlp.intercepts_[0].shape,model_mlp.intercepts_[1].shape

((100,), (1,))

In [16]:
model_mlp2 = MLPClassifier(hidden_layer_sizes=(100,50) ,max_iter=1000,verbose=True  )
model_mlp2.fit(x_data,y_data)

Iteration 1, loss = 0.70840009
Iteration 2, loss = 0.70038370
Iteration 3, loss = 0.69272521
Iteration 4, loss = 0.68527048
Iteration 5, loss = 0.67890895
Iteration 6, loss = 0.67385123
Iteration 7, loss = 0.66903154
Iteration 8, loss = 0.66424215
Iteration 9, loss = 0.65957283
Iteration 10, loss = 0.65522300
Iteration 11, loss = 0.65124453
Iteration 12, loss = 0.64720925
Iteration 13, loss = 0.64340115
Iteration 14, loss = 0.63953930
Iteration 15, loss = 0.63554287
Iteration 16, loss = 0.63156636
Iteration 17, loss = 0.62744504
Iteration 18, loss = 0.62333550
Iteration 19, loss = 0.61958857
Iteration 20, loss = 0.61559632
Iteration 21, loss = 0.61135457
Iteration 22, loss = 0.60701777
Iteration 23, loss = 0.60277005
Iteration 24, loss = 0.59873791
Iteration 25, loss = 0.59467510
Iteration 26, loss = 0.59044365
Iteration 27, loss = 0.58605936
Iteration 28, loss = 0.58149244
Iteration 29, loss = 0.57734776
Iteration 30, loss = 0.57293388
Iteration 31, loss = 0.56833617
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose=True)

In [17]:
len(model_mlp2.coefs_)

3

In [22]:
model_mlp2.coefs_[0].shape,model_mlp2.coefs_[1].shape,model_mlp2.coefs_[2].shape

((2, 100), (100, 50), (50, 1))

In [23]:
model_mlp3 = MLPClassifier(hidden_layer_sizes=(100,50,20) ,max_iter=1000,verbose=True  )
model_mlp3.fit(x_data,y_data)

Iteration 1, loss = 0.72011250
Iteration 2, loss = 0.71446665
Iteration 3, loss = 0.70878476
Iteration 4, loss = 0.70332149
Iteration 5, loss = 0.69796855
Iteration 6, loss = 0.69423268
Iteration 7, loss = 0.69033074
Iteration 8, loss = 0.68730946
Iteration 9, loss = 0.68488809
Iteration 10, loss = 0.68203540
Iteration 11, loss = 0.67920566
Iteration 12, loss = 0.67614419
Iteration 13, loss = 0.67276909
Iteration 14, loss = 0.66969747
Iteration 15, loss = 0.66701945
Iteration 16, loss = 0.66408333
Iteration 17, loss = 0.66110563
Iteration 18, loss = 0.65838343
Iteration 19, loss = 0.65589170
Iteration 20, loss = 0.65326759
Iteration 21, loss = 0.65026946
Iteration 22, loss = 0.64693515
Iteration 23, loss = 0.64370579
Iteration 24, loss = 0.64092444
Iteration 25, loss = 0.63792212
Iteration 26, loss = 0.63495373
Iteration 27, loss = 0.63244145
Iteration 28, loss = 0.62966158
Iteration 29, loss = 0.62663098
Iteration 30, loss = 0.62345376
Iteration 31, loss = 0.62014140
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


MLPClassifier(hidden_layer_sizes=(100, 50, 20), max_iter=1000, verbose=True)

In [30]:
model_mlp3.coefs_[0].shape,model_mlp3.coefs_[1].shape,model_mlp3.coefs_[2].shape,model_mlp3.coefs_[3].shape

((2, 100), (100, 50), (50, 20), (20, 1))

In [31]:
model_mlp3.predict(x_data)

array([0, 1, 1, 0])