In [23]:
import tensorflow as tf
import numpy as np
import pandas as pd

import math
import matplotlib.pyplot as plt 

plt.style.use('ggplot')

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense ,Flatten
from tensorflow.keras.optimizers import Adam

from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split


from sklearn.datasets import load_iris
# iris[5.1, 3.5, 1.4, 0.2]

In [24]:
iris = load_iris()
df = pd.DataFrame(iris['data'],columns=iris['feature_names'])
df['species'] = iris['target']
df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   species  
0        0  
1        0  
2        0

In [25]:
# 원핫 인코딩 
temp = pd.DataFrame(data= pd.get_dummies(df['species']).values)
temp.shape , df.shape

((150, 3), (150, 5))

In [26]:
df = pd.concat([df,temp],  axis=1)
del(df['species'])

In [27]:
df.sample(4)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
66                 5.6               3.0                4.5               1.5   
107                7.3               2.9                6.3               1.8   
96                 5.7               2.9                4.2               1.3   
55                 5.7               2.8                4.5               1.3   

     0  1  2  
66   0  1  0  
107  0  0  1  
96   0  1  0  
55   0  1  0


# 1. [5.1, 3.5, 1.4,  0.2   ]   종분류 예측

In [ ]:
x_data = df.iloc[:,0:4]
y_data = df.iloc[:,4:]

x = tf.constant(x_data, tf.float32)
y = tf.constant(y_data, tf.float32)

## 텐서


In [41]:
initX = tf.initializers.GlorotUniform()


w1 = tf.Variable( initX( shape = [4,64]  )    )
b1 = tf.Variable( initX( shape=[64] ) )

w2 = tf.Variable( initX( shape=[64,32] ) )
b2 = tf.Variable( initX( shape=[32] ) )

w3 = tf.Variable( initX(shape=[32,3]))
b3 = tf.Variable( initX(shape=[3]))

In [56]:
def compute_loss():
    z1 = tf.matmul(x,w1) + b1  # x 와 w1 matmul  4행2열 X 2행 2열 => 4행 2열 
    hx1 = tf.nn.softmax( z1 )  # z1을 sigmoid 함수에 넣음
    
    z2 = tf.matmul( hx1, w2  ) + b2  # 
    hx2 = tf.nn.softmax( z2 )
    
    z = tf.matmul(hx2 , w3 ) + b3
#     hx = tf.nn.sigmoid( z )   
    
    cost_i =tf.nn.softmax_cross_entropy_with_logits(logits=z,labels =y )
    cost = tf.reduce_mean(cost_i)
    return cost

In [57]:
optimizer = Adam(learning_rate=0.1)
for i in range(2000):
    optimizer.minimize(compute_loss, var_list=[w1,w2,w3,  b1,b2,b3  ])
    print(i, compute_loss().numpy())

0 3.3600757
1 2.3274465
2 1.9016781
3 1.7665417
4 1.4629936
5 1.1546067
6 0.9890017
7 0.95176005
8 0.909327
9 0.8336365
10 0.7752174
11 0.75185496
12 0.7177791
13 0.64822024
14 0.55753857
15 0.47764063
16 0.46246034
17 0.46667755
18 0.46922094
19 0.46962747
20 0.468617
21 0.46692398
22 0.46525025
23 0.4641276
24 0.46378744
25 0.46412206
26 0.46477142
27 0.46530524
28 0.46541718
29 0.46503958
30 0.46433595
31 0.46359634
32 0.46309245
33 0.46295843
34 0.4631449
35 0.4634636
36 0.46369526
37 0.46370077
38 0.4634775
39 0.46313986
40 0.4628447
41 0.46270585
42 0.46274242
43 0.46288204
44 0.46301132
45 0.46304262
46 0.4629564
47 0.4628018
48 0.4626591
49 0.46259028
50 0.46260807
51 0.46267506
52 0.4627333
53 0.46274003
54 0.46269044
55 0.46261397
56 0.46255255
57 0.46253213
58 0.46255076
59 0.46258366
60 0.46260193
61 0.46259084
62 0.4625568
63 0.46251994
64 0.46249917
65 0.46250036
66 0.4625144
67 0.46252584
68 0.46252376
69 0.46250802
70 0.46248794
71 0.46247402
72 0.4624713
73 0.46247634


551 0.041782767
552 0.041772418
553 0.041762285
554 0.041751917
555 0.041741904
556 0.041731726
557 0.041721694
558 0.041711748
559 0.041701972
560 0.041692153
561 0.041682355
562 0.04167269
563 0.041663002
564 0.04165349
565 0.041644022
566 0.04163465
567 0.041625183
568 0.041615933
569 0.041606784
570 0.041597713
571 0.04158846
572 0.04157942
573 0.041570436
574 0.041561652
575 0.04155287
576 0.04154401
577 0.04153525
578 0.041526526
579 0.04151799
580 0.041509442
581 0.041500747
582 0.041492317
583 0.041483935
584 0.04147554
585 0.04146743
586 0.04145909
587 0.041451
588 0.04144282
589 0.041434843
590 0.04142686
591 0.04141876
592 0.041410692
593 0.04140303
594 0.041395165
595 0.041387416
596 0.041379474
597 0.041372035
598 0.041364346
599 0.04135684
600 0.041349396
601 0.041341867
602 0.04133427
603 0.04132695
604 0.0413198
605 0.041312233
606 0.04130517
607 0.041298024
608 0.041290853
609 0.041283786
610 0.041276596
611 0.041269604
612 0.0412625
613 0.04125573
614 0.04124874
615 0

1081 0.0478482
1082 0.04654705
1083 0.048533242
1084 0.044614695
1085 0.04340227
1086 0.041841418
1087 0.041182395
1088 0.04079455
1089 0.040663492
1090 0.040693726
1091 0.040839892
1092 0.041096795
1093 0.041362207
1094 0.041818995
1095 0.042052865
1096 0.042695638
1097 0.042722065
1098 0.043441683
1099 0.04312132
1100 0.043704312
1101 0.043102045
1102 0.043431025
1103 0.042784527
1104 0.042935207
1105 0.042410657
1106 0.042503368
1107 0.042128958
1108 0.042234324
1109 0.041980114
1110 0.0421333
1111 0.041963845
1112 0.042192798
1113 0.04207824
1114 0.042412873
1115 0.042317223
1116 0.04277625
1117 0.042632952
1118 0.043180216
1119 0.0428903
1120 0.04339319
1121 0.042907614
1122 0.043211423
1123 0.042629465
1124 0.04271472
1125 0.042197112
1126 0.04216943
1127 0.041797787
1128 0.04176049
1129 0.04153152
1130 0.04154048
1131 0.041426484
1132 0.04152027
1133 0.04150945
1134 0.041757785
1135 0.04187119
1136 0.042432714
1137 0.042678747
1138 0.043792948
1139 0.04386518
1140 0.04535131
114

1600 0.040839024
1601 0.04060514
1602 0.040599607
1603 0.040760964
1604 0.041026637
1605 0.04124634
1606 0.041520786
1607 0.04156956
1608 0.041741744
1609 0.041666828
1610 0.041802444
1611 0.041738655
1612 0.04196438
1613 0.042001706
1614 0.042465612
1615 0.042631615
1616 0.043492332
1617 0.04359574
1618 0.044706453
1619 0.044112816
1620 0.044542056
1621 0.043200683
1622 0.042591993
1623 0.041534018
1624 0.040933188
1625 0.04061524
1626 0.040620185
1627 0.04085714
1628 0.041159786
1629 0.041506108
1630 0.04157163
1631 0.04167155
1632 0.04146607
1633 0.041366853
1634 0.041148935
1635 0.041045144
1636 0.040927637
1637 0.04089655
1638 0.040878635
1639 0.040950947
1640 0.041065115
1641 0.04138538
1642 0.041836143
1643 0.04298496
1644 0.044197395
1645 0.04752459
1646 0.047496207
1647 0.05046713
1648 0.045331534
1649 0.042948615
1650 0.041013584
1651 0.040637836
1652 0.04141861
1653 0.042384073
1654 0.04316524
1655 0.04213898
1656 0.041204922
1657 0.04068074
1658 0.04091212
1659 0.041562445


In [48]:
def hxfn( xdata ):
    xd = tf.constant( xdata, tf.float32)
    z1 = tf.matmul( xd, w1) + b1  
    hx1 = tf.nn.softmax( z1 )
    
    z2 = tf.matmul(hx1,w2)+b2
    hx2 = tf.nn.softmax( z2 )
    
    z3 = tf.matmul(hx2, w3 ) + b3
    hx = tf.nn.softmax( z3 )
    
    return (hx.numpy()>0.5) + 0

In [58]:
hxfn([[5.1,3.5,1.4,0.2]])

array([[1, 0, 0]])

In [77]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
print('정확도:',accuracy_score(y_data, hxfn(x_data)))

정확도: 0.9866666666666667


## 케라스

In [79]:
dense1 = Dense( units=100, input_dim=4 ,activation="softmax") # 2x100, b:100
dense2 = Dense( units=3, input_dim=100 ,activation="softmax") # 100x1 b: 1
model = Sequential( [dense1, dense2])
model.compile( loss="categorical_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 997us/step - loss: 0.9857 - acc: 0.4933
Epoch 2/1000
5/5 [==============================] - 0s 748us/step - loss: 0.7069 - acc: 0.7133
Epoch 3/1000
5/5 [==============================] - 0s 748us/step - loss: 0.5700 - acc: 0.7467
Epoch 4/1000
5/5 [==============================] - 0s 748us/step - loss: 0.5042 - acc: 0.6800
Epoch 5/1000
5/5 [==============================] - 0s 748us/step - loss: 0.4585 - acc: 0.7800
Epoch 6/1000
5/5 [==============================] - 0s 997us/step - loss: 0.4308 - acc: 0.7800
Epoch 7/1000
5/5 [==============================] - 0s 748us/step - loss: 0.4132 - acc: 0.7533
Epoch 8/1000
5/5 [==============================] - 0s 748us/step - loss: 0.3853 - acc: 0.7733
Epoch 9/1000
5/5 [==============================] - 0s 748us/step - loss: 0.3549 - acc: 0.8467
Epoch 10/1000
5/5 [==============================] - 0s 997us/step - loss: 0.2746 - acc: 0.8667
Epoch 11/1000
5/5 [==============================

5/5 [==============================] - 0s 748us/step - loss: 0.0459 - acc: 0.9800
Epoch 171/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0696 - acc: 0.9667
Epoch 172/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0822 - acc: 0.9667
Epoch 173/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0941 - acc: 0.9667
Epoch 174/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0447 - acc: 0.9867
Epoch 175/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0654 - acc: 0.9867
Epoch 176/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0559 - acc: 0.9800
Epoch 177/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0552 - acc: 0.9867
Epoch 178/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0827 - acc: 0.9667
Epoch 179/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0972 - acc: 0.9800
Epoch 180/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0467 - acc: 0.9867
Epoch 339/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0481 - acc: 0.9733
Epoch 340/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0470 - acc: 0.9867
Epoch 341/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0704 - acc: 0.9667
Epoch 342/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0730 - acc: 0.9600
Epoch 343/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0768 - acc: 0.9667
Epoch 344/1000
5/5 [==============================] - 0s 746us/step - loss: 0.0562 - acc: 0.9667
Epoch 345/1000
5/5 [==============================] - 0s 744us/step - loss: 0.0582 - acc: 0.9800
Epoch 346/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0473 - acc: 0.9867
Epoch 347/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0774 - acc: 0.9667
Epoch 348/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0718 - acc: 0.9667
Epoch 507/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0695 - acc: 0.9733
Epoch 508/1000
5/5 [==============================] - 0s 746us/step - loss: 0.1253 - acc: 0.9667
Epoch 509/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0896 - acc: 0.9667
Epoch 510/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1082 - acc: 0.9667
Epoch 511/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0497 - acc: 0.9867
Epoch 512/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0619 - acc: 0.9733
Epoch 513/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0497 - acc: 0.9800
Epoch 514/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0523 - acc: 0.9733
Epoch 515/1000
5/5 [==============================] - 0s 751us/step - loss: 0.0520 - acc: 0.9800
Epoch 516/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0664 - acc: 0.9733
Epoch 675/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0684 - acc: 0.9733
Epoch 676/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0585 - acc: 0.9867
Epoch 677/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0852 - acc: 0.9600
Epoch 678/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0615 - acc: 0.9800
Epoch 679/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0560 - acc: 0.9733
Epoch 680/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0547 - acc: 0.9800
Epoch 681/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0487 - acc: 0.9800
Epoch 682/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0539 - acc: 0.9733
Epoch 683/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0633 - acc: 0.9667
Epoch 684/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0567 - acc: 0.9800
Epoch 843/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0588 - acc: 0.9800
Epoch 844/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0852 - acc: 0.9733
Epoch 845/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0542 - acc: 0.9800
Epoch 846/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0723 - acc: 0.9733
Epoch 847/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0587 - acc: 0.9867
Epoch 848/1000
5/5 [==============================] - 0s 498us/step - loss: 0.0592 - acc: 0.9733
Epoch 849/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0772 - acc: 0.9667
Epoch 850/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0693 - acc: 0.9733
Epoch 851/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0747 - acc: 0.9733
Epoch 852/1000
5/5 [=========================

In [80]:
(model.predict([[5.1, 3.5, 1.4, 0.2]])>0.5)+0

array([[1, 0, 0]])

In [86]:
accuracy_score(y_data,(model.predict(x_data)>0.5  +0))

0.98

In [87]:
modelNN = Sequential()
modelNN.add( Dense( units=64, input_dim=4 ,activation="relu") )
modelNN.add( Dense( units=32, activation="relu") )
modelNN.add( Dense( units=3,  activation="softmax") )
modelNN.compile( loss="categorical_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = modelNN.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 998us/step - loss: 2.6984 - acc: 0.4800
Epoch 2/1000
5/5 [==============================] - 0s 498us/step - loss: 0.7711 - acc: 0.6600
Epoch 3/1000
5/5 [==============================] - 0s 997us/step - loss: 0.5009 - acc: 0.6867
Epoch 4/1000
5/5 [==============================] - 0s 997us/step - loss: 0.4832 - acc: 0.6467
Epoch 5/1000
5/5 [==============================] - 0s 998us/step - loss: 0.4501 - acc: 0.6733
Epoch 6/1000
5/5 [==============================] - 0s 999us/step - loss: 0.4078 - acc: 0.7800
Epoch 7/1000
5/5 [==============================] - 0s 748us/step - loss: 0.3268 - acc: 0.8867
Epoch 8/1000
5/5 [==============================] - 0s 748us/step - loss: 0.3176 - acc: 0.8733
Epoch 9/1000
5/5 [==============================] - 0s 997us/step - loss: 0.2516 - acc: 0.8800
Epoch 10/1000
5/5 [==============================] - 0s 998us/step - loss: 0.1239 - acc: 0.9667
Epoch 11/1000
5/5 [==============================

5/5 [==============================] - 0s 748us/step - loss: 0.0490 - acc: 0.9800
Epoch 171/1000
5/5 [==============================] - 0s 747us/step - loss: 0.0505 - acc: 0.9867
Epoch 172/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0505 - acc: 0.9733
Epoch 173/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0477 - acc: 0.9867
Epoch 174/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0474 - acc: 0.9800
Epoch 175/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0457 - acc: 0.9800
Epoch 176/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0469 - acc: 0.9867
Epoch 177/1000
5/5 [==============================] - 0s 744us/step - loss: 0.0450 - acc: 0.9800
Epoch 178/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0584 - acc: 0.9800
Epoch 179/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0450 - acc: 0.9733
Epoch 180/1000
5/5 [===========================

5/5 [==============================] - 0s 751us/step - loss: 0.0594 - acc: 0.9600
Epoch 339/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0518 - acc: 0.9733
Epoch 340/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0439 - acc: 0.9867
Epoch 341/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0466 - acc: 0.9800
Epoch 342/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0798 - acc: 0.9667
Epoch 343/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0956 - acc: 0.9800
Epoch 344/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1333 - acc: 0.9333
Epoch 345/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1870 - acc: 0.9533
Epoch 346/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1757 - acc: 0.9200
Epoch 347/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1975 - acc: 0.9267
Epoch 348/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0490 - acc: 0.9867
Epoch 507/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0424 - acc: 0.9867
Epoch 508/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0495 - acc: 0.9733
Epoch 509/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0730 - acc: 0.9733
Epoch 510/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0519 - acc: 0.9733
Epoch 511/1000
5/5 [==============================] - 0s 747us/step - loss: 0.0640 - acc: 0.9733
Epoch 512/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0906 - acc: 0.9600
Epoch 513/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0498 - acc: 0.9733
Epoch 514/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0790 - acc: 0.9600
Epoch 515/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1358 - acc: 0.9533
Epoch 516/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0463 - acc: 0.9800
Epoch 675/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0460 - acc: 0.9867
Epoch 676/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0582 - acc: 0.9667
Epoch 677/1000
5/5 [==============================] - 0s 750us/step - loss: 0.0692 - acc: 0.9733
Epoch 678/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0877 - acc: 0.9800
Epoch 679/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1582 - acc: 0.9600
Epoch 680/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1168 - acc: 0.9533
Epoch 681/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1098 - acc: 0.9467
Epoch 682/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0674 - acc: 0.9867
Epoch 683/1000
5/5 [==============================] - 0s 498us/step - loss: 0.0914 - acc: 0.9467
Epoch 684/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0521 - acc: 0.9800
Epoch 843/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0506 - acc: 0.9800
Epoch 844/1000
5/5 [==============================] - 0s 753us/step - loss: 0.0516 - acc: 0.9867
Epoch 845/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0545 - acc: 0.9800
Epoch 846/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0507 - acc: 0.9733
Epoch 847/1000
5/5 [==============================] - 0s 747us/step - loss: 0.0480 - acc: 0.9867
Epoch 848/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0460 - acc: 0.9800
Epoch 849/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0574 - acc: 0.9733
Epoch 850/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0485 - acc: 0.9800
Epoch 851/1000
5/5 [==============================] - 0s 746us/step - loss: 0.0464 - acc: 0.9867
Epoch 852/1000
5/5 [=========================

In [88]:
(modelNN.predict(x_data) >0.5)+0

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [89]:
(modelNN.predict([[5.1, 3.5, 1.4, 0.2]])>0.5) +0

array([[1, 0, 0]])

In [90]:
 modelNN.predict(x_data) 

array([[1.00000000e+00, 3.14316341e-29, 1.51092681e-38],
       [1.00000000e+00, 6.76049060e-21, 3.26932055e-29],
       [1.00000000e+00, 1.48554995e-25, 1.86044745e-34],
       [1.00000000e+00, 1.16506973e-18, 1.23810641e-26],
       [1.00000000e+00, 2.58785288e-30, 0.00000000e+00],
       [1.00000000e+00, 5.63189951e-23, 3.26904321e-31],
       [1.00000000e+00, 1.23984827e-22, 5.04060676e-31],
       [1.00000000e+00, 7.99074435e-25, 1.46664134e-33],
       [1.00000000e+00, 2.56505829e-17, 3.62055552e-25],
       [1.00000000e+00, 6.34047773e-23, 1.56269902e-31],
       [1.00000000e+00, 5.48071843e-31, 0.00000000e+00],
       [1.00000000e+00, 1.67257929e-21, 8.89239020e-30],
       [1.00000000e+00, 1.69384340e-23, 3.22739585e-32],
       [1.00000000e+00, 6.91962073e-29, 2.32976576e-38],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.05630398e-36, 0.00000000e+00],
       [1.00000000e+00, 6.21904323e-33, 0.00000000e+00],
       [1.00000000e+00, 3.26777

In [91]:
accuracy_score(y_data, (modelNN.predict(x_data)>0.5 )+0    )

0.98

In [96]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

array([[9.999919e-01, 8.158188e-06, 9.716642e-10]], dtype=float32)