In [1]:
import tensorflow as tf
import numpy as np

## scalar data

In [ ]:
s1 = 10 # 'abc' 
s2 = 'abc'
s3 = 3.14

### vector data

In [ ]:
v = [10,20,30]

## matrix data

In [ ]:
m = [[10,20,30], [40,50,60]] # 2 x 3

## 3d tensor

In [ ]:
# 2x2x3
d3 =[ [[10,20,30], [40,50,60]], [[10,20,30], [40,50,60]] ]

### 4d tensor

In [ ]:
#2 x2 x2 x3
d4 =[ [ [[10,20,30], [40,50,60]], [[10,20,30], [40,50,60]] ],
[ [[10,20,30], [40,50,60]], [[10,20,30], [40,50,60]] ] ]

### 텐서 데이터 노드정의하는 방법
## 1. constant:읽기전용
## 2. Variable: 읽기 쓰기

In [3]:
s1 = 10
c1 = tf.constant( s1 )
c1 # 텐서객체

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
c1.numpy()

10

In [5]:
v1 = [10,20,30]
t1 = tf.constant( v1 )
t1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [7]:
type(t1)

tensorflow.python.framework.ops.EagerTensor

In [6]:
t1.numpy()

array([10, 20, 30])

In [8]:
m = [[10,20,30], [40,50,60]]
t2 = tf.constant( m )
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

# 연산: element wise (요소별 연산)

In [9]:
a = tf.constant( 3 )
b = tf.constant( [1,2,3] )

In [10]:
c = tf.multiply( a, b)  # <===  a x b
c 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

In [11]:
c.numpy()

array([3, 6, 9])

In [12]:
#d = a + b
d = tf.add( a,b) # <= a + b
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [13]:
e = c+d #tf.add( c, b)
e

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12])>

### broad casting

In [14]:
f = tf.constant( [1,2,3])
g = tf.constant( [[1,2,3],[4,5,6],[7,8,9]] )
h = f + g # tf.add( f, g )

In [15]:
h.numpy()

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [16]:
i = tf.constant( [ [1],[2],[3] ] ) # 3x1
j = tf.constant( [[1,2,3],[4,5,6],[7,8,9]] )
k = i * j # tf.multiply( f, g )

In [17]:
k.numpy()

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [20]:
l = tf.constant( [ [1],[2] ] ) # 3x1
m = tf.constant( [[1,2,3],[4,5,6],[7,8,9]] )
n = l - m # tf.subtract( f, g )

InvalidArgumentError: Incompatible shapes: [2] vs. [3,3] [Op:Sub]

### 행열곱

In [22]:
o = tf.constant( [[1,2],[3,4] ] ) # 2x2
p = tf.constant( [[5,6],[7,8] ] ) # 2x2
q = tf.multiply( o, p)  # o*p
r = tf.matmul( o, p) # 별 5개 

In [23]:
q.numpy()

array([[ 5, 12],
       [21, 32]])

In [24]:
r.numpy()

array([[19, 22],
       [43, 50]])

### 많이 사용하는 operation

In [25]:
s = [1,2,3]
t = tf.square( s ) # s**2
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [26]:
u = tf.reduce_mean( s )
u

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Variable

In [27]:
v = tf.Variable(10)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
#v = 20 # x

In [ ]:
# v.assign(3)
# v.assign_add( 3 )
v.assign_sub( 3 )