In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = [1,2,3]
y_data = [1,2,3]

In [8]:
w = 3
x = tf.constant( x_data ,tf.float32)
y= tf.constant( y_data, tf.float32 )

In [9]:
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [10]:
hx =  tf.multiply( w, x) #w*x #  [3,6,9]
m = tf.subtract( hx, y ) # hx - y
sq = tf.square( m ) # (hx-y)**2
cost = tf.reduce_mean( sq )

In [16]:
def cost(w):
    hx = w*x
    cost = tf.reduce_mean( (hx-y)**2 )
    return cost

In [18]:
cost(3).numpy()

18.666666

In [19]:
cost(2).numpy()

4.6666665

In [12]:
hx

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 6., 9.], dtype=float32)>

In [13]:
sq

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4., 16., 36.], dtype=float32)>

In [11]:
cost.numpy()

18.666666