In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/test.csv', header=None)
df.columns=['q1','q2','mid','final']
df

q1  q2  mid  final
0   73  80   75    152
1   93  88   93    185
2   89  91   90    180
3   96  98  100    196
4   73  66   70    142
5   53  46   55    101
6   69  74   77    149
7   47  56   60    115
8   87  79   90    175
9   79  70   88    164
10  69  70   73    141
11  70  65   74    141
12  93  95   91    184
13  79  80   73    152
14  70  73   78    148
15  93  89   96    192
16  78  75   68    147
17  81  90   93    183
18  88  92   86    177
19  78  83   77    159
20  82  86   90    177
21  86  82   89    175
22  78  83   85    175
23  76  83   71    149
24  96  93   95    192

In [3]:
http://localhost:8890/notebooks/13.%EB%8B%A4%EC%A4%91%EC%84%A0%ED%98%95(%EC%BC%80%EB%9D%BC%EC%8A%A4).ipynb#x_data = df.iloc[:,:-1].values #특성데이터 추출
y_data = df.iloc[:, [-1]].values

In [4]:
dense = Dense( units=1, input_dim=3 ) # w:3x1,b:1 초기값...
model = Sequential( [dense] )
model.compile( loss='mse', optimizer=Adam(0.1) )
h = model.fit( x_data, y_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 182ms/step - loss: 24921.2227
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 17835.3613
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 11976.3086
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 7348.2749
Epoch 5/500
1/1 [==============================] - 0s 998us/step - loss: 3928.1826
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 1654.6776
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 417.1939
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 48.7187
Epoch 9/500
1/1 [==============================] - 0s 3ms/step - loss: 328.8171
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 1002.7010
Epoch 11/500
1/1 [==============================] - 0s 3ms/step - loss: 1815.6595
Epoch 12/500
1/1 [==============================] - 0s 3ms/step - loss: 2552.3823
Epoch 13/500
1/1 [====

1/1 [==============================] - 0s 2ms/step - loss: 44.5074
Epoch 103/500
1/1 [==============================] - 0s 3ms/step - loss: 44.5346
Epoch 104/500
1/1 [==============================] - 0s 2ms/step - loss: 44.5071
Epoch 105/500
1/1 [==============================] - 0s 2ms/step - loss: 44.4178
Epoch 106/500
1/1 [==============================] - 0s 2ms/step - loss: 44.2797
Epoch 107/500
1/1 [==============================] - 0s 2ms/step - loss: 44.1190
Epoch 108/500
1/1 [==============================] - 0s 2ms/step - loss: 43.9644
Epoch 109/500
1/1 [==============================] - 0s 3ms/step - loss: 43.8382
Epoch 110/500
1/1 [==============================] - 0s 996us/step - loss: 43.7503
Epoch 111/500
1/1 [==============================] - 0s 2ms/step - loss: 43.6974
Epoch 112/500
1/1 [==============================] - 0s 2ms/step - loss: 43.6661
Epoch 113/500
1/1 [==============================] - 0s 2ms/step - loss: 43.6389
Epoch 114/500
1/1 [=====================

1/1 [==============================] - 0s 996us/step - loss: 37.2449
Epoch 202/500
1/1 [==============================] - 0s 997us/step - loss: 37.1701
Epoch 203/500
1/1 [==============================] - 0s 997us/step - loss: 37.0954
Epoch 204/500
1/1 [==============================] - 0s 998us/step - loss: 37.0205
Epoch 205/500
1/1 [==============================] - 0s 997us/step - loss: 36.9457
Epoch 206/500
1/1 [==============================] - 0s 998us/step - loss: 36.8708
Epoch 207/500
1/1 [==============================] - 0s 997us/step - loss: 36.7959
Epoch 208/500
1/1 [==============================] - 0s 2ms/step - loss: 36.7210
Epoch 209/500
1/1 [==============================] - 0s 998us/step - loss: 36.6461
Epoch 210/500
1/1 [==============================] - 0s 997us/step - loss: 36.5712
Epoch 211/500
1/1 [==============================] - 0s 996us/step - loss: 36.4962
Epoch 212/500
1/1 [==============================] - 0s 997us/step - loss: 36.4213
Epoch 213/500
1/1 [=

1/1 [==============================] - 0s 997us/step - loss: 29.9338
Epoch 301/500
1/1 [==============================] - 0s 997us/step - loss: 29.8626
Epoch 302/500
1/1 [==============================] - 0s 996us/step - loss: 29.7915
Epoch 303/500
1/1 [==============================] - 0s 998us/step - loss: 29.7206
Epoch 304/500
1/1 [==============================] - 0s 997us/step - loss: 29.6496
Epoch 305/500
1/1 [==============================] - 0s 998us/step - loss: 29.5788
Epoch 306/500
1/1 [==============================] - 0s 998us/step - loss: 29.5080
Epoch 307/500
1/1 [==============================] - 0s 997us/step - loss: 29.4374
Epoch 308/500
1/1 [==============================] - 0s 997us/step - loss: 29.3668
Epoch 309/500
1/1 [==============================] - 0s 998us/step - loss: 29.2964
Epoch 310/500
1/1 [==============================] - 0s 997us/step - loss: 29.2260
Epoch 311/500
1/1 [==============================] - 0s 997us/step - loss: 29.1556
Epoch 312/500
1/1 

1/1 [==============================] - 0s 997us/step - loss: 23.3825
Epoch 400/500
1/1 [==============================] - 0s 997us/step - loss: 23.3222
Epoch 401/500
1/1 [==============================] - 0s 998us/step - loss: 23.2620
Epoch 402/500
1/1 [==============================] - 0s 2ms/step - loss: 23.2019
Epoch 403/500
1/1 [==============================] - 0s 998us/step - loss: 23.1420
Epoch 404/500
1/1 [==============================] - 0s 997us/step - loss: 23.0822
Epoch 405/500
1/1 [==============================] - 0s 997us/step - loss: 23.0225
Epoch 406/500
1/1 [==============================] - 0s 998us/step - loss: 22.9629
Epoch 407/500
1/1 [==============================] - 0s 998us/step - loss: 22.9035
Epoch 408/500
1/1 [==============================] - 0s 997us/step - loss: 22.8442
Epoch 409/500
1/1 [==============================] - 0s 998us/step - loss: 22.7850
Epoch 410/500
1/1 [==============================] - 0s 997us/step - loss: 22.7260
Epoch 411/500
1/1 [=

1/1 [==============================] - 0s 997us/step - loss: 18.0556
Epoch 499/500
1/1 [==============================] - 0s 997us/step - loss: 18.0086
Epoch 500/500
1/1 [==============================] - 0s 2ms/step - loss: 17.9617


In [8]:
# q1:80, q2:90, mid:90 최종점수를 예측하시요
model.predict( [[80,90,90]] )

array([[174.8546]], dtype=float32)

In [5]:
w,b = dense.get_weights()

In [6]:
w

array([[0.78197044],
       [0.7507158 ],
       [0.48876297]], dtype=float32)

In [7]:
b

array([0.74388003], dtype=float32)

In [ ]:
1. 상관관계
2. 정규화
3. 다중공선성