In [8]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam

In [2]:
#공부한시간, 출석일수
x_data = np.array( [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]])
y_data = np.array( [[0],[0],[0],[1],[1],[1]])

In [3]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [4]:
# xavier, he( 최적의 초기화 알고리즘)
initX =tf.initializers.GlorotUniform()
w = tf.Variable( initX( shape=[2,1] ) )
b = tf.Variable( initX( shape=[1] ) )

In [6]:
def compute_loss():
    z = tf.matmul( x, w) + b
#     hx = tf.nn.sigmoid( z ) # 0~1 사이값
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits( labels=y , logits= z)
    cost = tf.reduce_mean( cost_i )
#     hx = tf.matmul( x, w) + b
#     cost = tf.reduce_mean( (hx-y)**2)
    return cost

In [9]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b] )
    print(i, 'cost:', compute_loss().numpy() )

0 cost: 0.6256783
1 cost: 0.6120441
2 cost: 0.6093374
3 cost: 0.5894156
4 cost: 0.5579164
5 cost: 0.52706313
6 cost: 0.50595
7 cost: 0.49480617
8 cost: 0.48489976
9 cost: 0.46870676
10 cost: 0.447341
11 cost: 0.42662397
12 cost: 0.41054574
13 cost: 0.39882424
14 cost: 0.38862714
15 cost: 0.37743473
16 cost: 0.36455604
17 cost: 0.35099375
18 cost: 0.33842507
19 cost: 0.32799226
20 cost: 0.31950015
21 cost: 0.31161496
22 cost: 0.30303314
23 cost: 0.29352936
24 cost: 0.28388664
25 cost: 0.2750132
26 cost: 0.2672256
27 cost: 0.26019442
28 cost: 0.25334927
29 cost: 0.24630405
30 cost: 0.23903994
31 cost: 0.23182599
32 cost: 0.22499323
33 cost: 0.21871378
34 cost: 0.21290918
35 cost: 0.20733674
36 cost: 0.20177972
37 cost: 0.19619061
38 cost: 0.19068624
39 cost: 0.18542802
40 cost: 0.18050265
41 cost: 0.17588444
42 cost: 0.17147827
43 cost: 0.16719103
44 cost: 0.1629814
45 cost: 0.15886751
46 cost: 0.15489979
47 cost: 0.1511222
48 cost: 0.14754437
49 cost: 0.14413887
50 cost: 0.14086004
51 c

403 cost: 0.008262691
404 cost: 0.008232069
405 cost: 0.0082016345
406 cost: 0.008171376
407 cost: 0.0081413
408 cost: 0.008111399
409 cost: 0.008081675
410 cost: 0.008052128
411 cost: 0.008022751
412 cost: 0.007993552
413 cost: 0.007964523
414 cost: 0.007935664
415 cost: 0.007906969
416 cost: 0.00787844
417 cost: 0.00785008
418 cost: 0.00782188
419 cost: 0.007793845
420 cost: 0.0077659707
421 cost: 0.0077382587
422 cost: 0.0077107004
423 cost: 0.0076833046
424 cost: 0.0076560625
425 cost: 0.007628976
426 cost: 0.007602043
427 cost: 0.0075752623
428 cost: 0.0075486354
429 cost: 0.0075221583
430 cost: 0.0074958303
431 cost: 0.0074696504
432 cost: 0.0074436176
433 cost: 0.0074177273
434 cost: 0.007391983
435 cost: 0.007366383
436 cost: 0.0073409253
437 cost: 0.0073156096
438 cost: 0.0072904304
439 cost: 0.0072653913
440 cost: 0.0072404915
441 cost: 0.007215727
442 cost: 0.007191099
443 cost: 0.007166606
444 cost: 0.007142247
445 cost: 0.0071180216
446 cost: 0.0070939264
447 cost: 0.00706

820 cost: 0.0027536803
821 cost: 0.0027483061
822 cost: 0.002742949
823 cost: 0.0027376078
824 cost: 0.0027322818
825 cost: 0.002726972
826 cost: 0.0027216782
827 cost: 0.0027164007
828 cost: 0.0027111385
829 cost: 0.0027058925
830 cost: 0.002700663
831 cost: 0.0026954485
832 cost: 0.00269025
833 cost: 0.002685067
834 cost: 0.0026798984
835 cost: 0.0026747456
836 cost: 0.0026696094
837 cost: 0.0026644876
838 cost: 0.0026593797
839 cost: 0.0026542891
840 cost: 0.002649213
841 cost: 0.0026441524
842 cost: 0.0026391048
843 cost: 0.002634073
844 cost: 0.0026290556
845 cost: 0.0026240537
846 cost: 0.0026190656
847 cost: 0.0026140928
848 cost: 0.0026091354
849 cost: 0.0026041924
850 cost: 0.0025992624
851 cost: 0.002594347
852 cost: 0.0025894467
853 cost: 0.002584561
854 cost: 0.0025796888
855 cost: 0.0025748315
856 cost: 0.002569988
857 cost: 0.0025651583
858 cost: 0.0025603438
859 cost: 0.0025555415
860 cost: 0.0025507542
861 cost: 0.0025459807
862 cost: 0.0025412198
863 cost: 0.0025364747

In [10]:
w.numpy()

array([[2.1052947],
       [2.0978122]], dtype=float32)

In [17]:
def hxfn( xdata):
    xd = tf.constant( xdata ,tf.float32)
    z = tf.matmul( xd, w) +b
    hx = tf.nn.sigmoid( z )
    return (hx.numpy()>0.5) +0
#     return z.numpy(), hx.numpy()

In [18]:
hxfn( [[4,5]])

array([[1]])

In [19]:
hxfn( [[2,2]])

array([[0]])

In [16]:
False + 1

1