In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

In [2]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [3]:
dense1 = Dense( units=100, input_dim=2 ,activation="sigmoid") # w:2x100, b:100
dense2 = Dense( units=1, input_dim=100 ,activation="sigmoid") # w:100x1, b:1
model = Sequential( [dense1,dense2])
model.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 261ms/step - loss: 0.7027 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 8ms/step - loss: 2.7332 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.0528 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.2825 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.7157 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.3777 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.8260 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7429 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0316 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.1406 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - 

1/1 [==============================] - 0s 2ms/step - loss: 0.2594 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2514 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2432 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2348 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2261 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2173 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2085 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1996 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1909 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1823 - acc: 1.0000
Epoch 98/1000
1/1 [==============================] - 0s 2ms/step - loss: 0

1/1 [==============================] - 0s 3ms/step - loss: 0.0101 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0099 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0097 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0096 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0094 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0093 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0091 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0090 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0088 - acc: 1.0000
Epoch 183/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0087 - acc: 1.0000
Epoch 184/1000
1/1 [==============================] - 0s 997u

1/1 [==============================] - 0s 2ms/step - loss: 0.0037 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0037 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0036 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0036 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0036 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0035 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0035 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0035 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0035 - acc: 1.0000
Epoch 268/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - acc: 1.0000
Epoch 269/1000
1/1 [==============================] - 0s 2ms/

1/1 [==============================] - 0s 2ms/step - loss: 0.0020 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0020 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0020 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0020 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0019 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 353/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0019 - acc: 1.0000
Epoch 354/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0019 - acc: 1.0000
Epoch 355/1000
1/1 [==============================] - 0s 

Epoch 431/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0013 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0012 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0012 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0012 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 999us/step - loss: 0.0012 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 438/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 439/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 440/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 441/1000
1/1 [========================

1/1 [==============================] - 0s 2ms/step - loss: 8.7548e-04 - acc: 1.0000
Epoch 516/1000
1/1 [==============================] - 0s 997us/step - loss: 8.7210e-04 - acc: 1.0000
Epoch 517/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.6874e-04 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.6540e-04 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 997us/step - loss: 8.6208e-04 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.5879e-04 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 997us/step - loss: 8.5551e-04 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.5225e-04 - acc: 1.0000
Epoch 523/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.4901e-04 - acc: 1.0000
Epoch 524/1000
1/1 [==============================] - 0s 997us/step - loss: 8.4580e-04 - acc: 1.0000
Epoch 525/1000
1/

1/1 [==============================] - 0s 2ms/step - loss: 6.5440e-04 - acc: 1.0000
Epoch 598/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.5227e-04 - acc: 1.0000
Epoch 599/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.5015e-04 - acc: 1.0000
Epoch 600/1000
1/1 [==============================] - 0s 998us/step - loss: 6.4804e-04 - acc: 1.0000
Epoch 601/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.4595e-04 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 997us/step - loss: 6.4386e-04 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 984us/step - loss: 6.4178e-04 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 997us/step - loss: 6.3972e-04 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.3767e-04 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 996us/step - loss: 6.3562e-04 - acc: 1.0000
Epoch 607/1000


1/1 [==============================] - 0s 2ms/step - loss: 5.1043e-04 - acc: 1.0000
Epoch 680/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.0899e-04 - acc: 1.0000
Epoch 681/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.0756e-04 - acc: 1.0000
Epoch 682/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.0614e-04 - acc: 1.0000
Epoch 683/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.0472e-04 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.0331e-04 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.0190e-04 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.0050e-04 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.9911e-04 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.9772e-04 - acc: 1.0000
Epoch 689/1000
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 4.1077e-04 - acc: 1.0000
Epoch 762/1000
1/1 [==============================] - 0s 998us/step - loss: 4.0975e-04 - acc: 1.0000
Epoch 763/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.0873e-04 - acc: 1.0000
Epoch 764/1000
1/1 [==============================] - 0s 998us/step - loss: 4.0772e-04 - acc: 1.0000
Epoch 765/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.0671e-04 - acc: 1.0000
Epoch 766/1000
1/1 [==============================] - 0s 997us/step - loss: 4.0570e-04 - acc: 1.0000
Epoch 767/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.0470e-04 - acc: 1.0000
Epoch 768/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.0370e-04 - acc: 1.0000
Epoch 769/1000
1/1 [==============================] - 0s 998us/step - loss: 4.0271e-04 - acc: 1.0000
Epoch 770/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.0171e-04 - acc: 1.0000
Epoch 771/1000
1/

1/1 [==============================] - 0s 1ms/step - loss: 3.3849e-04 - acc: 1.0000
Epoch 844/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3774e-04 - acc: 1.0000
Epoch 845/1000
1/1 [==============================] - 0s 997us/step - loss: 3.3698e-04 - acc: 1.0000
Epoch 846/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3623e-04 - acc: 1.0000
Epoch 847/1000
1/1 [==============================] - 0s 997us/step - loss: 3.3548e-04 - acc: 1.0000
Epoch 848/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3474e-04 - acc: 1.0000
Epoch 849/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3399e-04 - acc: 1.0000
Epoch 850/1000
1/1 [==============================] - 0s 998us/step - loss: 3.3325e-04 - acc: 1.0000
Epoch 851/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3251e-04 - acc: 1.0000
Epoch 852/1000
1/1 [==============================] - 0s 2ms/step - loss: 3.3178e-04 - acc: 1.0000
Epoch 853/1000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 2.8415e-04 - acc: 1.0000
Epoch 926/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8358e-04 - acc: 1.0000
Epoch 927/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8300e-04 - acc: 1.0000
Epoch 928/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8243e-04 - acc: 1.0000
Epoch 929/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8185e-04 - acc: 1.0000
Epoch 930/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8128e-04 - acc: 1.0000
Epoch 931/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.8071e-04 - acc: 1.0000
Epoch 932/1000
1/1 [==============================] - 0s 998us/step - loss: 2.8015e-04 - acc: 1.0000
Epoch 933/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.7958e-04 - acc: 1.0000
Epoch 934/1000
1/1 [==============================] - 0s 2ms/step - loss: 2.7902e-04 - acc: 1.0000
Epoch 935/1000
1/1 [===

In [4]:
( model.predict(x_data)>0.5) +0

array([[0],
       [1],
       [1],
       [0]])

In [5]:
w, b = dense1.get_weights()
w

array([[-6.20337   , -2.5197327 , -6.0533743 , -1.1446409 , -1.1750504 ,
        -1.5120342 ,  1.5745621 , -0.58575124, -5.8468328 , -5.9659677 ,
        -2.9848983 , -2.5832262 , -3.3674586 ,  1.1025324 , -1.6374552 ,
        -6.1274443 , -8.329054  ,  1.5123022 , -1.4891868 , -1.4797653 ,
        -1.3838698 ,  3.500406  , -1.4502635 , -1.3816575 , -0.3309761 ,
        -7.435297  , -5.4298663 , -4.979408  , -6.1630344 , -1.7087163 ,
        -2.3300834 , -3.2543232 , -1.264646  , -1.1415788 , -7.842166  ,
        -3.4916432 , -5.7068353 , -1.0469804 , -4.1267567 ,  2.583222  ,
        -6.945619  , -1.2955763 , -4.067757  , -4.6622577 , -1.7995563 ,
         1.6462705 , -1.6784415 ,  1.9195144 , -1.2936804 , -4.4617305 ,
        -1.4263232 , -2.8983476 , -1.3228459 , -5.8253236 , -4.74399   ,
        -3.0560386 ,  0.7456143 , -2.8430135 ,  0.9728152 ,  1.8477161 ,
        -6.0354776 ,  1.9951799 , -4.7377644 , -1.3802356 , -6.4475904 ,
        -0.8469652 , -2.3780913 ,  0.9968212 ,  2.7

In [6]:
w, b = dense2.get_weights()
w

array([[-1.3304504 ],
       [ 0.54351175],
       [ 1.571005  ],
       [ 0.19692335],
       [ 0.21555613],
       [ 0.22821873],
       [ 1.3512256 ],
       [ 0.20577653],
       [ 1.2243183 ],
       [ 1.4492627 ],
       [-0.2603139 ],
       [-0.18145432],
       [-0.37133324],
       [-0.7175327 ],
       [ 0.53872544],
       [ 1.3672284 ],
       [-2.7802975 ],
       [ 1.2307086 ],
       [ 0.22062485],
       [ 0.18676195],
       [ 0.20967449],
       [-3.82008   ],
       [ 0.05021207],
       [ 0.06136715],
       [ 0.72570825],
       [-1.9895699 ],
       [-1.170231  ],
       [-0.8148029 ],
       [-1.5453502 ],
       [-0.00597596],
       [-0.16152456],
       [ 0.82595986],
       [ 0.18770128],
       [ 0.18938757],
       [-2.3222473 ],
       [ 0.5123431 ],
       [ 1.3515781 ],
       [ 0.2507385 ],
       [-0.6936021 ],
       [ 1.4738766 ],
       [-1.5521894 ],
       [ 0.20793477],
       [-0.531682  ],
       [ 0.8231156 ],
       [-0.03540113],
       [ 0

In [ ]:
4x2 2x100 = 4x100 100x1 = 4x1

In [7]:
modelNN = Sequential()
modelNN.add( Dense( units=64, input_dim=2 ,activation="sigmoid") )
modelNN.add( Dense( units=32, activation="sigmoid") )
modelNN.add( Dense( units=1,  activation="sigmoid") )
modelNN.compile( loss="binary_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = modelNN.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 245ms/step - loss: 0.6941 - acc: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 2.5307 - acc: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.3555 - acc: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.8045 - acc: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.8615 - acc: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7664 - acc: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7212 - acc: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7043 - acc: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.6966 - acc: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6937 - acc: 0.5000
Epoch 11/1000
1/1 [==============================] - 0s 2ms/step - 

1/1 [==============================] - 0s 2ms/step - loss: 0.0310 - acc: 1.0000
Epoch 88/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0293 - acc: 1.0000
Epoch 89/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0277 - acc: 1.0000
Epoch 90/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0263 - acc: 1.0000
Epoch 91/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0250 - acc: 1.0000
Epoch 92/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0239 - acc: 1.0000
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0228 - acc: 1.0000
Epoch 94/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0219 - acc: 1.0000
Epoch 95/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0211 - acc: 1.0000
Epoch 96/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0204 - acc: 1.0000
Epoch 97/1000
1/1 [==============================] - 0s 2ms/step - los

1/1 [==============================] - 0s 2ms/step - loss: 0.0064 - acc: 1.0000
Epoch 174/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0063 - acc: 1.0000
Epoch 175/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0063 - acc: 1.0000
Epoch 176/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0062 - acc: 1.0000
Epoch 177/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0062 - acc: 1.0000
Epoch 178/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0061 - acc: 1.0000
Epoch 179/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0061 - acc: 1.0000
Epoch 180/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0060 - acc: 1.0000
Epoch 181/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0060 - acc: 1.0000
Epoch 182/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.0059 - acc: 1.0000
Epoch 183/1000
1/1 [==============================] - 0s 2ms/step

Epoch 259/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - acc: 1.0000
Epoch 260/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - acc: 1.0000
Epoch 261/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - acc: 1.0000
Epoch 262/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0034 - acc: 1.0000
Epoch 263/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 264/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 265/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 266/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 267/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0033 - acc: 1.0000
Epoch 268/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0032 - acc: 1.0000
Epoch 269/1000
1/1 [============================

Epoch 345/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 346/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 347/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0022 - acc: 1.0000
Epoch 348/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 349/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0022 - acc: 1.0000
Epoch 350/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 351/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 352/1000
1/1 [==============================] - 0s 996us/step - loss: 0.0021 - acc: 1.0000
Epoch 353/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 354/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 355/1000
1/1 [============================

1/1 [==============================] - 0s 3ms/step - loss: 0.0016 - acc: 1.0000
Epoch 432/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0016 - acc: 1.0000
Epoch 433/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0015 - acc: 1.0000
Epoch 434/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0015 - acc: 1.0000
Epoch 435/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0015 - acc: 1.0000
Epoch 436/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0015 - acc: 1.0000
Epoch 437/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0015 - acc: 1.0000
Epoch 438/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0015 - acc: 1.0000
Epoch 439/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0015 - acc: 1.0000
Epoch 440/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0015 - acc: 1.0000
Epoch 441/1000
1/1 [==============================] - 0s 2ms/st

1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 518/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 519/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0012 - acc: 1.0000
Epoch 520/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 521/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 522/1000
1/1 [==============================] - 0s 550us/step - loss: 0.0012 - acc: 1.0000
Epoch 523/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0012 - acc: 1.0000
Epoch 524/1000
1/1 [==============================] - 0s 998us/step - loss: 0.0012 - acc: 1.0000
Epoch 525/1000
1/1 [==============================] - 0s 997us/step - loss: 0.0011 - acc: 1.0000
Epoch 526/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.0011 - acc: 1.0000
Epoch 527/1000
1/1 [==============================] - 0s 2m

1/1 [==============================] - 0s 2ms/step - loss: 9.2909e-04 - acc: 1.0000
Epoch 602/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.2666e-04 - acc: 1.0000
Epoch 603/1000
1/1 [==============================] - 0s 997us/step - loss: 9.2424e-04 - acc: 1.0000
Epoch 604/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.2183e-04 - acc: 1.0000
Epoch 605/1000
1/1 [==============================] - 0s 996us/step - loss: 9.1944e-04 - acc: 1.0000
Epoch 606/1000
1/1 [==============================] - 0s 3ms/step - loss: 9.1705e-04 - acc: 1.0000
Epoch 607/1000
1/1 [==============================] - 0s 998us/step - loss: 9.1467e-04 - acc: 1.0000
Epoch 608/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.1230e-04 - acc: 1.0000
Epoch 609/1000
1/1 [==============================] - 0s 2ms/step - loss: 9.0994e-04 - acc: 1.0000
Epoch 610/1000
1/1 [==============================] - 0s 3ms/step - loss: 9.0759e-04 - acc: 1.0000
Epoch 611/1000
1/1 

1/1 [==============================] - 0s 996us/step - loss: 7.5894e-04 - acc: 1.0000
Epoch 684/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5718e-04 - acc: 1.0000
Epoch 685/1000
1/1 [==============================] - 0s 1ms/step - loss: 7.5542e-04 - acc: 1.0000
Epoch 686/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5367e-04 - acc: 1.0000
Epoch 687/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.5192e-04 - acc: 1.0000
Epoch 688/1000
1/1 [==============================] - 0s 3ms/step - loss: 7.5019e-04 - acc: 1.0000
Epoch 689/1000
1/1 [==============================] - 0s 997us/step - loss: 7.4846e-04 - acc: 1.0000
Epoch 690/1000
1/1 [==============================] - 0s 3ms/step - loss: 7.4673e-04 - acc: 1.0000
Epoch 691/1000
1/1 [==============================] - 0s 997us/step - loss: 7.4501e-04 - acc: 1.0000
Epoch 692/1000
1/1 [==============================] - 0s 2ms/step - loss: 7.4330e-04 - acc: 1.0000
Epoch 693/1000
1/1 

1/1 [==============================] - 0s 3ms/step - loss: 6.3320e-04 - acc: 1.0000
Epoch 766/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.3187e-04 - acc: 1.0000
Epoch 767/1000
1/1 [==============================] - 0s 3ms/step - loss: 6.3055e-04 - acc: 1.0000
Epoch 768/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.2923e-04 - acc: 1.0000
Epoch 769/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.2792e-04 - acc: 1.0000
Epoch 770/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.2661e-04 - acc: 1.0000
Epoch 771/1000
1/1 [==============================] - 0s 3ms/step - loss: 6.2530e-04 - acc: 1.0000
Epoch 772/1000
1/1 [==============================] - 0s 2ms/step - loss: 6.2400e-04 - acc: 1.0000
Epoch 773/1000
1/1 [==============================] - 0s 3ms/step - loss: 6.2271e-04 - acc: 1.0000
Epoch 774/1000
1/1 [==============================] - 0s 997us/step - loss: 6.2141e-04 - acc: 1.0000
Epoch 775/1000
1/1 [===

1/1 [==============================] - 0s 3ms/step - loss: 5.3723e-04 - acc: 1.0000
Epoch 848/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.3620e-04 - acc: 1.0000
Epoch 849/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.3518e-04 - acc: 1.0000
Epoch 850/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.3416e-04 - acc: 1.0000
Epoch 851/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.3314e-04 - acc: 1.0000
Epoch 852/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.3212e-04 - acc: 1.0000
Epoch 853/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.3111e-04 - acc: 1.0000
Epoch 854/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.3010e-04 - acc: 1.0000
Epoch 855/1000
1/1 [==============================] - 0s 3ms/step - loss: 5.2909e-04 - acc: 1.0000
Epoch 856/1000
1/1 [==============================] - 0s 2ms/step - loss: 5.2809e-04 - acc: 1.0000
Epoch 857/1000
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 4.6205e-04 - acc: 1.0000
Epoch 930/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.6124e-04 - acc: 1.0000
Epoch 931/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.6042e-04 - acc: 1.0000
Epoch 932/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.5961e-04 - acc: 1.0000
Epoch 933/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.5880e-04 - acc: 1.0000
Epoch 934/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5800e-04 - acc: 1.0000
Epoch 935/1000
1/1 [==============================] - 0s 2ms/step - loss: 4.5719e-04 - acc: 1.0000
Epoch 936/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.5639e-04 - acc: 1.0000
Epoch 937/1000
1/1 [==============================] - 0s 997us/step - loss: 4.5559e-04 - acc: 1.0000
Epoch 938/1000
1/1 [==============================] - 0s 3ms/step - loss: 4.5480e-04 - acc: 1.0000
Epoch 939/1000
1/1 [===

In [12]:
(modelNN.predict(x_data) >0.5)

array([[False],
       [ True],
       [ True],
       [False]])

In [8]:
modelNN.layers

In [9]:
w, b=modelNN.layers[0].get_weights()
w

array([[-1.4671457 ,  2.1011145 , -1.4837378 , -1.6987456 , -3.3031175 ,
        -2.2090516 , -2.5011363 , -0.94582886, -1.3171576 ,  2.5685687 ,
         2.434232  ,  2.179923  , -1.7763755 , -1.3693708 , -2.6408174 ,
        -2.8016467 , -2.2676554 , -0.5914963 , -1.4886992 , -2.015416  ,
        -3.6095462 , -1.6242898 , -2.3303192 , -1.9797713 , -0.50609523,
        -2.0892231 ,  1.3670307 , -1.8810287 , -1.669695  , -1.7787848 ,
         1.9872754 , -1.7171731 , -1.4808999 , -0.9710782 , -1.6519277 ,
        -2.321187  ,  2.242753  , -1.7160432 , -2.0209267 , -1.2613614 ,
        -2.2297482 , -1.1700035 , -2.2650602 , -1.362931  , -1.0175296 ,
        -2.0625563 , -1.827896  , -0.7624507 , -2.2640164 , -1.8948377 ,
        -2.101485  , -1.7308874 , -1.9636045 , -1.7578179 , -2.4410028 ,
         2.0755067 , -1.5435002 , -2.2975967 , -1.9609498 , -0.74470586,
        -1.9975467 , -1.8811127 , -3.4369252 , -1.4821465 ],
       [-2.0329378 ,  2.1353297 , -1.6935432 , -1.70248   , -3.

In [10]:
w, b=modelNN.layers[1].get_weights()
w

array([[-0.30475008, -0.7204257 , -2.300105  , ..., -1.4202838 ,
        -0.08448885, -0.41945985],
       [-0.6239601 , -0.7415348 ,  2.0767179 , ...,  2.19102   ,
        -0.51329315, -0.4895944 ],
       [-0.62094206, -0.3518606 , -2.1164427 , ..., -0.4483402 ,
        -0.17252386, -0.31025556],
       ...,
       [-0.52731776, -0.62364984, -2.2972395 , ..., -1.0903937 ,
        -0.28556395, -0.46666422],
       [-0.6275081 , -0.40000716, -2.127409  , ..., -2.3935325 ,
        -0.32125688, -0.49790445],
       [-0.67085075, -0.7166581 , -2.6114974 , ..., -0.966124  ,
        -0.0552547 , -0.43907914]], dtype=float32)