In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import numpy as np

In [4]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
y_data = np.array( [[0],[1],[1],[0] ] )

In [6]:
model_logi = LogisticRegression( max_iter=1000, verbose=1)
model_logi.fit( x_data, y_data)

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=1000, verbose=1)

In [8]:
model_logi.coef_

array([[0., 0.]])

In [9]:
model_logi.intercept_

array([0.])

In [10]:
model_logi.predict(x_data)

array([0, 0, 0, 0])

In [12]:
model_logi.score(x_data, y_data)

0.5

### 딥러닝

In [13]:
model_mlp = MLPClassifier( hidden_layer_sizes=(100,), max_iter=1000 ,verbose=True)
model_mlp.fit( x_data, y_data )

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.69938567
Iteration 2, loss = 0.69711555
Iteration 3, loss = 0.69491125
Iteration 4, loss = 0.69279517
Iteration 5, loss = 0.69071796
Iteration 6, loss = 0.68881746
Iteration 7, loss = 0.68695245
Iteration 8, loss = 0.68516808
Iteration 9, loss = 0.68345292
Iteration 10, loss = 0.68183357
Iteration 11, loss = 0.68027709
Iteration 12, loss = 0.67878793
Iteration 13, loss = 0.67735091
Iteration 14, loss = 0.67597176
Iteration 15, loss = 0.67466008
Iteration 16, loss = 0.67339737
Iteration 17, loss = 0.67215659
Iteration 18, loss = 0.67093405
Iteration 19, loss = 0.66975747
Iteration 20, loss = 0.66857767
Iteration 21, loss = 0.66739480
Iteration 22, loss = 0.66621138
Iteration 23, loss = 0.66505532
Iteration 24, loss = 0.66395067
Iteration 25, loss = 0.66282336
Iteration 26, loss = 0.66170419
Iteration 27, loss = 0.66060542
Iteration 28, loss = 0.65950231
Iteration 29, loss = 0.65840347
Iteration 30, loss = 0.65728961
Iteration 31, loss = 0.65617166
Iteration 32, los

Iteration 533, loss = 0.09502770
Iteration 534, loss = 0.09459670
Iteration 535, loss = 0.09416858
Iteration 536, loss = 0.09374063
Iteration 537, loss = 0.09332152
Iteration 538, loss = 0.09290576
Iteration 539, loss = 0.09249749
Iteration 540, loss = 0.09209135
Iteration 541, loss = 0.09168905
Iteration 542, loss = 0.09128563
Iteration 543, loss = 0.09087185
Iteration 544, loss = 0.09047198
Iteration 545, loss = 0.09007372
Iteration 546, loss = 0.08967536
Iteration 547, loss = 0.08928745
Iteration 548, loss = 0.08889216
Iteration 549, loss = 0.08851427
Iteration 550, loss = 0.08813152
Iteration 551, loss = 0.08774658
Iteration 552, loss = 0.08735687
Iteration 553, loss = 0.08696591
Iteration 554, loss = 0.08659707
Iteration 555, loss = 0.08622525
Iteration 556, loss = 0.08583965
Iteration 557, loss = 0.08547189
Iteration 558, loss = 0.08510900
Iteration 559, loss = 0.08474293
Iteration 560, loss = 0.08437598
Iteration 561, loss = 0.08400929
Iteration 562, loss = 0.08365039
Iteration 

MLPClassifier(max_iter=1000, verbose=True)

In [14]:
model_mlp.predict( x_data ) # 4x2 2x100   4x100  100x1 = 4x1

array([0, 1, 1, 0])

In [23]:
model_mlp.score( x_data, y_data)

1.0

In [16]:
len( model_mlp.coefs_ )

2

In [18]:
model_mlp.coefs_[0].shape # 2x100

(2, 100)

In [19]:
model_mlp.coefs_[1].shape #100x1 

(100, 1)

In [21]:
model_mlp.intercepts_[0].shape

(100,)

In [22]:
model_mlp.intercepts_[1].shape

(1,)

In [24]:
model_mlp1 = MLPClassifier( hidden_layer_sizes=(100,50), max_iter=1000 ,verbose=True)
model_mlp1.fit( x_data, y_data )

Iteration 1, loss = 0.70217362
Iteration 2, loss = 0.69537637
Iteration 3, loss = 0.68906465
Iteration 4, loss = 0.68309226
Iteration 5, loss = 0.67779556
Iteration 6, loss = 0.67259985
Iteration 7, loss = 0.66797556
Iteration 8, loss = 0.66417529
Iteration 9, loss = 0.66054199
Iteration 10, loss = 0.65693636
Iteration 11, loss = 0.65332473
Iteration 12, loss = 0.64990460
Iteration 13, loss = 0.64694893
Iteration 14, loss = 0.64403679
Iteration 15, loss = 0.64110794
Iteration 16, loss = 0.63814645
Iteration 17, loss = 0.63522297
Iteration 18, loss = 0.63235035
Iteration 19, loss = 0.62936062
Iteration 20, loss = 0.62633499
Iteration 21, loss = 0.62340082
Iteration 22, loss = 0.62041995
Iteration 23, loss = 0.61738668
Iteration 24, loss = 0.61417825
Iteration 25, loss = 0.61097891
Iteration 26, loss = 0.60778057
Iteration 27, loss = 0.60447438
Iteration 28, loss = 0.60121051
Iteration 29, loss = 0.59792542
Iteration 30, loss = 0.59468718
Iteration 31, loss = 0.59165453
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, verbose=True)

In [29]:
model_mlp1.predict( x_data) #4x2 2x100 = 4x100 100x50 = 4x50 50x1 = 4x1

array([0, 1, 1, 0])

In [25]:
len( model_mlp1.coefs_ )

3

In [26]:
model_mlp1.coefs_[0].shape 

(2, 100)

In [27]:
model_mlp1.coefs_[1].shape 

(100, 50)

In [28]:
model_mlp1.coefs_[2].shape 

(50, 1)

In [31]:
model_mlp2 = MLPClassifier( hidden_layer_sizes=(64,32,16), 
                           max_iter=1000 ,verbose=True)
model_mlp2.fit( x_data, y_data )

Iteration 1, loss = 0.71876693
Iteration 2, loss = 0.71346115
Iteration 3, loss = 0.70955802
Iteration 4, loss = 0.70639993
Iteration 5, loss = 0.70303083
Iteration 6, loss = 0.69976576
Iteration 7, loss = 0.69675719
Iteration 8, loss = 0.69366913
Iteration 9, loss = 0.69051938
Iteration 10, loss = 0.68741031
Iteration 11, loss = 0.68438339
Iteration 12, loss = 0.68211264
Iteration 13, loss = 0.67970727
Iteration 14, loss = 0.67717782
Iteration 15, loss = 0.67464454
Iteration 16, loss = 0.67225888
Iteration 17, loss = 0.66974165
Iteration 18, loss = 0.66711494
Iteration 19, loss = 0.66444714
Iteration 20, loss = 0.66176164
Iteration 21, loss = 0.65926432
Iteration 22, loss = 0.65677943
Iteration 23, loss = 0.65438387
Iteration 24, loss = 0.65190198
Iteration 25, loss = 0.64929731
Iteration 26, loss = 0.64653555
Iteration 27, loss = 0.64384103
Iteration 28, loss = 0.64108366
Iteration 29, loss = 0.63838417
Iteration 30, loss = 0.63560963
Iteration 31, loss = 0.63278140
Iteration 32, los

C:\Users\TFG5076XG\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000, verbose=True)

In [32]:
len( model_mlp2.coefs_ )

4

In [33]:
model_mlp2.coefs_[0].shape

(2, 64)

In [34]:
model_mlp2.coefs_[1].shape

(64, 32)

In [35]:
model_mlp2.coefs_[2].shape

(32, 16)

In [36]:
model_mlp2.coefs_[3].shape

(16, 1)