In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
irisDF=pd.DataFrame(iris['data'])
irisDF.columns=iris['feature_names']
irisDF['species'] = iris['target']
irisDF.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [5]:
x_data = irisDF.iloc[:,:-1].values
x_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y_data=pd.get_dummies(irisDF['species']).values
y_data
# 0 -> 1, 0, 0
# 1 -> 0, 1, 0
# 2 -> 0, 0, 1

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [7]:
x = tf.constant( x_data, tf.float32)
y = tf.constant( y_data, tf.float32)

In [8]:
type(x_data)

numpy.ndarray

In [9]:
initX=tf.initializers.GlorotUniform()


w1=tf.Variable(initX(shape=[4,64]))
b1=tf.Variable(initX(shape=[64]))

w2=tf.Variable(initX(shape=[64,3]))
b2=tf.Variable(initX(shape=[3]))

In [10]:
def compute_loss():
    z1=tf.matmul(x,w1)+b1
    hx1=tf.nn.softmax(z1)
    
    z=tf.matmul(hx1, w2)+b2
    cost_i = tf.nn.softmax_cross_entropy_with_logits( labels=y, logits=z )
    cost = tf.reduce_mean( cost_i)
    return cost

In [11]:
optimizer=Adam(learning_rate=0.1)
for i in range(2000):
    optimizer.minimize(compute_loss, var_list=[w1,w2, b1, b2])
    print(i, compute_loss().numpy())

0 1.086241
1 1.0044819
2 0.9233554
3 0.8463071
4 0.78164333
5 0.7254648
6 0.67980736
7 0.64273036
8 0.61178905
9 0.5859735
10 0.5644213
11 0.54637223
12 0.5313032
13 0.51883334
14 0.5086183
15 0.5003164
16 0.4936003
17 0.48817503
18 0.4837855
19 0.48022136
20 0.47731873
21 0.47495335
22 0.47302714
23 0.47145772
24 0.47017434
25 0.469118
26 0.4682428
27 0.46751463
28 0.46690887
29 0.46640405
30 0.46598026
31 0.46562043
32 0.46531254
33 0.46504897
34 0.4648234
35 0.46462876
36 0.46445853
37 0.46430868
38 0.4641771
39 0.46406165
40 0.46395966
41 0.46386835
42 0.46378595
43 0.46371236
44 0.4636466
45 0.46358714
46 0.4635328
47 0.46348312
48 0.463438
49 0.46339706
50 0.46335918
51 0.46332413
52 0.46329167
53 0.4632618
54 0.46323416
55 0.46320826
56 0.4631839
57 0.4631612
58 0.46314
59 0.46312016
60 0.46310115
61 0.46308324
62 0.46306637
63 0.4630504
64 0.46303508
65 0.46302053
66 0.4630066
67 0.46299332
68 0.46298054
69 0.4629682
70 0.4629565
71 0.4629451
72 0.46293423
73 0.4629236
74 0.462

561 0.05400566
562 0.05396322
563 0.053920943
564 0.053879008
565 0.053837225
566 0.0537956
567 0.053754304
568 0.05371308
569 0.05367241
570 0.05363175
571 0.05359173
572 0.053552475
573 0.053514775
574 0.053481113
575 0.053456783
576 0.05345485
577 0.053518996
578 0.053726036
579 0.054454453
580 0.055999324
581 0.062154196
582 0.069103196
583 0.114723384
584 0.15364029
585 0.71051514
586 0.7626387
587 1.5213066
588 1.9660264
589 1.7312535
590 1.046675
591 0.069947876
592 1.9437103
593 0.21371679
594 0.6643533
595 1.1773033
596 0.91504884
597 0.4833983
598 0.4857912
599 0.5327146
600 0.55208784
601 0.5274899
602 0.4634963
603 0.37616158
604 0.29645818
605 0.24135007
606 0.19883169
607 0.16960226
608 0.17306659
609 0.21219276
610 0.24699967
611 0.25005877
612 0.25810987
613 0.28486833
614 0.28000757
615 0.26057982
616 0.26019385
617 0.24953698
618 0.22117157
619 0.20231116
620 0.19079003
621 0.17228018
622 0.1522046
623 0.13920893
624 0.13145474
625 0.125223
626 0.11981285
627 0.116273

1113 0.046422075
1114 0.04640782
1115 0.04639371
1116 0.046379685
1117 0.04636559
1118 0.04635167
1119 0.046337776
1120 0.046323787
1121 0.046310138
1122 0.04629649
1123 0.046282664
1124 0.046269104
1125 0.0462555
1126 0.046242032
1127 0.04622855
1128 0.046215132
1129 0.046201818
1130 0.046188544
1131 0.046175208
1132 0.046162073
1133 0.046148974
1134 0.04613587
1135 0.04612283
1136 0.046109892
1137 0.046096873
1138 0.046083994
1139 0.046071302
1140 0.046058454
1141 0.046045743
1142 0.046033014
1143 0.046020426
1144 0.046007894
1145 0.045995284
1146 0.04598288
1147 0.04597037
1148 0.04595805
1149 0.04594569
1150 0.045933485
1151 0.04592114
1152 0.045908965
1153 0.045896843
1154 0.04588479
1155 0.045872737
1156 0.04586071
1157 0.045848705
1158 0.04583678
1159 0.045824952
1160 0.045813024
1161 0.045801282
1162 0.04578954
1163 0.045777906
1164 0.045766257
1165 0.045754615
1166 0.04574308
1167 0.045731544
1168 0.045720197
1169 0.04570858
1170 0.045697298
1171 0.04568593
1172 0.045674708
11

1646 0.044648234
1647 0.04439848
1648 0.04479978
1649 0.04464241
1650 0.045283955
1651 0.04510837
1652 0.04603763
1653 0.045674488
1654 0.046812784
1655 0.046082728
1656 0.04716055
1657 0.04608738
1658 0.04684581
1659 0.045712437
1660 0.04615026
1661 0.045214303
1662 0.045494307
1663 0.04481893
1664 0.045081023
1665 0.044611495
1666 0.04493434
1667 0.04459239
1668 0.045022946
1669 0.044734836
1670 0.04530639
1671 0.04499509
1672 0.0457122
1673 0.04529215
1674 0.046103265
1675 0.04550952
1676 0.04630454
1677 0.045548927
1678 0.046220683
1679 0.04540373
1680 0.04592303
1681 0.045162152
1682 0.045575656
1683 0.044933192
1684 0.045310378
1685 0.044787206
1686 0.04518516
1687 0.04474898
1688 0.045206513
1689 0.04481203
1690 0.04535116
1691 0.044948976
1692 0.04557018
1693 0.04511136
1694 0.045787547
1695 0.045240108
1696 0.045920078
1697 0.045284867
1698 0.04591515
1699 0.045233164
1700 0.045788452
1701 0.045116678
1702 0.04560771
1703 0.044987865
1704 0.04544651
1705 0.044892073
1706 0.045

In [12]:
def hxfn(xdata):
    xd=tf.constant(xdata, tf.float32)
    z1=tf.matmul(xd,w1)+b1
    hx1=tf.nn.softmax(z1)
    z=tf.matmul(hx1,w2)+b2
    hx = tf.nn.softmax( z )
    return (hx.numpy()>0.5)+0

In [13]:
pred=[[5.1, 3.5, 1.4, 0.2]]

In [14]:
hxfn(pred)

array([[1, 0, 0]])

In [15]:
hxfn(x_data)

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
accuracy = accuracy_score(y_data, hxfn(x_data))
accuracy

0.9866666666666667

In [18]:
dense1 = Dense( units=64, input_dim=4 ,activation="softmax") # w:4x64, b:64
dense2 = Dense( units=3, input_dim=64 ,activation="softmax") # w:64x1, b:3
model = Sequential( [dense1, dense2])
model.compile( loss="categorical_crossentropy" ,optimizer=Adam(0.1), metrics=['acc'] )
h = model.fit( x_data, y_data, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.0111 - acc: 0.5800
Epoch 2/1000
5/5 [==============================] - 0s 748us/step - loss: 0.7499 - acc: 0.6400
Epoch 3/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.5823 - acc: 0.7000
Epoch 4/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.5146 - acc: 0.7000
Epoch 5/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.4858 - acc: 0.6667
Epoch 6/1000
5/5 [==============================] - 0s 997us/step - loss: 0.4736 - acc: 0.7400
Epoch 7/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.4481 - acc: 0.9200
Epoch 8/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.4355 - acc: 0.7933
Epoch 9/1000
5/5 [==============================] - 0s 997us/step - loss: 0.3792 - acc: 0.8800
Epoch 10/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.2676 - acc: 0.9800
Epoch 11/1000
5/5 [==============================] - 0s 2ms/ste

5/5 [==============================] - 0s 1ms/step - loss: 0.0887 - acc: 0.9733
Epoch 88/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0599 - acc: 0.9800
Epoch 89/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0860 - acc: 0.9600
Epoch 90/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0680 - acc: 0.9733
Epoch 91/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0769 - acc: 0.9667
Epoch 92/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0582 - acc: 0.9733
Epoch 93/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0551 - acc: 0.9867
Epoch 94/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0739 - acc: 0.9667
Epoch 95/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0606 - acc: 0.9800
Epoch 96/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0707 - acc: 0.9733
Epoch 97/1000
5/5 [==============================] - 0s 1ms/step - loss:

5/5 [==============================] - 0s 997us/step - loss: 0.0535 - acc: 0.9800
Epoch 173/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0711 - acc: 0.9733
Epoch 174/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0716 - acc: 0.9800
Epoch 175/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0525 - acc: 0.9867
Epoch 176/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0480 - acc: 0.9800
Epoch 177/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0534 - acc: 0.9800
Epoch 178/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0703 - acc: 0.9667
Epoch 179/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0551 - acc: 0.9733
Epoch 180/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0499 - acc: 0.9800
Epoch 181/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0739 - acc: 0.9800
Epoch 182/1000
5/5 [=========================

Epoch 257/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0573 - acc: 0.9733
Epoch 258/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0445 - acc: 0.9800
Epoch 259/1000
5/5 [==============================] - 0s 997us/step - loss: 0.1218 - acc: 0.9467
Epoch 260/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1190 - acc: 0.9600
Epoch 261/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1342 - acc: 0.9467
Epoch 262/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0702 - acc: 0.9800
Epoch 263/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1435 - acc: 0.9467
Epoch 264/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1883 - acc: 0.9200
Epoch 265/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.2180 - acc: 0.9400
Epoch 266/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1975 - acc: 0.9133
Epoch 267/1000
5/5 [============================

5/5 [==============================] - 0s 748us/step - loss: 0.0589 - acc: 0.9800
Epoch 342/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0801 - acc: 0.9600
Epoch 343/1000
5/5 [==============================] - 0s 748us/step - loss: 0.2011 - acc: 0.9333
Epoch 344/1000
5/5 [==============================] - 0s 747us/step - loss: 0.0616 - acc: 0.9800
Epoch 345/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0894 - acc: 0.9800
Epoch 346/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1235 - acc: 0.9600
Epoch 347/1000
5/5 [==============================] - 0s 998us/step - loss: 0.1028 - acc: 0.9533
Epoch 348/1000
5/5 [==============================] - 0s 750us/step - loss: 0.1058 - acc: 0.9667
Epoch 349/1000
5/5 [==============================] - 0s 748us/step - loss: 0.1069 - acc: 0.9667
Epoch 350/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0743 - acc: 0.9667
Epoch 351/1000
5/5 [=============================

5/5 [==============================] - 0s 1ms/step - loss: 0.0536 - acc: 0.9867
Epoch 426/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0523 - acc: 0.9867
Epoch 427/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0591 - acc: 0.9733
Epoch 428/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0612 - acc: 0.9667
Epoch 429/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0585 - acc: 0.9800
Epoch 430/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0645 - acc: 0.9800
Epoch 431/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0523 - acc: 0.9800
Epoch 432/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0724 - acc: 0.9667
Epoch 433/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1097 - acc: 0.9533
Epoch 434/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0840 - acc: 0.9667
Epoch 435/1000
5/5 [==============================]

5/5 [==============================] - 0s 1ms/step - loss: 0.2064 - acc: 0.9000
Epoch 511/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0726 - acc: 0.9667
Epoch 512/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0561 - acc: 0.9800
Epoch 513/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0583 - acc: 0.9733
Epoch 514/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0554 - acc: 0.9800
Epoch 515/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0639 - acc: 0.9667
Epoch 516/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1242 - acc: 0.9600
Epoch 517/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0599 - acc: 0.9667
Epoch 518/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.1015 - acc: 0.9667
Epoch 519/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0613 - acc: 0.9733
Epoch 520/1000
5/5 [==============================] - 0s 998us/

5/5 [==============================] - 0s 748us/step - loss: 0.0421 - acc: 0.9867
Epoch 596/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0615 - acc: 0.9800
Epoch 597/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0678 - acc: 0.9733
Epoch 598/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0600 - acc: 0.9800
Epoch 599/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0479 - acc: 0.9800
Epoch 600/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0575 - acc: 0.9800
Epoch 601/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0761 - acc: 0.9733
Epoch 602/1000
5/5 [==============================] - 0s 996us/step - loss: 0.0565 - acc: 0.9800
Epoch 603/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0473 - acc: 0.9800
Epoch 604/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0667 - acc: 0.9733
Epoch 605/1000
5/5 [=========================

5/5 [==============================] - 0s 748us/step - loss: 0.0690 - acc: 0.9800
Epoch 680/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0746 - acc: 0.9667
Epoch 681/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0887 - acc: 0.9667
Epoch 682/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0757 - acc: 0.9800
Epoch 683/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0793 - acc: 0.9733
Epoch 684/1000
5/5 [==============================] - 0s 1000us/step - loss: 0.0713 - acc: 0.9733
Epoch 685/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0615 - acc: 0.9800
Epoch 686/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0630 - acc: 0.9667
Epoch 687/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0761 - acc: 0.9733
Epoch 688/1000
5/5 [==============================] - 0s 747us/step - loss: 0.0600 - acc: 0.9800
Epoch 689/1000
5/5 [========================

5/5 [==============================] - 0s 998us/step - loss: 0.0560 - acc: 0.9800
Epoch 765/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0650 - acc: 0.9800
Epoch 766/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0529 - acc: 0.9800
Epoch 767/1000
5/5 [==============================] - 0s 499us/step - loss: 0.0490 - acc: 0.9800
Epoch 768/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0513 - acc: 0.9800
Epoch 769/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0556 - acc: 0.9800
Epoch 770/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0504 - acc: 0.9867
Epoch 771/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0562 - acc: 0.9800
Epoch 772/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0471 - acc: 0.9800
Epoch 773/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0704 - acc: 0.9733
Epoch 774/1000
5/5 [===========================

5/5 [==============================] - 0s 1ms/step - loss: 0.0616 - acc: 0.9667
Epoch 849/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0685 - acc: 0.9733
Epoch 850/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0470 - acc: 0.9867
Epoch 851/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0528 - acc: 0.9800
Epoch 852/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.0468 - acc: 0.9800
Epoch 853/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0617 - acc: 0.9667
Epoch 854/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0646 - acc: 0.9733
Epoch 855/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0432 - acc: 0.9800
Epoch 856/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0720 - acc: 0.9733
Epoch 857/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0934 - acc: 0.9733
Epoch 858/1000
5/5 [==============================] - 0s 1ms/step

5/5 [==============================] - 0s 1ms/step - loss: 0.0484 - acc: 0.9867
Epoch 934/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0609 - acc: 0.9800
Epoch 935/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0598 - acc: 0.9800
Epoch 936/1000
5/5 [==============================] - 0s 1ms/step - loss: 0.0560 - acc: 0.9800
Epoch 937/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0655 - acc: 0.9800
Epoch 938/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0547 - acc: 0.9733
Epoch 939/1000
5/5 [==============================] - 0s 748us/step - loss: 0.0506 - acc: 0.9733
Epoch 940/1000
5/5 [==============================] - 0s 997us/step - loss: 0.0735 - acc: 0.9667
Epoch 941/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0945 - acc: 0.9667
Epoch 942/1000
5/5 [==============================] - 0s 998us/step - loss: 0.0852 - acc: 0.9800
Epoch 943/1000
5/5 [==============================] -

In [19]:
model.predict(pred)

array([[9.9999630e-01, 3.4285670e-06, 2.0049077e-07]], dtype=float32)

In [20]:
(model.predict(pred)>0.5)+0

array([[1, 0, 0]])

In [21]:
accuracy = accuracy_score([y_data[0]], (model.predict(pred)>0.5)+0)
accuracy

1.0