In [159]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

In [160]:
df = pd.read_csv('../ddata/titanic.csv')

In [122]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [11]:
# df = temp[['Fare','Sex','Pclass','Age','Survived']]

# age 결측치를 평균으로 채우고 학습

In [161]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [162]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

In [163]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [83]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [164]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [165]:
df.sample(1)

PassengerId  Survived  Pclass                         Name   Sex   Age  \
73           74         0       3  Chronopoulos, Mr. Apostolos  male  26.0   

    SibSp  Parch Ticket     Fare Cabin Embarked  
73      1      0   2680  14.4542   NaN        C

# 문제
feature(탑승금액, 성별, 탑승등급 ,age) ,label(survived)
30달러, 여성, 1등급, 25 인경우 생사를 예측하시요(텐서, 케라스)

In [166]:
df = df[['Fare','Sex','Pclass','Age','Survived']].copy()
df.head(3)

Fare     Sex  Pclass   Age  Survived
0   7.2500    male       3  22.0         0
1  71.2833  female       1  38.0         1
2   7.9250  female       3  26.0         1

```
df[['탑승금액','성별','탑승등급' ,'Age']]

[30,female.1,25]
```

# 성별을 0과 1로 라벨인코딩

In [167]:
from sklearn.preprocessing import LabelEncoder
# male => 0    female => 1

# 객체 생성
encoder = LabelEncoder()
encoder.fit(df['Sex'])
df['Sex'] = encoder.transform(df['Sex'])

# Pclass 원핫 인코딩 

In [168]:
from tensorflow.keras.utils import to_categorical

OHE = pd.DataFrame(data = to_categorical(df['Pclass'].values),columns=['p1','p2','p3','p4'] )

In [169]:
df = pd.concat((df,OHE),axis=1)

In [170]:
del(df['Pclass'])

In [190]:
df.head(3)

Fare  Sex   Age  Survived   p1   p2   p3   p4
0   7.2500    1  22.0         0  0.0  0.0  0.0  1.0
1  71.2833    0  38.0         1  0.0  1.0  0.0  0.0
2   7.9250    0  26.0         1  0.0  0.0  0.0  1.0

# 스케일링

In [191]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()
df[['Fare','Sex',  'Age','p1','p2','p3','p4' ]] = scaler.fit_transform(df[['Fare','Sex',  'Age','p1','p2','p3','p4' ]])

In [ ]:
#  요금, 성별,pclass, 나이

In [192]:
xdf = df.iloc[:,[0,1,4,5,6,7,2]]
xdf

Fare  Sex   p1   p2   p3   p4       Age
0    0.014151  1.0  0.0  0.0  0.0  1.0  0.271174
1    0.139136  0.0  0.0  1.0  0.0  0.0  0.472229
2    0.015469  0.0  0.0  0.0  0.0  1.0  0.321438
3    0.103644  0.0  0.0  1.0  0.0  0.0  0.434531
4    0.015713  1.0  0.0  0.0  0.0  1.0  0.434531
..        ...  ...  ...  ...  ...  ...       ...
886  0.025374  1.0  0.0  0.0  1.0  0.0  0.334004
887  0.058556  0.0  0.0  1.0  0.0  0.0  0.233476
888  0.045771  0.0  0.0  0.0  0.0  1.0  0.367921
889  0.058556  1.0  0.0  1.0  0.0  0.0  0.321438
890  0.015127  1.0  0.0  0.0  0.0  1.0  0.396833

[891 rows x 7 columns]

In [193]:
ydf = df.iloc[:,[3]]
ydf

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [194]:

x_data =xdf.values
y_data = ydf.values

In [195]:
x_data.shape, y_data.shape

((891, 7), (891, 1))

In [196]:
x_data[0] # 요금, 성별,pclass, 나이, p1,p2,p3,p4

array([0.01415106, 1.        , 0.        , 0.        , 0.        ,
       1.        , 0.27117366])

# 훈련 검증 분리

In [197]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x_data, y_data, test_size=0.3, stratify=y_data)

## 텐서

In [198]:
x_train.shape, y_train.shape

((623, 7), (623, 1))

In [199]:
x = tf.constant(x_train, tf.float32)
y = tf.constant(y_train, tf.float32)
initX = tf.initializers.GlorotUniform()
w = tf.Variable( tf.random.uniform( [7,1] ) )
b = tf.Variable( tf.random.uniform( [1] ) )

In [200]:
# cost 함수
def compute_loss():
    z = tf.matmul(x,w) + b
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits( labels=y, logits=z)  
    cost = tf.reduce_mean( cost_i )
    return cost

In [201]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b])
    print(i, 'cost:', compute_loss().numpy() )

0 cost: 0.98498446
1 cost: 0.8711236
2 cost: 0.77860063
3 cost: 0.7085437
4 cost: 0.65949076
5 cost: 0.6278681
6 cost: 0.6093502
7 cost: 0.59963655
8 cost: 0.5949436
9 cost: 0.59233207
10 cost: 0.58979905
11 cost: 0.58618426
12 cost: 0.5809968
13 cost: 0.574226
14 cost: 0.5661743
15 cost: 0.5573193
16 cost: 0.5482074
17 cost: 0.53937155
18 cost: 0.5312694
19 cost: 0.52424115
20 cost: 0.5184847
21 cost: 0.5140496
22 cost: 0.51084846
23 cost: 0.50868285
24 cost: 0.50728023
25 cost: 0.5063347
26 cost: 0.50554776
27 cost: 0.5046614
28 cost: 0.50348306
29 cost: 0.50189716
30 cost: 0.49986744
31 cost: 0.49742892
32 cost: 0.49467206
33 cost: 0.49172416
34 cost: 0.48872766
35 cost: 0.48582038
36 cost: 0.48311928
37 cost: 0.48070842
38 cost: 0.47863337
39 cost: 0.476901
40 cost: 0.47548512
41 cost: 0.47433507
42 cost: 0.47338653
43 cost: 0.47257262
44 cost: 0.47183332
45 cost: 0.47112194
46 cost: 0.47040868
47 cost: 0.4696815
48 cost: 0.4689431
49 cost: 0.46820763
50 cost: 0.46749488
51 cost: 0

428 cost: 0.4541213
429 cost: 0.4541213
430 cost: 0.4541213
431 cost: 0.45412126
432 cost: 0.45412135
433 cost: 0.45412126
434 cost: 0.45412135
435 cost: 0.4541213
436 cost: 0.45412126
437 cost: 0.45412126
438 cost: 0.4541213
439 cost: 0.4541213
440 cost: 0.45412126
441 cost: 0.4541213
442 cost: 0.45412126
443 cost: 0.45412126
444 cost: 0.45412126
445 cost: 0.4541213
446 cost: 0.45412126
447 cost: 0.4541213
448 cost: 0.45412126
449 cost: 0.4541213
450 cost: 0.45412135
451 cost: 0.45412126
452 cost: 0.45412126
453 cost: 0.4541213
454 cost: 0.45412126
455 cost: 0.45412135
456 cost: 0.45412126
457 cost: 0.4541213
458 cost: 0.4541213
459 cost: 0.4541213
460 cost: 0.45412126
461 cost: 0.45412126
462 cost: 0.45412126
463 cost: 0.4541212
464 cost: 0.4541213
465 cost: 0.4541213
466 cost: 0.45412126
467 cost: 0.45412126
468 cost: 0.45412126
469 cost: 0.45412126
470 cost: 0.4541213
471 cost: 0.4541212
472 cost: 0.45412126
473 cost: 0.4541213
474 cost: 0.4541213
475 cost: 0.45412126
476 cost: 0.4

828 cost: 0.45412126
829 cost: 0.45412126
830 cost: 0.45412126
831 cost: 0.45412126
832 cost: 0.45412126
833 cost: 0.45412126
834 cost: 0.45412126
835 cost: 0.45412126
836 cost: 0.45412126
837 cost: 0.45412126
838 cost: 0.45412126
839 cost: 0.45412126
840 cost: 0.45412126
841 cost: 0.45412126
842 cost: 0.45412126
843 cost: 0.45412126
844 cost: 0.45412126
845 cost: 0.45412126
846 cost: 0.45412126
847 cost: 0.45412126
848 cost: 0.45412126
849 cost: 0.45412126
850 cost: 0.45412126
851 cost: 0.45412126
852 cost: 0.45412126
853 cost: 0.45412126
854 cost: 0.45412126
855 cost: 0.45412126
856 cost: 0.45412126
857 cost: 0.45412126
858 cost: 0.45412126
859 cost: 0.45412126
860 cost: 0.45412126
861 cost: 0.45412126
862 cost: 0.45412126
863 cost: 0.45412126
864 cost: 0.45412126
865 cost: 0.45412126
866 cost: 0.45412126
867 cost: 0.45412126
868 cost: 0.45412126
869 cost: 0.45412126
870 cost: 0.45412126
871 cost: 0.45412126
872 cost: 0.45412126
873 cost: 0.45412126
874 cost: 0.45412126
875 cost: 0.4

예측함수

In [155]:
x_data[0] # 요금, 성별,pclass, 나이, p1,p2,p3,p4

array([0.01415106, 1.        , 3.        , 0.27117366, 0.        ,
       0.        , 0.        , 1.        ])

In [202]:
# 예측함수
def hxfn(xdata):
    xd = tf.constant(xdata, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return (hx.numpy()>0.5) +0

In [203]:
hxfn(     scaler.transform( [    [30,1,25,1,0,0,0,]]       )        )

array([[1]])

In [204]:
# 예측함수
def hxfn2(xdata):
    xd = tf.constant(xdata, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return hx.numpy()

In [205]:
hxfn2( scaler.transform( [    [30,1,25,1,0,0,0,]]       )        )

array([[0.6395646]], dtype=float32)

## 케라스

In [212]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
dense = Dense(units = 1, input_dim =7 ) # w : 3x1   b : 1   초기값
model = Sequential([dense])
model.compile(loss='mse',optimizer=Adam(0.1), metrics=['acc'])
# n행 3열
h = model.fit(x_train, y_train, epochs=500) # x값을 행렬로 주어야함


Epoch 1/500
20/20 [==============================] - 0s 578us/step - loss: 0.2881 - acc: 0.6148
Epoch 2/500
20/20 [==============================] - 0s 525us/step - loss: 0.1751 - acc: 0.7689
Epoch 3/500
20/20 [==============================] - 0s 525us/step - loss: 0.1634 - acc: 0.7705
Epoch 4/500
20/20 [==============================] - 0s 525us/step - loss: 0.1529 - acc: 0.7897
Epoch 5/500
20/20 [==============================] - 0s 525us/step - loss: 0.1540 - acc: 0.7913
Epoch 6/500
20/20 [==============================] - 0s 577us/step - loss: 0.1542 - acc: 0.7961
Epoch 7/500
20/20 [==============================] - 0s 472us/step - loss: 0.1547 - acc: 0.7801
Epoch 8/500
20/20 [==============================] - 0s 525us/step - loss: 0.1638 - acc: 0.7737
Epoch 9/500
20/20 [==============================] - 0s 525us/step - loss: 0.1497 - acc: 0.7978
Epoch 10/500
20/20 [==============================] - 0s 535us/step - loss: 0.1536 - acc: 0.7978
Epoch 11/500
20/20 [===================

20/20 [==============================] - 0s 472us/step - loss: 0.1592 - acc: 0.7801
Epoch 86/500
20/20 [==============================] - 0s 525us/step - loss: 0.1601 - acc: 0.7721
Epoch 87/500
20/20 [==============================] - 0s 525us/step - loss: 0.1517 - acc: 0.7865
Epoch 88/500
20/20 [==============================] - 0s 525us/step - loss: 0.1554 - acc: 0.7865
Epoch 89/500
20/20 [==============================] - 0s 525us/step - loss: 0.1559 - acc: 0.7737
Epoch 90/500
20/20 [==============================] - 0s 472us/step - loss: 0.1529 - acc: 0.7881
Epoch 91/500
20/20 [==============================] - 0s 472us/step - loss: 0.1540 - acc: 0.7945
Epoch 92/500
20/20 [==============================] - 0s 472us/step - loss: 0.1488 - acc: 0.7881
Epoch 93/500
20/20 [==============================] - 0s 472us/step - loss: 0.1485 - acc: 0.7897
Epoch 94/500
20/20 [==============================] - 0s 525us/step - loss: 0.1519 - acc: 0.7801
Epoch 95/500
20/20 [=======================

20/20 [==============================] - 0s 525us/step - loss: 0.1532 - acc: 0.7881
Epoch 169/500
20/20 [==============================] - 0s 472us/step - loss: 0.1541 - acc: 0.7801
Epoch 170/500
20/20 [==============================] - 0s 525us/step - loss: 0.1627 - acc: 0.7785
Epoch 171/500
20/20 [==============================] - 0s 525us/step - loss: 0.1574 - acc: 0.7753
Epoch 172/500
20/20 [==============================] - 0s 472us/step - loss: 0.1560 - acc: 0.7849
Epoch 173/500
20/20 [==============================] - 0s 525us/step - loss: 0.1555 - acc: 0.7785
Epoch 174/500
20/20 [==============================] - 0s 472us/step - loss: 0.1514 - acc: 0.7881
Epoch 175/500
20/20 [==============================] - 0s 525us/step - loss: 0.1556 - acc: 0.7817
Epoch 176/500
20/20 [==============================] - 0s 472us/step - loss: 0.1663 - acc: 0.7705
Epoch 177/500
20/20 [==============================] - 0s 525us/step - loss: 0.1577 - acc: 0.7961
Epoch 178/500
20/20 [=============

20/20 [==============================] - 0s 472us/step - loss: 0.1521 - acc: 0.7849
Epoch 252/500
20/20 [==============================] - 0s 472us/step - loss: 0.1544 - acc: 0.7897
Epoch 253/500
20/20 [==============================] - 0s 525us/step - loss: 0.1528 - acc: 0.7913
Epoch 254/500
20/20 [==============================] - 0s 525us/step - loss: 0.1539 - acc: 0.7785
Epoch 255/500
20/20 [==============================] - 0s 472us/step - loss: 0.1586 - acc: 0.7817
Epoch 256/500
20/20 [==============================] - 0s 525us/step - loss: 0.1612 - acc: 0.7801
Epoch 257/500
20/20 [==============================] - 0s 525us/step - loss: 0.1587 - acc: 0.7657
Epoch 258/500
20/20 [==============================] - 0s 472us/step - loss: 0.1509 - acc: 0.7865
Epoch 259/500
20/20 [==============================] - 0s 525us/step - loss: 0.1506 - acc: 0.7833
Epoch 260/500
20/20 [==============================] - 0s 525us/step - loss: 0.1548 - acc: 0.7929
Epoch 261/500
20/20 [=============

20/20 [==============================] - 0s 525us/step - loss: 0.1550 - acc: 0.7769
Epoch 335/500
20/20 [==============================] - 0s 472us/step - loss: 0.1547 - acc: 0.7945
Epoch 336/500
20/20 [==============================] - 0s 472us/step - loss: 0.1627 - acc: 0.7801
Epoch 337/500
20/20 [==============================] - 0s 525us/step - loss: 0.1525 - acc: 0.7865
Epoch 338/500
20/20 [==============================] - 0s 472us/step - loss: 0.1558 - acc: 0.7913
Epoch 339/500
20/20 [==============================] - 0s 472us/step - loss: 0.1498 - acc: 0.7961
Epoch 340/500
20/20 [==============================] - 0s 525us/step - loss: 0.1583 - acc: 0.7961
Epoch 341/500
20/20 [==============================] - 0s 472us/step - loss: 0.1625 - acc: 0.7769
Epoch 342/500
20/20 [==============================] - 0s 472us/step - loss: 0.1525 - acc: 0.7785
Epoch 343/500
20/20 [==============================] - 0s 525us/step - loss: 0.1512 - acc: 0.7961
Epoch 344/500
20/20 [=============

20/20 [==============================] - 0s 525us/step - loss: 0.1571 - acc: 0.7897
Epoch 418/500
20/20 [==============================] - 0s 525us/step - loss: 0.1604 - acc: 0.7978
Epoch 419/500
20/20 [==============================] - 0s 525us/step - loss: 0.1694 - acc: 0.7576
Epoch 420/500
20/20 [==============================] - 0s 525us/step - loss: 0.1581 - acc: 0.7833
Epoch 421/500
20/20 [==============================] - 0s 472us/step - loss: 0.1640 - acc: 0.7817
Epoch 422/500
20/20 [==============================] - 0s 525us/step - loss: 0.1571 - acc: 0.7881
Epoch 423/500
20/20 [==============================] - 0s 525us/step - loss: 0.1505 - acc: 0.7881
Epoch 424/500
20/20 [==============================] - 0s 472us/step - loss: 0.1562 - acc: 0.7817
Epoch 425/500
20/20 [==============================] - 0s 525us/step - loss: 0.1599 - acc: 0.7881
Epoch 426/500
20/20 [==============================] - 0s 525us/step - loss: 0.1591 - acc: 0.7961
Epoch 427/500
20/20 [=============

20/20 [==============================] - 0s 472us/step - loss: 0.1607 - acc: 0.7689


In [213]:
w,b = dense.get_weights()
w.shape,b.shape  # w = 3행 1열

((7, 1), (1,))

In [214]:
model.predict(  scaler.transform( [    [30,1,25,1,0,0,0,]]       )    )   

array([[0.60264677]], dtype=float32)

In [223]:
(model.predict(  scaler.transform( [ [30,1,25,1,0,0,0,]]   )  )   >0.5)+0

array([[1]])

In [245]:
confusion_matrix(y_test, model.predict(x_test))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [242]:
model.predict(x_data)

array([[ 0.12115842],
       [ 0.80102724],
       [ 0.5754249 ],
       [ 0.805024  ],
       [ 0.06357783],
       [ 0.08743608],
       [ 0.2478633 ],
       [ 0.21751589],
       [ 0.57262003],
       [ 0.86883354],
       [ 0.67809755],
       [ 0.68871474],
       [ 0.13049346],
       [ 0.05772251],
       [ 0.62892085],
       [ 0.6786673 ],
       [ 0.22167128],
       [ 0.31822488],
       [ 0.55832046],
       [ 0.5585616 ],
       [ 0.30128807],
       [ 0.29903847],
       [ 0.6245501 ],
       [ 0.35540396],
       [ 0.66251177],
       [ 0.53400385],
       [ 0.0867995 ],
       [ 0.51299024],
       [ 0.55889934],
       [ 0.08714569],
       [ 0.29785576],
       [ 0.8768959 ],
       [ 0.55883265],
       [ 0.1549946 ],
       [ 0.3794957 ],
       [ 0.30146676],
       [ 0.08680165],
       [ 0.12603241],
       [ 0.616314  ],
       [ 0.6306695 ],
       [ 0.5137704 ],
       [ 0.8061576 ],
       [ 0.08714569],
       [ 0.9238457 ],
       [ 0.60662854],
       [ 0

# 오차행렬

In [234]:
y_data.shape, pred.shape

((891, 1), (891, 1))

In [237]:

from sklearn.metrics import confusion_matrix

# 오차행렬
confusion_matrix(y_test, hxfn(x_test) )

array([[  4, 161],
       [  0, 103]], dtype=int64)

In [ ]:
m

In [241]:
confusion_matrix(y_test ,model.predict(x_test) )

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [238]:
from sklearn.metrics import accuracy_score
# 정확도
accuracy_score(y_test,hxfn(x_test))

0.39925373134328357

In [239]:
from sklearn.metrics import f1_score
f1_score(y_test, hxfn(x_test)  )

0.5613079019073569

In [240]:
model.predict(x_test)

array([[ 0.44338873],
       [ 0.13487494],
       [ 0.05051088],
       [ 0.8390859 ],
       [ 0.08714569],
       [ 0.08714569],
       [ 0.655177  ],
       [ 0.1964727 ],
       [ 0.08705759],
       [ 0.28746587],
       [ 0.5361147 ],
       [ 0.08708334],
       [ 0.07689643],
       [ 0.5754249 ],
       [ 0.12115842],
       [ 0.6786673 ],
       [ 0.43790388],
       [ 0.56797814],
       [ 0.6749571 ],
       [ 0.0631004 ],
       [ 0.4748611 ],
       [ 0.08714569],
       [ 0.3974774 ],
       [ 0.5907342 ],
       [ 0.12561947],
       [ 0.8696118 ],
       [ 0.80445623],
       [ 0.2180816 ],
       [ 0.11019278],
       [ 0.81618536],
       [ 0.44850245],
       [ 0.6108917 ],
       [ 0.55883265],
       [ 0.19961959],
       [ 0.17731434],
       [ 0.2737223 ],
       [ 0.894567  ],
       [ 0.08714569],
       [ 0.34320408],
       [ 0.5796449 ],
       [ 0.30063537],
       [ 0.3258047 ],
       [ 0.09913498],
       [ 0.09025377],
       [ 0.02336395],
       [ 0