In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

In [2]:
df = pd.read_csv('../ddata/titanic.csv')

In [3]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [4]:
# df = temp[['Fare','Sex','Pclass','Age','Survived']]

# age 결측치를 평균으로 채우고 학습

In [5]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [9]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
df.sample(1)

PassengerId  Survived  Pclass                           Name     Sex  \
345          346         1       2  Brown, Miss. Amelia "Mildred"  female   

      Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
345  24.0      0      0  248733  13.0   F33        S

# 문제
feature(탑승금액, 성별, 탑승등급 ,age) ,label(survived)
30달러, 여성, 1등급, 25 인경우 생사를 예측하시요(텐서, 케라스)

In [11]:
df = df[['Fare','Sex','Pclass','Age','Survived']].copy()
df.head(3)

Fare     Sex  Pclass   Age  Survived
0   7.2500    male       3  22.0         0
1  71.2833  female       1  38.0         1
2   7.9250  female       3  26.0         1

```
df[['탑승금액','성별','탑승등급' ,'Age']]

[30,female.1,25]
```

# 성별을 0과 1로 라벨인코딩

In [12]:
from sklearn.preprocessing import LabelEncoder
# male => 0    female => 1

# 객체 생성
encoder = LabelEncoder()
encoder.fit(df['Sex'])
df['Sex'] = encoder.transform(df['Sex'])

# Pclass 원핫 인코딩 

In [13]:
from tensorflow.keras.utils import to_categorical

OHE = pd.DataFrame(data = to_categorical(df['Pclass'].values),columns=['p1','p2','p3','p4'] )

In [14]:
df = pd.concat((df,OHE),axis=1)

In [15]:
del(df['Pclass'])

In [16]:
df.head(3)

Fare  Sex   Age  Survived   p1   p2   p3   p4
0   7.2500    1  22.0         0  0.0  0.0  0.0  1.0
1  71.2833    0  38.0         1  0.0  1.0  0.0  0.0
2   7.9250    0  26.0         1  0.0  0.0  0.0  1.0

# 스케일링

In [17]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()
df[['Fare','Sex',  'Age','p1','p2','p3','p4' ]] = scaler.fit_transform(df[['Fare','Sex',  'Age','p1','p2','p3','p4' ]])

In [18]:
#  요금, 성별,pclass, 나이

In [19]:
xdf = df.iloc[:,[0,1,4,5,6,7,2]]
xdf

Fare  Sex   p1   p2   p3   p4       Age
0    0.014151  1.0  0.0  0.0  0.0  1.0  0.271174
1    0.139136  0.0  0.0  1.0  0.0  0.0  0.472229
2    0.015469  0.0  0.0  0.0  0.0  1.0  0.321438
3    0.103644  0.0  0.0  1.0  0.0  0.0  0.434531
4    0.015713  1.0  0.0  0.0  0.0  1.0  0.434531
..        ...  ...  ...  ...  ...  ...       ...
886  0.025374  1.0  0.0  0.0  1.0  0.0  0.334004
887  0.058556  0.0  0.0  1.0  0.0  0.0  0.233476
888  0.045771  0.0  0.0  0.0  0.0  1.0  0.367921
889  0.058556  1.0  0.0  1.0  0.0  0.0  0.321438
890  0.015127  1.0  0.0  0.0  0.0  1.0  0.396833

[891 rows x 7 columns]

In [20]:
ydf = df.iloc[:,[3]]
ydf

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [21]:

x_data =xdf.values
y_data = ydf.values

In [22]:
x_data.shape, y_data.shape

((891, 7), (891, 1))

In [23]:
x_data[0] # 요금, 성별,pclass, 나이, p1,p2,p3,p4

array([0.01415106, 1.        , 0.        , 0.        , 0.        ,
       1.        , 0.27117366])

# 훈련 검증 분리

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x_data, y_data, test_size=0.3, stratify=y_data)

## 텐서

In [25]:
x_train.shape, y_train.shape

((623, 7), (623, 1))

In [26]:
x = tf.constant(x_train, tf.float32)
y = tf.constant(y_train, tf.float32)
initX = tf.initializers.GlorotUniform()
w = tf.Variable( tf.random.uniform( [7,1] ) )
b = tf.Variable( tf.random.uniform( [1] ) )

In [27]:
# cost 함수
def compute_loss():
    z = tf.matmul(x,w) + b
    cost_i = tf.nn.sigmoid_cross_entropy_with_logits( labels=y, logits=z)  
    cost = tf.reduce_mean( cost_i )
    return cost

In [28]:
optimizer = Adam(0.1)
for i in range(1000):
    optimizer.minimize( compute_loss, var_list=[w,b])
    print(i, 'cost:', compute_loss().numpy() )

0 cost: 1.029095
1 cost: 0.9006097
2 cost: 0.7907518
3 cost: 0.70184475
4 cost: 0.63507855
5 cost: 0.59001243
6 cost: 0.56434864
7 cost: 0.5541672
8 cost: 0.55465025
9 cost: 0.5610425
10 cost: 0.5694228
11 cost: 0.5770338
12 cost: 0.5822325
13 cost: 0.5842633
14 cost: 0.5830056
15 cost: 0.57875806
16 cost: 0.5720756
17 cost: 0.56364965
18 cost: 0.55421835
19 cost: 0.5444983
20 cost: 0.53513235
21 cost: 0.52664554
22 cost: 0.51941645
23 cost: 0.5136589
24 cost: 0.5094205
25 cost: 0.50659704
26 cost: 0.50496083
27 cost: 0.50420165
28 cost: 0.5039715
29 cost: 0.50393105
30 cost: 0.50378555
31 cost: 0.5033146
32 cost: 0.5023856
33 cost: 0.5009563
34 cost: 0.49906528
35 cost: 0.49681485
36 cost: 0.49434757
37 cost: 0.49182233
38 cost: 0.48939145
39 cost: 0.48718163
40 cost: 0.48528194
41 cost: 0.4837374
42 cost: 0.48255017
43 cost: 0.4816855
44 cost: 0.48108238
45 cost: 0.4806657
46 cost: 0.48035732
47 cost: 0.480087
48 cost: 0.47979942
49 cost: 0.47945803
50 cost: 0.47904637
51 cost: 0.478

458 cost: 0.4668443
459 cost: 0.4668443
460 cost: 0.46684423
461 cost: 0.46684435
462 cost: 0.46684423
463 cost: 0.46684423
464 cost: 0.4668443
465 cost: 0.4668443
466 cost: 0.4668443
467 cost: 0.4668443
468 cost: 0.4668443
469 cost: 0.4668443
470 cost: 0.46684423
471 cost: 0.4668443
472 cost: 0.4668443
473 cost: 0.46684423
474 cost: 0.4668442
475 cost: 0.46684435
476 cost: 0.4668443
477 cost: 0.4668443
478 cost: 0.4668443
479 cost: 0.46684423
480 cost: 0.46684423
481 cost: 0.4668443
482 cost: 0.46684423
483 cost: 0.46684423
484 cost: 0.4668443
485 cost: 0.46684423
486 cost: 0.46684423
487 cost: 0.4668442
488 cost: 0.4668443
489 cost: 0.4668442
490 cost: 0.46684423
491 cost: 0.46684435
492 cost: 0.4668443
493 cost: 0.4668443
494 cost: 0.4668443
495 cost: 0.4668443
496 cost: 0.4668443
497 cost: 0.4668442
498 cost: 0.4668443
499 cost: 0.4668442
500 cost: 0.46684423
501 cost: 0.4668443
502 cost: 0.4668442
503 cost: 0.4668443
504 cost: 0.4668443
505 cost: 0.46684423
506 cost: 0.4668443
507

905 cost: 0.4668443
906 cost: 0.4668443
907 cost: 0.4668443
908 cost: 0.4668443
909 cost: 0.4668443
910 cost: 0.4668443
911 cost: 0.4668443
912 cost: 0.4668443
913 cost: 0.4668443
914 cost: 0.4668443
915 cost: 0.4668443
916 cost: 0.4668443
917 cost: 0.4668443
918 cost: 0.4668443
919 cost: 0.4668443
920 cost: 0.4668443
921 cost: 0.4668443
922 cost: 0.4668443
923 cost: 0.4668443
924 cost: 0.4668443
925 cost: 0.4668443
926 cost: 0.4668443
927 cost: 0.4668443
928 cost: 0.4668443
929 cost: 0.4668443
930 cost: 0.4668443
931 cost: 0.4668443
932 cost: 0.4668443
933 cost: 0.4668443
934 cost: 0.4668443
935 cost: 0.4668443
936 cost: 0.4668443
937 cost: 0.4668443
938 cost: 0.4668443
939 cost: 0.4668443
940 cost: 0.4668443
941 cost: 0.4668443
942 cost: 0.4668443
943 cost: 0.4668443
944 cost: 0.4668443
945 cost: 0.4668443
946 cost: 0.4668443
947 cost: 0.4668443
948 cost: 0.4668443
949 cost: 0.4668443
950 cost: 0.4668443
951 cost: 0.4668443
952 cost: 0.4668443
953 cost: 0.4668443
954 cost: 0.4668443


예측함수

In [29]:
x_data[0] # 요금, 성별,pclass, 나이, p1,p2,p3,p4

array([0.01415106, 1.        , 0.        , 0.        , 0.        ,
       1.        , 0.27117366])

In [30]:
# 예측함수
def hxfn(xdata):
    xd = tf.constant(xdata, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return (hx.numpy()>0.5) +0

In [31]:
hxfn(     scaler.transform( [    [30,1,25,1,0,0,0,]]       )        )

array([[1]])

In [32]:
# 예측함수
def hxfn2(xdata):
    xd = tf.constant(xdata, tf.float32)
    z = tf.matmul(xd, w) + b
    hx = tf.nn.sigmoid(z)
    return hx.numpy()

In [33]:
hxfn2( scaler.transform( [    [30,1,25,1,0,0,0,]]       )        )

array([[0.64004666]], dtype=float32)

## 케라스

In [34]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
dense = Dense(units = 1, input_dim =7 ) # w : 3x1   b : 1   초기값
model = Sequential([dense])
model.compile(loss='mse',optimizer=Adam(0.1), metrics=['acc'])
# n행 3열
h = model.fit(x_train, y_train, epochs=500) # x값을 행렬로 주어야함


Epoch 1/500
20/20 [==============================] - 0s 2ms/step - loss: 0.2194 - acc: 0.7335
Epoch 2/500
20/20 [==============================] - 0s 577us/step - loss: 0.1611 - acc: 0.7769
Epoch 3/500
20/20 [==============================] - 0s 582us/step - loss: 0.1567 - acc: 0.7817
Epoch 4/500
20/20 [==============================] - 0s 577us/step - loss: 0.1534 - acc: 0.7801
Epoch 5/500
20/20 [==============================] - 0s 525us/step - loss: 0.1560 - acc: 0.7849
Epoch 6/500
20/20 [==============================] - 0s 525us/step - loss: 0.1568 - acc: 0.7801
Epoch 7/500
20/20 [==============================] - 0s 553us/step - loss: 0.1572 - acc: 0.7769
Epoch 8/500
20/20 [==============================] - 0s 577us/step - loss: 0.1563 - acc: 0.7769
Epoch 9/500
20/20 [==============================] - 0s 630us/step - loss: 0.1541 - acc: 0.7785
Epoch 10/500
20/20 [==============================] - 0s 577us/step - loss: 0.1598 - acc: 0.7849
Epoch 11/500
20/20 [=====================

20/20 [==============================] - 0s 472us/step - loss: 0.1657 - acc: 0.7673
Epoch 86/500
20/20 [==============================] - 0s 472us/step - loss: 0.1614 - acc: 0.7833
Epoch 87/500
20/20 [==============================] - 0s 472us/step - loss: 0.1566 - acc: 0.7801
Epoch 88/500
20/20 [==============================] - 0s 472us/step - loss: 0.1644 - acc: 0.7640
Epoch 89/500
20/20 [==============================] - 0s 472us/step - loss: 0.1609 - acc: 0.7817
Epoch 90/500
20/20 [==============================] - 0s 472us/step - loss: 0.1569 - acc: 0.7817
Epoch 91/500
20/20 [==============================] - 0s 525us/step - loss: 0.1603 - acc: 0.7929
Epoch 92/500
20/20 [==============================] - 0s 525us/step - loss: 0.1633 - acc: 0.7705
Epoch 93/500
20/20 [==============================] - 0s 472us/step - loss: 0.1575 - acc: 0.7721
Epoch 94/500
20/20 [==============================] - 0s 472us/step - loss: 0.1599 - acc: 0.7705
Epoch 95/500
20/20 [=======================

20/20 [==============================] - 0s 630us/step - loss: 0.1594 - acc: 0.7849
Epoch 169/500
20/20 [==============================] - 0s 630us/step - loss: 0.1570 - acc: 0.7865
Epoch 170/500
20/20 [==============================] - 0s 630us/step - loss: 0.1592 - acc: 0.7689
Epoch 171/500
20/20 [==============================] - 0s 734us/step - loss: 0.1674 - acc: 0.7737
Epoch 172/500
20/20 [==============================] - 0s 577us/step - loss: 0.1648 - acc: 0.7785
Epoch 173/500
20/20 [==============================] - 0s 630us/step - loss: 0.1560 - acc: 0.7817
Epoch 174/500
20/20 [==============================] - 0s 630us/step - loss: 0.1573 - acc: 0.7817
Epoch 175/500
20/20 [==============================] - 0s 682us/step - loss: 0.1543 - acc: 0.7833
Epoch 176/500
20/20 [==============================] - 0s 577us/step - loss: 0.1654 - acc: 0.7961
Epoch 177/500
20/20 [==============================] - 0s 524us/step - loss: 0.1581 - acc: 0.7833
Epoch 178/500
20/20 [=============

20/20 [==============================] - 0s 577us/step - loss: 0.1596 - acc: 0.7833
Epoch 252/500
20/20 [==============================] - 0s 577us/step - loss: 0.1598 - acc: 0.7705
Epoch 253/500
20/20 [==============================] - 0s 525us/step - loss: 0.1667 - acc: 0.7464
Epoch 254/500
20/20 [==============================] - 0s 577us/step - loss: 0.1729 - acc: 0.7576
Epoch 255/500
20/20 [==============================] - 0s 577us/step - loss: 0.1620 - acc: 0.7817
Epoch 256/500
20/20 [==============================] - 0s 577us/step - loss: 0.1556 - acc: 0.7801
Epoch 257/500
20/20 [==============================] - 0s 577us/step - loss: 0.1571 - acc: 0.7817
Epoch 258/500
20/20 [==============================] - 0s 577us/step - loss: 0.1602 - acc: 0.7833
Epoch 259/500
20/20 [==============================] - 0s 577us/step - loss: 0.1584 - acc: 0.7881
Epoch 260/500
20/20 [==============================] - 0s 577us/step - loss: 0.1636 - acc: 0.7608
Epoch 261/500
20/20 [=============

20/20 [==============================] - 0s 578us/step - loss: 0.1601 - acc: 0.7689
Epoch 335/500
20/20 [==============================] - 0s 577us/step - loss: 0.1653 - acc: 0.7785
Epoch 336/500
20/20 [==============================] - 0s 525us/step - loss: 0.1609 - acc: 0.7785
Epoch 337/500
20/20 [==============================] - 0s 525us/step - loss: 0.1584 - acc: 0.7785
Epoch 338/500
20/20 [==============================] - 0s 576us/step - loss: 0.1599 - acc: 0.7833
Epoch 339/500
20/20 [==============================] - 0s 525us/step - loss: 0.1619 - acc: 0.7721
Epoch 340/500
20/20 [==============================] - 0s 525us/step - loss: 0.1706 - acc: 0.7785
Epoch 341/500
20/20 [==============================] - 0s 630us/step - loss: 0.1572 - acc: 0.7801
Epoch 342/500
20/20 [==============================] - 0s 630us/step - loss: 0.1564 - acc: 0.7721
Epoch 343/500
20/20 [==============================] - 0s 578us/step - loss: 0.1621 - acc: 0.7849
Epoch 344/500
20/20 [=============

20/20 [==============================] - 0s 577us/step - loss: 0.1625 - acc: 0.7801
Epoch 418/500
20/20 [==============================] - 0s 525us/step - loss: 0.1554 - acc: 0.7801
Epoch 419/500
20/20 [==============================] - 0s 525us/step - loss: 0.1580 - acc: 0.7657
Epoch 420/500
20/20 [==============================] - 0s 525us/step - loss: 0.1575 - acc: 0.7865
Epoch 421/500
20/20 [==============================] - 0s 582us/step - loss: 0.1577 - acc: 0.7753
Epoch 422/500
20/20 [==============================] - 0s 577us/step - loss: 0.1574 - acc: 0.7849
Epoch 423/500
20/20 [==============================] - 0s 525us/step - loss: 0.1561 - acc: 0.7801
Epoch 424/500
20/20 [==============================] - 0s 525us/step - loss: 0.1628 - acc: 0.7785
Epoch 425/500
20/20 [==============================] - 0s 525us/step - loss: 0.1624 - acc: 0.7817
Epoch 426/500
20/20 [==============================] - 0s 525us/step - loss: 0.1614 - acc: 0.7833
Epoch 427/500
20/20 [=============

20/20 [==============================] - 0s 525us/step - loss: 0.1667 - acc: 0.7737


In [35]:
w,b = dense.get_weights()
w.shape,b.shape  # w = 3행 1열

((7, 1), (1,))

In [36]:
model.predict(  scaler.transform( [    [30,1,25,1,0,0,0,]]       )    )   

array([[0.15996322]], dtype=float32)

In [37]:
(model.predict(  scaler.transform( [ [30,1,25,1,0,0,0,]]   )  )   >0.5)+0

array([[0]])

In [45]:
x_test.shape

(268, 7)

In [43]:
y_test.shape ,  model.predict(x_test).shape

((268, 1), (268, 1))

In [47]:
y_test

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [49]:
(model.predict(x_test)>0.5)+0

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [50]:
confusion_matrix(y_test, (model.predict(x_test)>0.5)+0)

array([[160,   5],
       [ 52,  51]], dtype=int64)

In [ ]:
model.predict(x_data)

# 오차행렬

In [ ]:
y_data.shape, pred.shape

In [39]:

from sklearn.metrics import confusion_matrix

# 오차행렬
confusion_matrix(y_test, hxfn(x_test) )

array([[92, 73],
       [11, 92]], dtype=int64)

In [ ]:
confusion_matrix(y_test ,model.predict(x_test) )

In [40]:
from sklearn.metrics import accuracy_score
# 정확도
accuracy_score(y_test,hxfn(x_test))

0.6865671641791045

In [41]:
from sklearn.metrics import f1_score
f1_score(y_test, hxfn(x_test)  )

0.6865671641791046

In [ ]:
model.predict(x_test)